import {
  formatSmpte,
  fromTotalFrames,
  isAutoGeneratedMetadataJson,
  isoZ,
} from '@autologger/domain';
import { describe, expect, it } from 'vitest';
import { eventRowToRpc } from '@autologger/session-core/eventStore';
import { boundCore } from './boundCore';
import { insertRaw, rawRows, type TestStorage } from './sessionRows';

describe('eventRowToRpc', () => {
  it('maps a row with a timecode', () => {
    const r = {
      id: 'e1',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      frame_rate: 24,
      timecode_total_frames: 48,
      category: 'note',
      message: 'hi',
      metadata_json: '{"a":1}',
    };
    expect(eventRowToRpc(r)).toEqual({
      event_id: 'e1',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      timecode: formatSmpte(fromTotalFrames(48, 24)),
      frame_rate: 24,
      timecode_total_frames: 48,
      category: 'note',
      message: 'hi',
      metadata_json: '{"a":1}',
      version: 1,
    });
  });

  it('nulls timecode fields when timecode_total_frames is absent, defaults metadata', () => {
    const r = {
      id: 'e2',
      wall_time_utc: '2026-06-25T00:00:01.000Z',
      frame_rate: 24,
      timecode_total_frames: null,
      category: 'internal',
      message: 'rec start',
      metadata_json: null,
    };
    expect(eventRowToRpc(r)).toEqual({
      event_id: 'e2',
      wall_time_utc: '2026-06-25T00:00:01.000Z',
      timecode: null,
      frame_rate: null,
      timecode_total_frames: null,
      category: 'internal',
      message: 'rec start',
      metadata_json: '{}',
      version: 1,
    });
  });
});

// code-health-tail task 2.2 (design D10) — behavior pin over a REAL core
// (in-memory SQLite then; Postgres since session-tables), written BEFORE the count SQL moved into
// core.eventCounts(): listEvents' total/loggedTotal must exclude
// internal-category rows regardless of casing/whitespace, and near-miss
// categories must still count as logged.
describe('listEvents counts over a real core (D10 pin)', () => {
  it('total counts every event; loggedTotal excludes internal (any casing/whitespace)', async () => {
    const { read, storage } = await boundCore();
    const categories = [
      'mark', // logged
      'note', // logged
      'internal', // filtered
      'Internal', // filtered (casing)
      ' INTERNAL ', // filtered (casing + surrounding spaces)
      '\tinternal', // logged — trim() strips SPACES only, a tab survives
      'INTERNAL', // filtered
      'internally', // logged
      'x internal', // logged
    ];
    for (const [i, cat] of categories.entries()) {
      await insertRaw(storage, 'session_events', {
        id: `e${i}`,
        wall_time_utc: '2026-06-25T00:00:00.000Z',
        frame_rate: 30,
        category: cat,
        message: `m${i}`,
      });
    }
    const out = await read((s) => s.events.listEvents({ limit: 100, offset: 0 }));
    expect(out.total).toBe(9);
    expect(out.loggedTotal).toBe(5);
    expect(out.events).toHaveLength(9);
  });
});

// event-generate-hardening task 2.1 (design D6) — deleteEventsByIds() replaces
// deleteAutoGeneratedEvents(): an explicit id set (the route's pre-spawn
// snapshot), one DELETE inside the one caller transaction (the ids as one JSON
// text bind since session-tables D5; it was chunked at 500 ids on SQLite), one
// event.changed broadcast iff the total deleted count > 0. The first two
// tests below characterize the same broadcast/transaction behavior the old
// predicate-delete's tests pinned; the remaining tests cover the id-set
// contract and a large id set the old RPC never needed.
describe('deleteEventsByIds', () => {
  it('deletes exactly the given ids, leaves everything else, and broadcasts once', async () => {
    const { run, read, storage, broadcasts } = await boundCore();
    const rows = [
      ['auto', '{"auto_generated":true}'],
      ['auto-extra', '{"auto_generated":true,"run":"r1"}'],
      ['manual', '{}'],
      ['false', '{"auto_generated":false}'],
    ];
    for (const [index, [id, metadataJson]] of rows.entries()) {
      await insertRaw(storage, 'session_events', {
        id: id,
        wall_time_utc: `2026-06-25T00:00:0${index}.000Z`,
        frame_rate: 24,
        timecode_total_frames: index,
        category: 'note',
        message: id,
        metadata_json: metadataJson,
      });
    }

    const deleted = await run((s) => s.events.deleteEventsByIds(['auto', 'auto-extra']));

    expect(deleted).toBe(2);
    expect(await rawRows(storage, 'session_events', { columns: 'id', orderBy: 'id' })).toEqual([
      { id: 'false' },
      { id: 'manual' },
    ]);
    expect(await read((s) => s.core.revision())).toBe(1);
    expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
  });

  it('does not bump the revision or broadcast when none of the given ids exist', async () => {
    const { run, read, storage, broadcasts } = await boundCore();
    await insertRaw(storage, 'session_events', {
      id: 'manual',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      frame_rate: 24,
      timecode_total_frames: 0,
      category: 'note',
      message: 'manual',
      metadata_json: '{}',
    });

    expect(await run((s) => s.events.deleteEventsByIds(['no-such-id', 'also-missing']))).toBe(0);
    expect(await read((s) => s.core.revision())).toBe(0);
    expect(broadcasts).toEqual([]);
    expect(await rawRows(storage, 'session_events', { columns: 'id' })).toEqual([{ id: 'manual' }]);
  });

  // event-generate-hardening task 2.3(d) — the mid-run-manual-delete property
  // (design D4: "if an operator manually deleted an old auto row mid-run,
  // `deleted` shrinks accordingly"). The int-level fake-CLI harness (see
  // events.generate.int.test.ts) has no mechanism to pause a fixture
  // subprocess mid-turn and interleave a real HTTP delete, so this pins the
  // property at the level that actually decides it: deleteEventsByIds()
  // receives the pre-spawn snapshot ids verbatim regardless of what happened
  // to the rows since the snapshot was taken — a ROW ALREADY GONE (the
  // simulated mid-run manual delete) by the time this call runs still yields
  // a correctly-shrunk count over only the ids still present.
  it('reflects a mid-run manual delete of one snapshotted id: only the still-present id is removed', async () => {
    const { run, read, storage, broadcasts } = await boundCore();
    const rows: Array<[string, string]> = [
      ['auto-1', '{"auto_generated":true,"auto_generate_run_id":"old-run"}'],
      ['auto-2', '{"auto_generated":true,"auto_generate_run_id":"old-run"}'],
      ['manual', '{}'],
    ];
    for (const [index, [id, metadataJson]] of rows.entries()) {
      await insertRaw(storage, 'session_events', {
        id: id,
        wall_time_utc: `2026-06-25T00:00:0${index}.000Z`,
        frame_rate: 24,
        timecode_total_frames: index,
        category: 'note',
        message: id,
        metadata_json: metadataJson,
      });
    }
    const snapshotIds = ['auto-1', 'auto-2']; // the pre-spawn snapshot, as the route would build it

    // Simulate an operator manually deleting one of the snapshotted rows
    // WHILE the run is still in flight — before the post-success delete call
    // (this exercises the exact same DELETE the operator's manual route uses).
    await run((s) =>
      s.core.db.run(
        'DELETE FROM session_events WHERE session_id = ? AND id = ?',
        s.core.sessionId,
        'auto-1',
      ),
    );

    const deleted = await run((s) => s.events.deleteEventsByIds(snapshotIds));

    expect(deleted).toBe(1); // only auto-2 was still present to remove
    expect(await rawRows(storage, 'session_events', { columns: 'id', orderBy: 'id' })).toEqual([
      { id: 'manual' },
    ]);
    // session-row-versions D2: the simulated manual delete is a changing write too, so the
    // revision is 2 after it and the surviving delete.
    expect(await read((s) => s.core.revision())).toBe(2);
    expect(broadcasts).toEqual([{ type: 'event.changed', revision: 2 }]);
  });

  it('an empty id array deletes nothing and does not broadcast', async () => {
    const { run, read, broadcasts } = await boundCore();
    expect(await run((s) => s.events.deleteEventsByIds([]))).toBe(0);
    expect(await read((s) => s.core.revision())).toBe(0);
    expect(broadcasts).toEqual([]);
  });

  it('deletes a 1,001-id set inside one call: all rows gone, one broadcast', async () => {
    const { run, read, storage, broadcasts } = await boundCore();
    const N = 1001; // > the 500-id chunk boundary SQLite needed
    const ids: string[] = [];
    const rows = [];
    for (let i = 0; i < N; i += 1) {
      const id = `e${i}`;
      ids.push(id);
      rows.push({
        id: id,
        wall_time_utc: '2026-06-25T00:00:00.000Z',
        frame_rate: 24,
        timecode_total_frames: i,
        category: 'note',
        message: id,
        metadata_json: '{"auto_generated":true}',
      });
    }
    await insertRaw(storage, 'session_events', rows);

    const deleted = await run((s) => s.events.deleteEventsByIds(ids));

    expect(deleted).toBe(N);
    expect(await rawRows(storage, 'session_events', { columns: 'id' })).toEqual([]);
    expect(await read((s) => s.core.revision())).toBe(1);
    expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
  });
});

// event-generate-hardening task 1.2 (design D1) — hasAutoGeneratedEvents():
// a read-only EXISTS check over the same SQL predicate the events route's JS
// auto-predicate mirrors when it computes the regenerate id snapshot passed
// to deleteEventsByIds, independent of any page/window.
describe('hasAutoGeneratedEvents', () => {
  async function insertEvent(
    storage: TestStorage,
    id: string,
    metadataJson: string,
    index: number,
  ) {
    await insertRaw(storage, 'session_events', {
      id: id,
      wall_time_utc: `2026-06-25T00:00:0${index}.000Z`,
      frame_rate: 24,
      timecode_total_frames: index,
      category: 'note',
      message: id,
      metadata_json: metadataJson,
    });
  }

  it('is false when the session has no events', async () => {
    const { read } = await boundCore();
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(false);
  });

  it('is false when only non-auto/false/malformed metadata exists (predicate edges)', async () => {
    const { read, storage } = await boundCore();
    const rows: Array<[string, string]> = [
      ['manual', '{}'],
      ['false', '{"auto_generated":false}'],
      ['number', '{"auto_generated":1}'],
      ['string', '{"auto_generated":"true"}'],
      ['malformed', '{"auto_generated":true'],
    ];
    for (const [index, [id, metadataJson]] of rows.entries()) {
      await insertEvent(storage, id, metadataJson, index);
    }
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(false);
  });

  it('is true when at least one row carries auto_generated === true (JSON boolean)', async () => {
    const { read, storage } = await boundCore();
    await insertEvent(storage, 'manual', '{}', 0);
    await insertEvent(storage, 'auto', '{"auto_generated":true}', 1);
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(true);
  });

  it('is true for an auto row outside any list page/window (whole-session semantics)', async () => {
    const { read, storage } = await boundCore();
    // 3 manual rows first, then the one auto row last — a listEvents({limit:1})
    // window would never see it, but the whole-session check must.
    await insertEvent(storage, 'm0', '{}', 0);
    await insertEvent(storage, 'm1', '{}', 1);
    await insertEvent(storage, 'm2', '{}', 2);
    await insertEvent(storage, 'auto', '{"auto_generated":true}', 3);
    const page = await read((s) => s.events.listEvents({ limit: 1, offset: 0 }));
    expect(page.events.some((e) => e.event_id === 'auto')).toBe(false);
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(true);
  });

  it('does not mutate revision or broadcast (read-only)', async () => {
    const { read, storage, broadcasts } = await boundCore();
    await insertEvent(storage, 'auto', '{"auto_generated":true}', 0);
    const revBefore = await read((s) => s.core.revision());
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(true);
    expect(await read((s) => s.core.revision())).toBe(revBefore);
    expect(broadcasts).toEqual([]);
  });
});

// event-generate-hardening task 1.2 (gate ruling E3) — the route's JS
// isAuto predicate (isAutoGeneratedMetadataJson, exported from
// @autologger/domain and consumed by routers/events.ts) and the event
// store's SQL predicate must agree on every metadata_json value in this
// corpus: two implementations, one tested meaning. (persistence-package-
// extraction task 4.1: this predicate moved from routers/events.ts to
// @autologger/domain, killing the only session -> server production/test
// edge; the parity relationship this comment describes is unchanged.)
// session-tables D5 (A2): the SQL predicate reads the metadata as `jsonb`. Two
// rows outside the original corpus: duplicate keys read as the last value, as
// in JavaScript (SQLite took the first); and a `\u0000` escape is not valid
// `jsonb`, so SQL reads it as not auto-generated while JavaScript says yes —
// the documented exception (`sql` below). Generated events' metadata is built
// from catalog labels, which cannot hold NUL.
describe('JS↔SQL auto-generated predicate parity (gate ruling E3)', () => {
  const corpus: Array<{ label: string; metadataJson: string; expected: boolean; sql?: boolean }> = [
    { label: 'true (JSON boolean)', metadataJson: '{"auto_generated":true}', expected: true },
    {
      label: 'true with extra keys',
      metadataJson: '{"auto_generated":true,"auto_generate_run_id":"r1"}',
      expected: true,
    },
    { label: 'false', metadataJson: '{"auto_generated":false}', expected: false },
    { label: 'number 1', metadataJson: '{"auto_generated":1}', expected: false },
    { label: 'string "true"', metadataJson: '{"auto_generated":"true"}', expected: false },
    { label: 'missing key', metadataJson: '{}', expected: false },
    { label: 'empty string (defaults to {})', metadataJson: '', expected: false },
    { label: 'malformed JSON', metadataJson: '{"auto_generated":true', expected: false },
    { label: 'JSON array (not an object)', metadataJson: '[true]', expected: false },
    { label: 'JSON null', metadataJson: 'null', expected: false },
    {
      label: 'duplicate keys (the last wins)',
      metadataJson: '{"auto_generated":false,"auto_generated":true}',
      expected: true,
    },
    {
      label: 'a \\u0000 escape (documented exception: not valid jsonb)',
      metadataJson: '{"auto_generated":true,"x":"\\u0000"}',
      expected: true,
      sql: false,
    },
  ];

  it.each(corpus)('$label → $expected, agreeing across JS and SQL', async ({
    metadataJson,
    expected,
    sql,
  }) => {
    // JS side: the exact route predicate.
    expect(isAutoGeneratedMetadataJson(metadataJson)).toBe(expected);

    // SQL side: hasAutoGeneratedEvents() over a single row carrying this
    // metadata — the same predicate the route uses to compute the id
    // snapshot deleteEventsByIds() then removes.
    const { read, storage } = await boundCore();
    await insertRaw(storage, 'session_events', {
      id: 'row',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      frame_rate: 24,
      timecode_total_frames: 0,
      category: 'note',
      message: 'row',
      metadata_json: metadataJson,
    });
    expect(await read((s) => s.events.hasAutoGeneratedEvents())).toBe(sql ?? expected);
  });
});

// auto-generate-event-logs task 2.3 (design D4) — ONE insert path: addEvent
// gains an optional explicit-anchor parameter; when absent, behavior is
// byte-identical to today (pinned below over a real rolling transport), and
// when present the timecodeForMark derivation is bypassed entirely.
describe('addEvent over a real core', () => {
  /** Rolling transport at a known instant: roll started 5s before the fake
   * clock's default now (1_000_000ms), 50 frames already banked. */
  /** A rolling transport. Its setup write advances the revision to 1 (session-row-versions D2), so
   * the event under test is revision 2. */
  async function rollingFixture() {
    const rt = await boundCore();
    await rt.run((s) =>
      s.core.db.run(
        'UPDATE session_transport SET is_rolling = ?, current_take = ?, roll_started_at_utc = ?, elapsed_frames = ? WHERE session_id = ?',
        1,
        1,
        isoZ(new Date(995_000)),
        50,
        s.core.sessionId,
      ),
    );
    return rt;
  }
  const ctx = { frameRate: 24, startOffsetFrames: 100 };

  describe('manual path (parameter absent) — byte-identical pin', () => {
    it('derives via timecodeForMark from the rolling transport at now(), broadcasts one event.changed', async () => {
      const { run, storage, broadcasts } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'hi',
          metadataJson: '',
          markedAtUtc: null,
          ctx,
        }),
      );
      // 100 offset + 50 elapsed + trunc(5s * 24fps) = 270
      expect(out.event).toEqual({
        event_id: out.event.event_id,
        wall_time_utc: '1970-01-01T00:16:40.000Z',
        timecode: formatSmpte(fromTotalFrames(270, 24)),
        frame_rate: 24,
        timecode_total_frames: 270,
        category: 'note',
        message: 'hi',
        metadata_json: '{}',
        version: 1,
      });
      expect(out.projection.event_count).toBe(1);
      expect(out.projection.max_timecode_total_frames).toBe(270);
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 2 }]);
      // Pin the INSERT columns on the raw row, not just the RPC mapping.
      const [r] = await rawRows(storage, 'session_events', {
        where: 'id = ?',
        binds: [out.event.event_id],
      });
      expect(r).toEqual({
        id: out.event.event_id,
        wall_time_utc: '1970-01-01T00:16:40.000Z',
        frame_rate: 24,
        timecode_total_frames: 270,
        category: 'note',
        message: 'hi',
        metadata_json: '{}',
        version: 1,
      });
    });

    it('honors markedAtUtc as the mark instant for both wall time and timecode', async () => {
      const { run, broadcasts } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'marked',
          metadataJson: '{"a":1}',
          markedAtUtc: '1970-01-01T00:16:37.000Z', // 2s after roll start
          ctx,
        }),
      );
      // 100 offset + 50 elapsed + trunc(2s * 24fps) = 198
      expect(out.event.wall_time_utc).toBe('1970-01-01T00:16:37.000Z');
      expect(out.event.timecode_total_frames).toBe(198);
      expect(out.event.metadata_json).toBe('{"a":1}');
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 2 }]);
    });
  });

  // chunked-live-recording D9 — storedWallTimeUtc decouples the STORED wall
  // time from the wall time timecodeForMark derives the timecode from: the
  // timecode still anchors at the rolling transport's position at now()
  // (unaffected — proves the youtube-audio-import spec's
  // `timecode_total_frames` pin survives), but the stored wall_time_utc is
  // the caller's override, not isoZ(new Date(markMs)).
  describe('storedWallTimeUtc override (design D9)', () => {
    it('stores the override as wall_time_utc while timecode still derives from now() via the rolling transport', async () => {
      const { run, storage, broadcasts } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'internal',
          message: 'Recording 1 Started',
          metadataJson: '{}',
          markedAtUtc: null,
          ctx,
          storedWallTimeUtc: '2020-01-01T00:00:00.000Z', // an unrelated, much-earlier wall time
        }),
      );
      // Same timecode as the "manual path" now()-derived pin above (100
      // offset + 50 elapsed + trunc(5s * 24fps) = 270) — storedWallTimeUtc
      // does NOT perturb the transport-position derivation.
      expect(out.event.timecode_total_frames).toBe(270);
      expect(out.event.frame_rate).toBe(24);
      // But the STORED wall time is the override, not isoZ(now()).
      expect(out.event.wall_time_utc).toBe('2020-01-01T00:00:00.000Z');
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 2 }]);
      const [r] = await rawRows(storage, 'session_events', {
        columns: 'wall_time_utc',
        where: 'id = ?',
        binds: [out.event.event_id],
      });
      expect(r).toEqual({ wall_time_utc: '2020-01-01T00:00:00.000Z' });
    });

    it('is ignored when explicitAnchor is present (explicitAnchor owns wall time in that branch)', async () => {
      const { run } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'generated',
          metadataJson: '',
          markedAtUtc: null,
          ctx,
          explicitAnchor: { timecodeTotalFrames: 5, wallTimeUtc: '2026-06-25T00:00:05.000Z' },
          storedWallTimeUtc: '2020-01-01T00:00:00.000Z', // must be ignored
        }),
      );
      expect(out.event.wall_time_utc).toBe('2026-06-25T00:00:05.000Z');
    });

    it('omitted falls back to isoZ(new Date(markMs)) — byte-identical to the pre-D9 manual path', async () => {
      const { run } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'hi',
          metadataJson: '',
          markedAtUtc: null,
          ctx,
        }),
      );
      expect(out.event.wall_time_utc).toBe('1970-01-01T00:16:40.000Z'); // same as the manual-path pin above
    });
  });

  describe('explicit anchor (design D4)', () => {
    it('stores the given frames + wall time verbatim, bypassing the transport derivation', async () => {
      const { run, storage, broadcasts } = await rollingFixture();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'generated',
          metadataJson: '{"auto_generated":true}',
          markedAtUtc: null,
          ctx,
          explicitAnchor: {
            timecodeTotalFrames: 12345,
            wallTimeUtc: '2026-06-25T00:01:00.000Z',
          },
        }),
      );
      expect(out.event).toEqual({
        event_id: out.event.event_id,
        wall_time_utc: '2026-06-25T00:01:00.000Z',
        timecode: formatSmpte(fromTotalFrames(12345, 24)),
        frame_rate: 24,
        timecode_total_frames: 12345,
        category: 'note',
        message: 'generated',
        metadata_json: '{"auto_generated":true}',
        version: 1,
      });
      expect(out.projection.event_count).toBe(1);
      expect(out.projection.max_timecode_total_frames).toBe(12345);
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 2 }]);
      const [r] = await rawRows(storage, 'session_events', {
        where: 'id = ?',
        binds: [out.event.event_id],
      });
      expect(r).toEqual({
        id: out.event.event_id,
        wall_time_utc: '2026-06-25T00:01:00.000Z',
        frame_rate: 24,
        timecode_total_frames: 12345,
        category: 'note',
        message: 'generated',
        metadata_json: '{"auto_generated":true}',
        version: 1,
      });
    });

    it('stores frame_rate rounded from ctx exactly as the manual path does (29.97)', async () => {
      const { run } = await boundCore();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'df',
          metadataJson: '',
          markedAtUtc: null,
          ctx: { frameRate: 29.97, startOffsetFrames: 0 },
          explicitAnchor: { timecodeTotalFrames: 60, wallTimeUtc: '2026-06-25T00:00:02.000Z' },
        }),
      );
      expect(out.event.frame_rate).toBe(29.97);
      expect(out.event.timecode).toBe(formatSmpte(fromTotalFrames(60, 29.97)));
      expect(out.event.metadata_json).toBe('{}');
    });

    it('rounds a >3-decimal ctx rate exactly like the manual path (23.976023976 → 23.976)', async () => {
      // 29.97 is already 3-decimal, so it cannot detect a rounding divergence
      // between the explicit-anchor path and fromTotalFrames' millidecimal
      // rounding (Phase-2 review finding 3) — this rate can.
      const rate = 23.976023976;
      const { run, storage } = await boundCore();
      const out = await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'ntsc-film',
          metadataJson: '',
          markedAtUtc: null,
          ctx: { frameRate: rate, startOffsetFrames: 0 },
          explicitAnchor: { timecodeTotalFrames: 24, wallTimeUtc: '2026-06-25T00:00:01.000Z' },
        }),
      );
      expect(out.event.frame_rate).toBe(23.976);
      expect(out.event.frame_rate).toBe(fromTotalFrames(24, rate).frame_rate);
      const [r] = await rawRows(storage, 'session_events', {
        columns: 'frame_rate',
        where: 'id = ?',
        binds: [out.event.event_id],
      });
      expect(r).toEqual({ frame_rate: 23.976 });
    });

    it('still honors suppressBroadcast (same broadcast handling as the manual path)', async () => {
      const { run, read, broadcasts } = await boundCore();
      await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'quiet',
          metadataJson: '',
          markedAtUtc: null,
          ctx,
          explicitAnchor: { timecodeTotalFrames: 1, wallTimeUtc: '2026-06-25T00:00:00.000Z' },
          suppressBroadcast: true,
        }),
      );
      expect(broadcasts).toEqual([]);
      expect(await read((s) => s.core.revision())).toBe(1); // revision still bumps
    });

    it('interleaves per wall_time_utc ASC among manual events in listEvents', async () => {
      const { run, read } = await boundCore();
      await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'first-manual',
          metadataJson: '',
          markedAtUtc: '2026-06-25T00:00:00.000Z',
          ctx,
        }),
      );
      await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'second-manual',
          metadataJson: '',
          markedAtUtc: '2026-06-25T00:02:00.000Z',
          ctx,
        }),
      );
      await run((s) =>
        s.events.addEvent({
          category: 'note',
          message: 'generated-between',
          metadataJson: '',
          markedAtUtc: null,
          ctx,
          explicitAnchor: {
            timecodeTotalFrames: 24 * 60,
            wallTimeUtc: '2026-06-25T00:01:00.000Z',
          },
        }),
      );
      const out = await read((s) => s.events.listEvents({ limit: 10, offset: 0 }));
      expect(out.events.map((e) => e.message)).toEqual([
        'first-manual',
        'generated-between',
        'second-manual',
      ]);
    });
  });
});
