// Session isolation on Postgres (session-tables design D4 guard 2; core-ports-architecture
// "Sessions are isolated"): every hub write method runs on session A while session B holds rows in
// all nine session tables, and B's rows are byte-identical afterwards; no read on A returns a row
// of B. A's calls name B's ids wherever they take one.

import type { SessionHub } from '@autologger/session-core/SessionHub';
import { UI_SNAPSHOT_LABEL_KEY } from '@autologger/domain';
import { describe, expect, it } from 'vitest';
import { catalogRoot, createSessionRow, testRegistry } from './sessionRows';

const CTX = { frameRate: 24, startOffsetFrames: 0 };

const TABLES: Record<string, string> = {
  session_events: 'id',
  session_transport: 'session_id',
  session_audio_segments: 'id',
  session_transcript_words: 'id',
  session_topics: 'id',
  session_transcript_paragraphs: 'id',
  session_transcript_sentiment: 'id',
  session_dashboards: 'id',
  session_meta: 'key',
};

/** Every row of the session in every session table, read on its own connection. */
async function allRows(sessionId: string): Promise<Record<string, unknown[]>> {
  const db = catalogRoot().bindSystem('test');
  const out: Record<string, unknown[]> = {};
  for (const [table, key] of Object.entries(TABLES)) {
    out[table] = await db.all(
      `SELECT * FROM ${table} WHERE session_id = ? ORDER BY ${key}`,
      sessionId,
    );
  }
  return out;
}

const DASHBOARD = {
  widgets: [{ id: 'w1', type: 'session_duration', title: 'Duration', x: 0, y: 0, w: 4, h: 2 }],
  interactions: [],
};

/** Rows in every session table: events (one auto-generated, one with a snapshot label), the
 * transport, an audio segment with seam parts, words with enrichment, a topic, a dashboard and the
 * lease's meta keys. Returns the ids A's calls will name. */
async function fill(hub: SessionHub, sessionId: string) {
  const { event: plain } = await hub.addEvent({
    category: 'cam',
    message: `plain ${sessionId}`,
    metadataJson: '{}',
    markedAtUtc: null,
    ctx: CTX,
  });
  const { event: auto } = await hub.addEvent({
    category: 'cam',
    message: `auto ${sessionId}`,
    metadataJson: '{"auto_generated":true}',
    markedAtUtc: null,
    ctx: CTX,
  });
  await hub.addEvent({
    category: 'gone-button',
    message: `orphan ${sessionId}`,
    metadataJson: JSON.stringify({ [UI_SNAPSHOT_LABEL_KEY]: 'Camera' }),
    markedAtUtc: null,
    ctx: CTX,
  });
  const segment = await hub.addAudioSegment({
    sessionId,
    mimeType: 'audio/webm',
    startedAtUtc: null,
    endedAtUtc: null,
    recordingOrdinal: 1,
  });
  await hub.appendAudioSeamParts([{ duration_s: 5 }]);
  const [word] = await hub.replaceTranscriptWords(
    [
      {
        session_time: '00:00:01:00',
        speaker: '0',
        word: `w-${sessionId}`,
        start_sec: 1,
        end_sec: 2,
      },
    ],
    {
      paragraphs: [{ start_sec: 1, end_sec: 2, speaker: '0', text: `p-${sessionId}` }],
      sentiment: [
        { start_sec: 1, end_sec: 2, sentiment: 'neutral', sentiment_score: 0, text: 's' },
      ],
    },
  );
  const topic = await hub.insertTopic({
    session_time: '00:00:01',
    duration_sec: 5,
    topic_level: 1,
    summary: `t-${sessionId}`,
  });
  await hub.saveDashboard({
    id: 'primary',
    config: DASHBOARD,
    createdBy: null,
    createdByTurnId: null,
  });
  await hub.saveDashboard({
    id: `dash-${sessionId}`,
    config: DASHBOARD,
    createdBy: null,
    createdByTurnId: null,
  });
  await hub.startTake(CTX);
  await hub.claimLease(`client-${sessionId}`);
  return { plain, auto, segment, word, topic, dashboard: `dash-${sessionId}` };
}

describe('session isolation (D4 guard 2)', () => {
  it("every hub write on A leaves B's rows byte for byte, and no read on A returns a B row", async () => {
    const a = await createSessionRow();
    const b = await createSessionRow();
    const registry = testRegistry();
    const hubB = await registry.get(b);
    const B = await fill(hubB, b);
    const before = await allRows(b);
    for (const rows of Object.values(before)) expect(rows.length).toBeGreaterThan(0);

    const hubA = await registry.get(a);
    // Reads on an empty A see nothing of B.
    expect(await hubA.ensure()).toMatchObject({
      event_count: 0,
      is_rolling: false,
      current_take: 0,
    });
    expect((await hubA.listEvents({ limit: 100, offset: 0 })).events).toEqual([]);
    expect(await hubA.exportEvents()).toEqual([]);
    expect(await hubA.getEvent(B.plain.event_id)).toBeNull();
    expect(await hubA.hasAutoGeneratedEvents()).toBe(false);
    expect((await hubA.statusLive(CTX)).event_count).toBe(0);
    expect((await hubA.transportSnapshot(CTX)).is_rolling).toBe(false);
    expect((await hubA.leaseStatus()).holder_client_id).toBeNull();
    expect(await hubA.listAudioSegments()).toEqual([]);
    expect(await hubA.getAudioSegmentKey(B.segment.id)).toBeNull();
    expect(await hubA.getAudioSeamParts()).toBeNull();
    expect(await hubA.listTranscriptWords()).toEqual([]);
    expect(await hubA.listTranscriptEnrichment()).toEqual({ paragraphs: [], sentiment: [] });
    expect(await hubA.listTopics()).toEqual([]);
    expect(await hubA.getDashboard(B.dashboard)).toBeNull();
    expect(await hubA.listDashboards()).toEqual([]);

    // Every write method on A, with A's own rows in place and B's ids where an id is taken.
    const A = await fill(hubA, a);
    expect(
      await hubA.updateEvent({
        eventId: B.plain.event_id,
        category: 'cam',
        message: 'x',
        wallTimeUtc: B.plain.wall_time_utc,
        timecodeTotalFrames: 1,
        mergeMetadata: (m) => m,
      }),
    ).toBeNull();
    await hubA.updateEvent({
      eventId: A.plain.event_id,
      category: 'cam',
      message: 'edited',
      wallTimeUtc: A.plain.wall_time_utc,
      timecodeTotalFrames: 1,
      mergeMetadata: (m) => m,
    });
    expect((await hubA.deleteEvent(B.plain.event_id)).ok).toBe(false);
    expect(await hubA.deleteEventsByIds([B.plain.event_id, B.auto.event_id])).toBe(0);
    expect(await hubA.deleteEventsByIds([A.auto.event_id])).toBe(1);
    expect(
      await hubA.maybeRelinkOrphans({ validIds: ['cam'], labelToIds: { camera: ['cam'] } }),
    ).toBe(1);
    await hubA.addEventAtTotalFrames({
      category: 'cam',
      message: `plain ${b}`,
      metadataJson: '{}',
      timecodeTotalFrames: 0,
      ctx: CTX,
    });
    await hubA.addEventAtTotalFramesIfAbsent({
      category: 'cam',
      message: 'imported',
      metadataJson: '{}',
      timecodeTotalFrames: 48,
      ctx: CTX,
    });
    await hubA.createAnchoredEvent({
      category: 'cam',
      message: 'anchored',
      metadataJson: '{}',
      timecodeTotalFrames: 24,
      frameRate: 24,
      startOffsetFrames: 0,
      startedAtUtc: '2026-10-03T00:00:00.000Z',
    });
    await hubA.stopTake(CTX);
    await hubA.startTake(CTX);
    await hubA.toggleTake(CTX);
    await hubA.stopTakeWithDuration({ durationS: 2, ctx: CTX });
    await hubA.anchorImportedTake({ recordingOrdinal: 2, durationS: 1, ctx: CTX });
    await hubA.heartbeatLease(`client-${a}`);
    await hubA.releaseLease(`client-${a}`);
    await hubA.releaseLease(`client-${b}`);
    expect(await hubA.claimLease('client-a2')).toBe(true);
    await hubA.addImportedAudioSegment({
      sessionId: a,
      mimeType: 'audio/mpeg',
      startedAtUtc: null,
      endedAtUtc: null,
    });
    expect(await hubA.setAudioSegmentWaveform({ segmentId: B.segment.id, peaks: [1] })).toBe(false);
    await hubA.setAudioSegmentWaveform({ segmentId: A.segment.id, peaks: [1] });
    await hubA.deleteAudioSegment(B.segment.id);
    await hubA.syncAudioFromBlobs([
      { r2_key: `audio/${a}/0009_${crypto.randomUUID()}.webm`, ordinal: 9 },
    ]);
    await hubA.appendAudioSeamParts([{ duration_s: 1 }]);
    await hubA.insertTranscriptWord({ session_time: '00:00:03:00', speaker: '1', word: 'more' });
    expect(await hubA.updateTranscriptWord(B.word.id, { word: 'stolen' })).toBeNull();
    expect(await hubA.deleteTranscriptWord(B.word.id)).toBe(false);
    await hubA.replaceTranscriptWords(
      [{ session_time: '00:00:01:00', speaker: '0', word: 'again', start_sec: 1, end_sec: 2 }],
      { paragraphs: [], sentiment: [] },
    );
    await hubA.replaceTranscriptWordsRemapped(() => ({
      words: [
        { session_time: '00:00:01:00', speaker: '0', word: 'remapped', start_sec: 1, end_sec: 2 },
      ],
      enrichment: {
        paragraphs: [{ start_sec: null, end_sec: null, speaker: '0', text: 'p' }],
        sentiment: [],
      },
    }));
    await hubA.insertTopic({
      session_time: '00:00:02',
      duration_sec: 1,
      topic_level: 2,
      summary: 'x',
    });
    expect(await hubA.updateTopic(B.topic.id, { summary: 'stolen' })).toBeNull();
    expect(await hubA.deleteTopic(B.topic.id)).toBe(false);
    await hubA.deleteTopics([B.topic.id, A.topic.id]);
    await hubA.saveDashboard({
      id: 'primary',
      config: DASHBOARD,
      createdBy: 'a',
      createdByTurnId: null,
    });
    expect(await hubA.deleteDashboard(B.dashboard)).toBe(false);
    expect(await hubA.deleteDashboard('primary')).toBe(true);

    expect(await allRows(b)).toEqual(before);

    // Reads on A return A's rows only.
    const bIds = new Set(
      Object.values(before)
        .flat()
        .map((r) => (r as { id?: string }).id),
    );
    const listed = await hubA.listEvents({ limit: 100, offset: 0 });
    expect(listed.events.some((e) => bIds.has(e.event_id))).toBe(false);
    expect(listed.total).toBe((await allRows(a)).session_events.length);
    expect((await hubA.exportEvents()).some((e) => bIds.has(e.event_id))).toBe(false);
    expect(await hubA.hasAutoGeneratedEvents()).toBe(false);
    expect((await hubA.listAudioSegments()).some((s) => bIds.has(s.id))).toBe(false);
    expect((await hubA.listTranscriptWords()).map((w) => w.word)).toEqual(['remapped']);
    expect((await hubA.listTranscriptEnrichment()).paragraphs.map((p) => p.text)).toEqual(['p']);
    expect((await hubA.listTopics()).some((t) => bIds.has(t.id))).toBe(false);
    expect((await hubA.listDashboards()).map((d) => d.id)).toEqual([A.dashboard]);
    expect((await hubA.leaseStatus()).holder_client_id).toBe('client-a2');
    expect(await hubA.getAudioSeamParts()).toEqual([{ duration_s: 5 }, { duration_s: 1 }]);
    await registry.closeAll();
  });
});
