import { memo, useMemo, useReducer } from 'react';
import { useSessionStatus } from '../../../api/hooks/useSessionStatus';
import { useGenerateTopics, useInsertTopic, useTopics } from '../../../api/hooks/useTopics';
import { useTranscriptWords } from '../../../api/hooks/useTranscriptWords';
import type { TranscriptWord } from '../../../api/types';
import { useGatedGenerate } from '../hooks/useGatedGenerate';
import { useTimelineSeek } from '../hooks/useTimelineSeek';
import { clickSortReducer } from '../utils/sortReducer';
import { FeedShell } from './FeedShell';
import { type ColumnDef, FeedTable } from './FeedTable';
import { GenerateToolbar } from './GenerateToolbar';
import { JUMP_COLUMN } from './JumpToTimeButton';
import { TopicsRow } from './TopicsRow';

type SortKey = 'session_time' | 'duration_sec' | 'topic_level' | 'summary';
const sortReducer = clickSortReducer<SortKey>;

// --- feed-row-seek, task 8.3 (spec "Topic jumps require an anchored
// transcript") ---
//
// Same predicate SHAPE as ai-v2-dashboards' `wordTimingsAreDegenerate`
// (packages/ai-runtime/src/aggregates.ts: `words.length > 0 && words.every(...)`),
// applied to `session_time` instead of the numeric `start_sec`/`end_sec`
// fields — Topics has no numeric timing to read, only the model-authored
// string. A transcript is "wholly anchorless" only when it has at least one
// word AND every word's `session_time` is empty.
//
// Empty-transcript semantics (deliberately decided, not copied blindly): an
// EMPTY transcript (no words at all) is NOT the same as a wholly-anchorless
// one, and the `length > 0` guard is what keeps them apart. A session with
// hand-entered topics and no transcript at all is a real case — nothing
// there was generated by copying (or inventing) transcript timestamps, so
// there is no invented-time hazard to guard against, and blocking those
// topics' jumps would only make well-formed, hand-typed times unusable for
// no safety benefit. Mirroring `wordTimingsAreDegenerate`'s own `length > 0`
// guard keeps the empty case OUT of "wholly anchorless", the same way an
// empty transcript is not "degenerate timing" there either.
export function transcriptWhollyAnchorless(words: TranscriptWord[]): boolean {
  return words.length > 0 && words.every((w) => w.session_time.trim() === '');
}

const COLUMNS: ColumnDef[] = [
  JUMP_COLUMN,
  {
    key: 'session_time',
    label: 'Session Time',
    sortKey: 'session_time',
    thClassName: 'text-left w-[6.5rem]',
  },
  {
    key: 'duration_sec',
    label: 'Duration (s)',
    sortKey: 'duration_sec',
    thClassName: 'text-left w-24',
  },
  { key: 'topic_level', label: 'Level', sortKey: 'topic_level', thClassName: 'text-left w-16' },
  { key: 'summary', label: 'Summary', sortKey: 'summary', thClassName: 'text-left min-w-56' },
];

interface Props {
  sessionId: string;
}

// Render-isolation memo (the WorkspaceStatic/TranscribeRow idiom). INVARIANT: every
// prop passed here must stay referentially stable across a SessionWorkspace render —
// today that is `sessionId` alone, memoized into `feedPanels` — or the playback-tick
// (~60/s) render isolation this buys reopens.
export const TopicsFeed = memo(function TopicsFeed({ sessionId }: Props) {
  const { data: topics, isLoading } = useTopics(sessionId);
  const generate = useGenerateTopics(sessionId);
  const insert = useInsertTopic(sessionId);
  // --- Feed row jump (feed-row-seek, design D5/D7): one hook call per feed,
  // its `unavailable`/`jump` handed to every row as a prop/stable callback.
  // Topics has no batch-edit mode (always editable, mirroring Transcript),
  // so the gate is just loaded-status + not-rolling. `useTimelineSeek` reads
  // the session-wide clip layout via `AudioClipsContext` — no local
  // `useEvents` call needed here at all (whole-branch audit fix wave,
  // finding C1/I3). `useTranscriptWords` is already fetched elsewhere when
  // the Transcript feed is mounted (ui-refresh: all tabs stay mounted, just
  // hidden) — React Query dedupes. ---
  const { data: status } = useSessionStatus(sessionId);
  const { data: words } = useTranscriptWords(sessionId);
  const { unavailable: jumpUnavailable, jump } = useTimelineSeek(sessionId, false);
  const jumpReasonId = 'v5-topics-feed-jump-reason';
  const fps = status?.frame_rate ?? null;
  // Task 8.3: computed once here from the session's transcript words, passed
  // down to every row like `fps` — never re-derived per row.
  //
  // Whole-branch audit fix wave, finding I1: `words` is `undefined` until
  // `useTranscriptWords` resolves (or forever, if the request fails) —
  // `transcriptWhollyAnchorless(words ?? [])` reads an empty array as "not
  // wholly anchorless" (its `length > 0` guard), so `transcriptAnchored`
  // used to fail OPEN during that window: every Topics row would render a
  // live jump control against model-invented times before the real
  // transcript state was known, permanently so if the request errors. `words
  // != null` treats "not yet known" as unanchored while preserving the
  // deliberate empty-transcript decision below `transcriptWhollyAnchorless`
  // — a LOADED empty transcript (hand-entered topics, no transcript at all)
  // still yields `transcriptAnchored === true`, because that case never went
  // through the model's invented-time path.
  // Quality fix wave, FIX 6c: `useMemo`'d so this doesn't re-scan every word
  // on every feed render (each status poll) — matches the "computed once"
  // framing of the comment above.
  const transcriptAnchored = useMemo(
    () => words != null && !transcriptWhollyAnchorless(words),
    [words],
  );
  // Latched on the first 503 (ui-refresh D9: honest capability gate — topic
  // generation has no external integration wired up on this deployment); see
  // `useGatedGenerate` for the full rationale.
  const { genError, genUnavailable, handleGenerate } = useGatedGenerate(generate.mutate);
  // Default direction is oldest-first across all three feeds (owner decision
  // 2026-08-06, PR#4 review) — the log reads top-down like a sheet.
  const [sort, dispatchSort] = useReducer(sortReducer, { key: 'session_time', dir: 'asc' });

  function handleInsert() {
    insert.mutate({});
  }

  const sortedTopics = useMemo(() => {
    if (!topics) return topics;
    const mul = sort.dir === 'asc' ? 1 : -1;
    return [...topics].sort((a, b) => {
      if (sort.key === 'session_time') return mul * (a.ordinal - b.ordinal);
      if (sort.key === 'duration_sec') return mul * (a.duration_sec - b.duration_sec);
      if (sort.key === 'topic_level') return mul * (a.topic_level - b.topic_level);
      if (sort.key === 'summary')
        return mul * a.summary.toLowerCase().localeCompare(b.summary.toLowerCase());
      return 0;
    });
  }, [topics, sort]);

  const topicCount = topics?.length ?? 0;

  // Shared aria-disabled latch toolbar — the a11y rationale (focusable
  // aria-disabled button + always-visible reason span) lives on GenerateToolbar.
  const genReasonId = 'v5-topics-gen-reason';
  const toolbar = (
    <GenerateToolbar
      genError={genError}
      genUnavailable={genUnavailable}
      onGenerate={handleGenerate}
      generatePending={generate.isPending}
      reasonId={genReasonId}
      reason={
        <>Topic generation isn&apos;t available on this server (no integration configured).</>
      }
      onInsert={handleInsert}
      insertPending={insert.isPending}
    />
  );

  return (
    <FeedShell
      countLabel={`${topicCount} ${topicCount === 1 ? 'Topic' : 'Topics'}`}
      headerId="v5-topics-feed-head"
      feedAriaLabel="Topics feed"
      toolbar={toolbar}
      toolbarAriaLabel="Topics feed tools"
      // `v5-topics-feed` retained as a chrome hook; the flex-column panel layout
      // (was `:global(.v5-topics-feed)` in FeedTable.module.css) rides along as
      // utilities: fill the tab panel on desktop, cap + internal-scroll on phones.
      modifier="v5-topics-feed flex flex-col flex-[1_1_0] min-h-0 overflow-hidden max-md:flex-[0_0_auto] max-md:max-h-[70dvh]"
      after={
        // The ONE shared reason node every row's jump control references
        // while unavailable (design D2 gate decision) — never one per row.
        jumpUnavailable && (
          <span id={jumpReasonId} className="sr-only">
            Jump is unavailable while timecode is rolling or session status is loading.
          </span>
        )
      }
    >
      <FeedTable
        columns={COLUMNS}
        isLoading={isLoading}
        isEmpty={!topics || topics.length === 0}
        emptyMessage={
          genUnavailable ? (
            <>
              Topic generation isn&apos;t available on this server — no topic-generation integration
              is configured. You can still add topics by hand with <strong>Insert</strong>, or
              design a dashboard from the <strong>Dashboards</strong> tab.
            </>
          ) : (
            <>
              No topics yet. Generate a transcript first, then click <strong>Auto Generate</strong>.
            </>
          )
        }
        sortKey={sort.key}
        sortDir={sort.dir}
        onSort={(k) => dispatchSort(k as SortKey)}
      >
        {sortedTopics?.map((t) => (
          <TopicsRow
            key={t.id}
            row={t}
            sessionId={sessionId}
            fps={fps}
            onJump={jump}
            jumpUnavailable={jumpUnavailable}
            jumpReasonId={jumpReasonId}
            transcriptAnchored={transcriptAnchored}
          />
        ))}
      </FeedTable>
    </FeedShell>
  );
});
