// persistence-package-extraction task 4.1 (design D4) — moved verbatim from
// server/src/routers/events.ts. Pure JSON predicate, no zod, no wire shape:
// two parties must agree on its meaning — the writer/reader in
// routers/events.ts and the SQL predicate in session-core's eventStore.ts
// (whose parity test — eventStore.test.ts — imports this from here). Moving
// it to domain lets both sides import one shared implementation instead of
// session depending on a server router module.

/** event-generate-hardening D1/gate ruling E3 — the route's JS auto-generated
 * predicate: `metadata_json` parses to an object whose `auto_generated` key
 * is JSON `true` (not `1`, not `"true"`, not missing, not malformed JSON).
 * The event store's SQL predicate (`EventStore.hasAutoGeneratedEvents`) is
 * pinned equal to this one by a dedicated parity unit test
 * (session-core's eventStore.test.ts) — two implementations, one tested
 * meaning. This is also the predicate the regenerate pre-spawn id snapshot
 * uses (D2/E3). Exported for the parity test; not otherwise used outside
 * routers/events.ts and that test. */
export function isAutoGeneratedMetadataJson(metadataJson: string): boolean {
  try {
    const meta = JSON.parse(metadataJson || '{}') as Record<string, unknown> | null;
    return meta !== null && typeof meta === 'object' && meta.auto_generated === true;
  } catch {
    return false;
  }
}
