import { describe, expect, it } from 'vitest';
import { isAutoGeneratedMetadataJson } from './eventMetadata';

// persistence-package-extraction task 4.1 (design D4) — moved from
// server/src/routers/events.metadataStrip.test.ts, which colocated this
// predicate's own unit coverage with the reserved-metadata-keys tests. The
// router's file still imports isAutoGeneratedMetadataJson from
// @autologger/domain and covers it via that import; this is the predicate's
// canonical direct coverage now that it lives here.
describe('isAutoGeneratedMetadataJson', () => {
  it('is true only for a JSON object with auto_generated: true (boolean)', () => {
    expect(isAutoGeneratedMetadataJson('{"auto_generated":true}')).toBe(true);
    expect(isAutoGeneratedMetadataJson('{"auto_generated":true,"auto_generate_run_id":"r1"}')).toBe(
      true,
    );
  });

  it('is false for false, non-boolean truthy values, missing key, and empty input', () => {
    expect(isAutoGeneratedMetadataJson('{"auto_generated":false}')).toBe(false);
    expect(isAutoGeneratedMetadataJson('{"auto_generated":1}')).toBe(false);
    expect(isAutoGeneratedMetadataJson('{"auto_generated":"true"}')).toBe(false);
    expect(isAutoGeneratedMetadataJson('{}')).toBe(false);
    expect(isAutoGeneratedMetadataJson('')).toBe(false);
  });

  it('is false for malformed JSON and non-object JSON values', () => {
    expect(isAutoGeneratedMetadataJson('{"auto_generated":true')).toBe(false);
    expect(isAutoGeneratedMetadataJson('[true]')).toBe(false);
    expect(isAutoGeneratedMetadataJson('null')).toBe(false);
  });
});
