// Tests for docker/scripts/compose-run.mjs (infisical-secrets task 3.2; design D1, H1-H12).
// Run: node --test docker/scripts/compose-run.test.mjs   (part of the root `npm test`)
//
// Black-box cases run the real wrapper as a child process against a local HTTPS stand-in for
// Infisical (127.0.0.1 only; CA and server certificate generated by openssl into a temp dir at
// test time, nothing committed) and a stub `docker` first on PATH that records argv, env and
// stdin. `compose ... config` is forwarded to the real docker so the resolved-config guards run
// for real. Unit cases import the wrapper's exported helpers.

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createHmac } from 'node:crypto';
import https from 'node:https';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { after, before, beforeEach, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  checkCaFile,
  checkCredFile,
  checkNodeVersion,
  checkResolved,
  checkSupabaseKeys,
  httpsJson,
  parseDomain,
  sanitizeMessage,
  splitStep,
  validateSecrets,
} from './compose-run.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const WRAPPER = join(ROOT, 'docker/scripts/compose-run.mjs');
const REAL_DOCKER = spawnSync('sh', ['-c', 'command -v docker'], { encoding: 'utf8' }).stdout.trim();
const SECRET = 'csec-SHOULD-NOT-LEAK';
const TOKEN = 'tok-SHOULD-NOT-LEAK';
const PGPW = '0123456789abcdef0123456789abcdef'; // a valid POSTGRES_PASSWORD (supabase-db D4)

let T; // temp dir
let server;
let port;
let otherServer; // presents a certificate from a different CA
let otherPort;
let handler; // (req, body, res) => void, set per test
let seen; // requests the stand-in received

function ossl(...args) {
  const r = spawnSync('openssl', args, { cwd: T, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`openssl ${args[0]} failed: ${r.stderr}`);
}

function makeCa(name) {
  ossl('req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '1', '-subj', `/CN=${name}`,
    '-keyout', `${name}.key`, '-out', `${name}.crt`);
}
function makeServerCert(ca, name) {
  ossl('req', '-newkey', 'rsa:2048', '-nodes', '-subj', '/CN=127.0.0.1', '-keyout', `${name}.key`, '-out', `${name}.csr`);
  writeFileSync(join(T, `${name}.ext`), 'subjectAltName=IP:127.0.0.1\n');
  ossl('x509', '-req', '-in', `${name}.csr`, '-CA', `${ca}.crt`, '-CAkey', `${ca}.key`, '-CAcreateserial',
    '-days', '1', '-extfile', `${name}.ext`, '-out', `${name}.crt`);
}

function listen(srv) {
  return new Promise((ok) => srv.listen(0, '127.0.0.1', () => ok(srv.address().port)));
}

function ok200(res, obj) {
  res.writeHead(200, { 'content-type': 'application/json' });
  res.end(JSON.stringify(obj));
}
function secret(k, v, extra = {}) {
  return { secretKey: k, secretValue: v, secretValueHidden: false, ...extra };
}
function standIn(secrets) {
  return (req, body, res) => {
    if (req.method === 'POST' && req.url.startsWith('/api/v1/auth/universal-auth/login')) {
      return ok200(res, { accessToken: TOKEN, expiresIn: 900 });
    }
    if (req.method === 'GET' && req.url.startsWith('/api/v4/secrets')) return ok200(res, { secrets, imports: [] });
    res.writeHead(404).end();
  };
}

// Stub docker: records argv (one line per call), env and stdin; forwards `config` to real docker.
function writeStubs() {
  mkdirSync(join(T, 'bin'), { recursive: true });
  writeFileSync(join(T, 'bin/docker'), `#!/bin/sh
d=${JSON.stringify(join(T, 'log'))}
mkdir -p "$d"
printf '%s\\n' "$*" >>"$d/argv"
for a in "$@"; do [ "$a" = config ] && exec ${JSON.stringify(REAL_DOCKER)} "$@"; done
env >"$d/env"
for a in "$@"; do [ "$a" = exec ] && cat >"$d/stdin"; done
if [ -f "$d/sleep" ]; then trap 'echo TERM >"$d/signal"; exit 143' TERM; sleep 5 & wait $!; fi
exit 0
`);
  chmodSync(join(T, 'bin/docker'), 0o755);
}

function writeCreds(env, over = {}) {
  const dir = join(T, 'cred');
  mkdirSync(dir, { recursive: true });
  const kv = {
    INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: 'cid-1',
    INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: SECRET,
    INFISICAL_PROJECT_ID: 'proj-1',
    INFISICAL_DOMAIN: `https://127.0.0.1:${port}`,
    INFISICAL_CA_FILE: join(T, 'ca.crt'),
    ...over,
  };
  const f = join(dir, `.env.infisical.${env}`);
  rmSync(f, { force: true });
  writeFileSync(f, Object.entries(kv).filter(([, v]) => v !== null).map(([k, v]) => `${k}=${v}`).join('\n') + '\n');
  chmodSync(f, 0o600);
  return f;
}

function log(name) {
  const f = join(T, 'log', name);
  return existsSync(f) ? readFileSync(f, 'utf8') : '';
}

// Run the wrapper like the Makefile does (clean env), plus the test hooks.
function run(args, { env = {}, input, onSpawn } = {}) {
  return new Promise((ok) => {
    const child = spawn(process.execPath, [WRAPPER, ...args], {
      cwd: ROOT,
      env: {
        PATH: '/usr/local/bin:/usr/bin:/bin',
        HOME: process.env.HOME,
        TERM: 'xterm',
        AUTOLOGGER_TEST: '1',
        AUTOLOGGER_TEST_PATH: join(T, 'bin'),
        AUTOLOGGER_TEST_CRED_DIR: join(T, 'cred'),
        API_TOKEN: 'ambient-weak',
        ...env,
      },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    if (input !== undefined) child.stdin.end(input); else child.stdin.end();
    onSpawn?.(child);
    child.on('close', (code, signal) => ok({ code, signal, out }));
  });
}

before(async () => {
  T = mkdtempSync(join(tmpdir(), 'compose-run-test-'));
  makeCa('ca');
  makeServerCert('ca', 'srv');
  makeCa('other');
  makeServerCert('other', 'osrv');
  chmodSync(join(T, 'ca.crt'), 0o644); // the host umask may leave it group-writable (H7 refuses that)
  writeStubs();
  const onReq = (req, res) => {
    let body = '';
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      seen.push({ method: req.method, url: req.url, headers: req.headers, body });
      handler(req, body, res);
    });
  };
  server = https.createServer({ key: readFileSync(join(T, 'srv.key')), cert: readFileSync(join(T, 'srv.crt')) }, onReq);
  port = await listen(server);
  otherServer = https.createServer({ key: readFileSync(join(T, 'osrv.key')), cert: readFileSync(join(T, 'osrv.crt')) }, onReq);
  otherPort = await listen(otherServer);
});
after(() => {
  server?.closeAllConnections();
  server?.close();
  otherServer?.closeAllConnections();
  otherServer?.close();
  if (T) rmSync(T, { recursive: true, force: true });
});
beforeEach(() => {
  seen = [];
  handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('DEV_PORT', '18787'), secret('POSTGRES_PASSWORD', PGPW)]);
  rmSync(join(T, 'log'), { recursive: true, force: true });
  rmSync(join(T, 'cred'), { recursive: true, force: true });
});

describe('credentials file (H7, D1 step 1)', () => {
  it('missing file names the template', async () => {
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /docker\/infisical-credentials\.example/);
  });
  it('http domain is refused before any request', async () => {
    writeCreds('dev', { INFISICAL_DOMAIN: `http://127.0.0.1:${port}` });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /https/);
    assert.equal(seen.length, 0);
  });
  it('group/world-readable file is refused, naming the mode', async () => {
    chmodSync(writeCreds('dev'), 0o644);
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /chmod 600|mode/);
  });
  it('a missing key is named', async () => {
    writeCreds('dev', { INFISICAL_PROJECT_ID: null });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /INFISICAL_PROJECT_ID/);
  });
  it('a missing CA file is named', async () => {
    writeCreds('dev', { INFISICAL_CA_FILE: join(T, 'nope.crt') });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /INFISICAL_CA_FILE/);
  });
  it('symlink, group-writable file, or another owner is refused', () => {
    const f = join(T, 'c1');
    writeFileSync(f, 'x\n');
    chmodSync(f, 0o600);
    const l = join(T, 'c1link');
    rmSync(l, { force: true });
    symlinkSync(f, l);
    assert.throws(() => checkCredFile(l), /symlink|regular file/);
    chmodSync(f, 0o620);
    assert.throws(() => checkCredFile(f), /chmod 600|mode/);
    chmodSync(f, 0o600);
    assert.throws(() => checkCredFile(f, process.getuid() + 1), /owned/);
    assert.doesNotThrow(() => checkCredFile(f));
  });
  it('a FIFO or oversized CA file is refused before reading', () => {
    const fifo = join(T, 'ca.fifo');
    rmSync(fifo, { force: true });
    spawnSync('mkfifo', [fifo]);
    assert.throws(() => checkCaFile(fifo), /regular file/);
    const big = join(T, 'big.crt');
    writeFileSync(big, 'x'.repeat(70 * 1024));
    chmodSync(big, 0o644);
    assert.throws(() => checkCaFile(big), /64 KiB/);
    const gw = join(T, 'gw.crt');
    writeFileSync(gw, 'x');
    chmodSync(gw, 0o664);
    assert.throws(() => checkCaFile(gw), /writable/);
  });
});

describe('TLS and HTTP (H2, H3)', () => {
  it('a certificate from another CA says to trust the Infisical CA, never to disable checks', async () => {
    writeCreds('dev', { INFISICAL_DOMAIN: `https://127.0.0.1:${otherPort}` });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /trust the Infisical CA/);
    assert.doesNotMatch(r.out, /http:\/\/|insecure|rejectUnauthorized|disable/i);
    assert.equal(seen.length, 0);
  });
  it('explicit rejectUnauthorized wins over NODE_TLS_REJECT_UNAUTHORIZED=0', async () => {
    const saved = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
    process.removeAllListeners('warning');
    try {
      await assert.rejects(
        httpsJson({ url: parseDomain(`https://127.0.0.1:${otherPort}`), ca: readFileSync(join(T, 'ca.crt')), method: 'GET', path: '/x' }),
        /trust the Infisical CA/,
      );
    } finally {
      if (saved === undefined) delete process.env.NODE_TLS_REJECT_UNAUTHORIZED; else process.env.NODE_TLS_REJECT_UNAUTHORIZED = saved;
    }
  });
  it('domain with a path, query, fragment or userinfo is refused', () => {
    for (const d of ['https://h/api', 'https://h/?x=1', 'https://h/#f', 'https://u:p@h/', 'http://h/', 'nonsense']) {
      assert.throws(() => parseDomain(d), /INFISICAL_DOMAIN/, d);
    }
    assert.equal(parseDomain('https://192.168.0.100').hostname, '192.168.0.100');
  });
  const ca = () => readFileSync(join(T, 'ca.crt'));
  const url = () => parseDomain(`https://127.0.0.1:${port}`);
  it('302 and 500 are refused with the status only', async () => {
    handler = (_q, _b, res) => { res.writeHead(302, { location: 'http://127.0.0.1:1/x' }).end('{"accessToken":"t"}'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /HTTP 302/);
    handler = (_q, _b, res) => { res.writeHead(500).end('{"message":"boom"}'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /HTTP 500: boom/);
  });
  it('a body over 1 MiB is refused', async () => {
    handler = (_q, _b, res) => { res.writeHead(200).end('x'.repeat(1024 * 1024 + 10)); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /too large/);
  });
  it('a server that never answers times out', async () => {
    handler = () => {};
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x', totalMs: 300 }), /timed out/);
  });
  it('a compressed response is refused', async () => {
    handler = (_q, _b, res) => { res.writeHead(200, { 'content-encoding': 'gzip' }).end('x'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /encoding/);
  });
});

describe('no secret in any output (H4)', () => {
  it('a truncated secrets body with a sentinel prints a fixed message only', async () => {
    writeCreds('dev');
    handler = (req, _b, res) => {
      if (req.method === 'POST') return ok200(res, { accessToken: TOKEN });
      res.writeHead(200).end('{"secrets":[{"secretKey":"API_TOKEN","secretValue":"SENTINEL-VALUE-123"');
    };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.doesNotMatch(r.out, /SENTINEL|API_TOKEN|tok-SHOULD/);
    assert.match(r.out, /not valid JSON/);
    assert.equal(log('argv'), '');
  });
  it('error messages are sanitized; a 422 issue array prints path/code only', () => {
    assert.equal(sanitizeMessage('bad\u001b[31mred\u0007'.padEnd(300, 'z')).length, 200);
    assert.doesNotMatch(sanitizeMessage('bad\u001b[31mred'), /\u001b/);
    assert.equal(sanitizeMessage([{ code: 'invalid_type', path: ['clientId'], received: 'SECRETISH' }]), 'clientId: invalid_type');
    assert.equal(sanitizeMessage({ x: 1 }), '');
  });
  it('login 401 prints only the status and message; no fetch', async () => {
    writeCreds('dev');
    handler = (_q, _b, res) => { res.writeHead(401, { 'content-type': 'application/json' }).end('{"message":"Invalid credentials"}'); };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /HTTP 401: Invalid credentials/);
    assert.equal(seen.length, 1);
    assert.doesNotMatch(r.out, new RegExp(SECRET));
  });
  it('login JSON without a string accessToken is refused; no fetch', async () => {
    writeCreds('dev');
    handler = (_q, _b, res) => ok200(res, { accessToken: 42 });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.equal(seen.length, 1);
  });
});

describe('secret validation (D1 step 4, H5, H6)', () => {
  const allowed = new Set(['API_TOKEN', 'GOOGLE_CLIENT_ID']);
  const refuse = (secrets, re) => assert.throws(() => validateSecrets({ secrets }, allowed), re);
  it('refuses names outside the allowed set, printing names not values', () => {
    const e = assert.throws(() => validateSecrets({ secrets: [secret('LD_PRELOAD', '/tmp/evil.so'), secret('DOCKER_HOST', 'tcp://x')] }, allowed), /LD_PRELOAD/);
    try { validateSecrets({ secrets: [secret('LD_PRELOAD', '/tmp/evil.so')] }, allowed); } catch (err) {
      assert.doesNotMatch(err.message, /evil/);
    }
    void e;
  });
  it('refuses non-string values, duplicates, NUL, hidden values, bad identifiers, empty or missing lists', () => {
    refuse([{ secretKey: 'API_TOKEN', secretValue: ['x', 'LD_PRELOAD=y'], secretValueHidden: false }], /API_TOKEN/);
    refuse([{ secretKey: 'API_TOKEN', secretValue: null, secretValueHidden: false }], /API_TOKEN/);
    refuse([secret('API_TOKEN', 'a'), secret('API_TOKEN', 'b')], /duplicate/);
    refuse([secret('API_TOKEN', 'a\u0000b')], /NUL/);
    refuse([secret('API_TOKEN', '<hidden-by-infisical>', { secretValueHidden: true })], /hidden/);
    refuse([{ secretKey: 'API_TOKEN', secretValue: 'v' }], /hidden/);
    refuse([secret('bad-name', 'v')], /1 more/);
    refuse([secret('API_TOKEN\n', 'v')], /1 more/);
    refuse([], /no secrets/);
    assert.throws(() => validateSecrets({}, allowed), /shape/);
    assert.throws(() => validateSecrets(null, allowed), /shape/);
  });
  it('refuses __proto__ and constructor without polluting anything', () => {
    refuse([secret('__proto__', 'x'), secret('constructor', 'y')], /__proto__.*constructor|constructor.*__proto__/);
    assert.equal({}.x, undefined);
  });
  it('returns a Map of the validated secrets', () => {
    const m = validateSecrets({ secrets: [secret('API_TOKEN', `a'b"c$d\`e\nf`)] }, allowed);
    assert.equal(m.get('API_TOKEN'), `a'b"c$d\`e\nf`);
  });
});

describe('start-up checks (H1, H10, H11)', () => {
  it('refuses NODE_* and proxy variables before any request', async () => {
    writeCreds('dev');
    for (const [k, v] of [['NODE_OPTIONS', '--no-warnings'], ['NODE_DEBUG', 'http'], ['NODE_TLS_REJECT_UNAUTHORIZED', '0'], ['HTTPS_PROXY', 'http://127.0.0.1:1']]) {
      const r = await run(['dev', 'compose version'], { env: { [k]: v } });
      assert.notEqual(r.code, 0, k);
      assert.match(r.out, new RegExp(k), k);
    }
    assert.equal(seen.length, 0);
  });
  it('refuses Node older than 22.12', () => {
    assert.throws(() => checkNodeVersion('22.11.9'), /22\.12/);
    assert.throws(() => checkNodeVersion('20.18.0'), /22\.12/);
    assert.doesNotThrow(() => checkNodeVersion('22.12.0'));
    assert.doesNotThrow(() => checkNodeVersion('24.21.0'));
  });
  it('step words with quotes, $ or ; are refused', () => {
    for (const w of [`compose up 'x'`, 'compose up $X', 'compose up;id', 'compose up `id`']) {
      assert.throws(() => splitStep(w), /step/, w);
    }
    assert.deepEqual(splitStep('compose logs -f --tail=200'), ['logs', '-f', '--tail=200']);
  });
  it('test hooks without AUTOLOGGER_TEST=1 are ignored', async () => {
    // prod: honored hooks would be refused for prod; ignored hooks fall through to the repo-root
    // credentials file, which never exists for prod on a dev host or in CI. (dev/stage would use
    // a real .env.infisical.<env> once the owner has one, and reach the real Infisical.)
    const r = await run(['prod', 'compose version'], { env: { AUTOLOGGER_TEST: '' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /\.env\.infisical\.prod is missing/);
    assert.doesNotMatch(r.out, /TEST HOOKS ACTIVE|test hooks/);
    assert.equal(seen.length, 0);
  });
  it('relative hook paths and hooks with prod are refused; a banner shows when active', async () => {
    writeCreds('dev');
    let r = await run(['dev', 'compose version'], { env: { AUTOLOGGER_TEST_PATH: 'bin' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /absolute/);
    writeCreds('prod');
    r = await run(['prod', 'prod-tags']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /prod/);
    assert.equal(seen.length, 0);
    r = await run(['dev', 'compose version']);
    assert.match(r.out, /TEST HOOKS ACTIVE/);
  });
});

describe('success path (D1 steps 5-6, H12)', () => {
  it('logs in once, fetches with the right query, and spawns docker with only the clean env', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', `a'b"c$d\`e\nf`), secret('DEV_PORT', '18787'), secret('POSTGRES_PASSWORD', PGPW)]);
    const r = await run(['dev', 'compose version']);
    assert.equal(r.code, 0, r.out);
    assert.equal(seen.length, 2);
    const [login, fetch] = seen;
    assert.equal(JSON.parse(login.body).clientSecret, SECRET);
    assert.equal(login.headers.authorization, undefined);
    assert.equal(fetch.headers.authorization, `Bearer ${TOKEN}`);
    assert.equal(fetch.body, '');
    const q = new URL(fetch.url, 'https://x').searchParams;
    assert.equal(q.get('projectId'), 'proj-1');
    assert.equal(q.get('environment'), 'dev');
    assert.equal(q.get('expandSecretReferences'), 'false');
    assert.equal(q.get('includeImports'), 'false');
    assert.equal(q.get('viewSecretValue'), 'true');
    const argv = log('argv');
    assert.match(argv, /--env-file \/dev\/null/);
    assert.doesNotMatch(argv, new RegExp(`${SECRET}|${TOKEN}`));
    const env = log('env');
    assert.doesNotMatch(env, /^(INFISICAL_|LD_|NODE_|API_TOKEN=)/m);
    assert.doesNotMatch(env, new RegExp(`${SECRET}|${TOKEN}`));
    assert.match(env, /^AUTOLOGGER_STACK=dev$/m);
    assert.match(env, /^TERM=xterm$/m);
    assert.ok(env.includes(`GOOGLE_CLIENT_ID=a'b"c$d\`e\nf`));
    const names = env.split('\n').filter((l) => /^[A-Za-z_][A-Za-z0-9_]*=/.test(l)).map((l) => l.split('=')[0]).sort();
    assert.deepEqual(names, ['AUTOLOGGER_STACK', 'DEV_PORT', 'GOOGLE_CLIENT_ID', 'HOME', 'PATH', 'POSTGRES_PASSWORD', 'PWD', 'TERM']);
    assert.match(env, new RegExp(`^POSTGRES_PASSWORD=${PGPW}$`, 'm'));
  });
  it('a multi-step call logs in once and runs the steps in order', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'compose restart app', 'compose restart app-gate', 'compose restart companion', 'compose restart companion-gate']);
    assert.equal(r.code, 0, r.out);
    assert.equal(seen.length, 2);
    assert.deepEqual(log('argv').trim().split('\n').map((l) => l.split(' ').at(-1)), ['app', 'app-gate', 'companion', 'companion-gate']);
  });
  it('an exec step gets the caller stdin', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'compose exec app sh'], { input: 'hello-stdin\n' });
    assert.equal(r.code, 0, r.out);
    assert.equal(log('stdin'), 'hello-stdin\n');
  });
  it('SIGTERM is forwarded to the running child and the wrapper exits with its status', async () => {
    writeCreds('dev');
    mkdirSync(join(T, 'log'), { recursive: true });
    writeFileSync(join(T, 'log/sleep'), '');
    const r = await run(['dev', 'compose up'], {
      onSpawn: (c) => {
        const t = setInterval(() => { if (existsSync(join(T, 'log/argv'))) { clearInterval(t); setTimeout(() => c.kill('SIGTERM'), 200); } }, 50);
      },
    });
    assert.equal(log('signal').trim(), 'TERM');
    assert.equal(r.code, 143);
  });
});

describe('guard steps (resolved, urls, prod-tags, reset; H8)', () => {
  it('resolved passes and urls prints the Infisical DEV_PORT', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'resolved', 'urls']);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /127\.0\.0\.1:18787/);
  });
  it('resolved refuses 8080, 80/443 in dev, and a non-numeric port', async () => {
    writeCreds('dev');
    for (const p of ['8080', '443', 'abc']) {
      handler = standIn([secret('DEV_PORT', p), secret('POSTGRES_PASSWORD', PGPW)]);
      const r = await run(['dev', 'resolved', 'compose up -d']);
      assert.notEqual(r.code, 0, p);
      assert.doesNotMatch(log('argv'), / up /, p);
    }
  });
  it('prod-tags refuses latest (checked with the stage-free prod allowlist, hooks refused for prod)', async () => {
    const { checkProdTags } = await import('./compose-run.mjs');
    assert.throws(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa'], ['API_TAG', 'latest']])), /API_TAG/);
    assert.throws(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa']])), /API_TAG/);
    assert.doesNotThrow(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa'], ['API_TAG', 'aaaaaaaaaaaa']])));
  });
  it('reset needs CONFIRM=yes before any request, and is refused for prod', async () => {
    writeCreds('dev');
    let r = await run(['dev', 'reset', 'compose down -v']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /CONFIRM=yes/);
    assert.equal(seen.length, 0);
    r = await run(['prod', 'reset', 'compose down -v'], { env: { CONFIRM: 'yes', AUTOLOGGER_TEST: '' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /reset.*prod|prod.*reset/);
    r = await run(['dev', 'reset', 'compose down -v'], { env: { CONFIRM: 'yes' } });
    assert.equal(r.code, 0, r.out);
    assert.match(log('argv'), /down -v/);
  });
  it('a failing guard stops before the destructive step', async () => {
    writeCreds('dev');
    handler = standIn([secret('DEV_PORT', '8080'), secret('POSTGRES_PASSWORD', PGPW)]);
    const r = await run(['dev', 'reset', 'resolved', 'compose down -v'], { env: { CONFIRM: 'yes' } });
    assert.notEqual(r.code, 0);
    assert.doesNotMatch(log('argv'), /down/);
  });
});

describe('Postgres password and prod run/exec (supabase-db D4, D6)', () => {
  const allowed = new Set(['POSTGRES_PASSWORD']);
  it('POSTGRES_PASSWORD must be at least 32 lowercase hex characters; the value is never printed', () => {
    for (const v of ['-e', 'a'.repeat(31), 'A'.repeat(32), `${PGPW}\n`, `${PGPW} `, 'g'.repeat(32)]) {
      let msg = '';
      try { validateSecrets({ secrets: [secret('POSTGRES_PASSWORD', v)] }, allowed); } catch (e) { msg = e.message; }
      assert.match(msg, /POSTGRES_PASSWORD.*bad-format/, JSON.stringify(v));
      if (v.length > 2) assert.ok(!msg.includes(v.trim()), JSON.stringify(v));
    }
    assert.equal(validateSecrets({ secrets: [secret('POSTGRES_PASSWORD', PGPW)] }, allowed).get('POSTGRES_PASSWORD'), PGPW);
  });
  it('a weak password from Infisical stops the target before docker runs', async () => {
    writeCreds('dev');
    handler = standIn([secret('DEV_PORT', '18787'), secret('POSTGRES_PASSWORD', '-e')]);
    const r = await run(['dev', 'compose up -d']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /POSTGRES_PASSWORD/);
    assert.equal(log('argv'), '');
  });
  it('prod refuses compose run and exec before any request', async () => {
    for (const step of ['compose run --rm migrate', 'compose exec db psql -U postgres', 'compose --profile tools run migrate']) {
      const r = await run(['prod', step], { env: { AUTOLOGGER_TEST: '' } });
      assert.notEqual(r.code, 0, step);
      assert.match(r.out, /prod.*(run|exec)|(run|exec).*prod/, step);
    }
    assert.equal(seen.length, 0);
    writeCreds('dev');
    const r = await run(['dev', 'compose run --rm migrate']);
    assert.equal(r.code, 0, r.out);
  });
  it('resolved refuses a config where the password value appears outside db and migrate', () => {
    const ok = { name: 'autologger', services: { router: { ports: [{ host_ip: '127.0.0.1', published: '8080' }] }, db: { environment: { POSTGRES_PASSWORD: PGPW } }, migrate: { environment: { PGPASSWORD: PGPW } } } };
    const secrets = new Map([['POSTGRES_PASSWORD', PGPW]]);
    assert.doesNotThrow(() => checkResolved('prod', ok, secrets));
    for (const leak of [{ labels: { x: `pw=${PGPW}` } }, { environment: { DATABASE_URL: `postgres://u:${PGPW}@db/x` } }, { build: { args: { P: PGPW } } }]) {
      const cfg = structuredClone(ok);
      cfg.services.api = leak;
      let msg = '';
      try { checkResolved('prod', cfg, secrets); } catch (e) { msg = e.message; }
      assert.match(msg, /POSTGRES_PASSWORD.*api|api.*POSTGRES_PASSWORD/, JSON.stringify(leak));
      assert.ok(!msg.includes(PGPW));
    }
  });
});

// supabase-services D4: formats, JWT consistency, per-secret confinement.
const b64u = (x) => Buffer.from(typeof x === 'string' ? x : JSON.stringify(x)).toString('base64url');
function jwt(secret, payload, header = { alg: 'HS256', typ: 'JWT' }) {
  const hp = `${b64u(header)}.${b64u(payload)}`;
  return `${hp}.${createHmac('sha256', secret).update(hp).digest('base64url')}`;
}
const JS = 'j'.repeat(43);
const now = Math.floor(Date.now() / 1000);
const ANON = jwt(JS, { role: 'anon', iss: 'supabase', iat: now, exp: now + 5 * 365 * 86400 });
const SVC = jwt(JS, { role: 'service_role', iss: 'supabase', iat: now, exp: now + 5 * 365 * 86400 });

describe('Supabase keys (supabase-services D4)', () => {
  const keys = ['POSTGRES_PASSWORD', 'SUPABASE_ROLES_PASSWORD', 'JWT_SECRET', 'SECRET_KEY_BASE', 'REALTIME_DB_ENC_KEY', 'ANON_KEY', 'SERVICE_ROLE_KEY', 'SUPABASE_PORT'];
  const allowed = new Set(keys);
  it('each format refuses a bad value without printing it', () => {
    const bad = {
      SUPABASE_ROLES_PASSWORD: 'A'.repeat(32), // uppercase is refused
      JWT_SECRET: 'short-secret-value',
      SECRET_KEY_BASE: 'k'.repeat(63),
      REALTIME_DB_ENC_KEY: 'k'.repeat(15),
      ANON_KEY: 'not-a-jwt-value',
      SERVICE_ROLE_KEY: 'a.b.c.d',
      SUPABASE_PORT: '80',
    };
    for (const [k, v] of Object.entries(bad)) {
      let msg = '';
      try { validateSecrets({ secrets: [secret(k, v)] }, allowed); } catch (e) { msg = e.message; }
      assert.match(msg, new RegExp(`${k}.*bad-format`), k);
      assert.ok(!msg.includes(v), k);
    }
    for (const v of ['99999', '1023', '8790x']) assert.throws(() => validateSecrets({ secrets: [secret('SUPABASE_PORT', v)] }, allowed), /bad-format/, v);
    const ok = validateSecrets({ secrets: [secret('SUPABASE_ROLES_PASSWORD', PGPW), secret('JWT_SECRET', JS), secret('SECRET_KEY_BASE', 'k'.repeat(64)), secret('REALTIME_DB_ENC_KEY', 'k'.repeat(16)), secret('ANON_KEY', ANON), secret('SERVICE_ROLE_KEY', SVC), secret('SUPABASE_PORT', '8790')] }, allowed);
    assert.equal(ok.size, 7);
  });
  it('the anon and service-role keys must verify against JWT_SECRET with the right roles', () => {
    const m = (o) => new Map(Object.entries({ JWT_SECRET: JS, ANON_KEY: ANON, SERVICE_ROLE_KEY: SVC, ...o }));
    assert.deepEqual(checkSupabaseKeys(m({})), []);
    const refused = (o, re) => {
      let msg = '';
      try { checkSupabaseKeys(m(o)); } catch (e) { msg = e.message; }
      assert.match(msg, re, JSON.stringify(Object.keys(o)));
      for (const v of Object.values(o)) if (v && v.length > 8) assert.ok(!msg.includes(v));
    };
    refused({ ANON_KEY: SVC, SERVICE_ROLE_KEY: ANON }, /ANON_KEY/);
    refused({ ANON_KEY: jwt('x'.repeat(43), { role: 'anon', exp: now + 999999 }) }, /ANON_KEY/);
    refused({ SERVICE_ROLE_KEY: jwt(JS, { role: 'service_role', exp: now - 10 }) }, /SERVICE_ROLE_KEY/);
    refused({ ANON_KEY: jwt(JS, { role: 'anon', exp: now + 999999 }, { alg: 'none' }) }, /ANON_KEY/);
    refused({ SERVICE_ROLE_KEY: ANON }, /SERVICE_ROLE_KEY/);
    refused({ ANON_KEY: undefined }, /ANON_KEY/);
    const warn = checkSupabaseKeys(m({ ANON_KEY: jwt(JS, { role: 'anon', exp: now + 30 * 86400 }) }));
    assert.equal(warn.length, 1);
    assert.match(warn[0], /ANON_KEY.*expires/);
    assert.deepEqual(checkSupabaseKeys(new Map([['POSTGRES_PASSWORD', PGPW]])), []);
  });
  it('resolved refuses a secret value outside its allowed services', () => {
    const base = { name: 'autologger', services: { router: { ports: [{ host_ip: '127.0.0.1', published: '8080' }] }, realtime: { environment: { ANON: ANON, DB: PGPW } }, storage: { environment: { A: ANON, S: SVC } }, 'supabase-gw': { environment: { A: ANON, S: SVC } } } };
    const secrets = new Map([['POSTGRES_PASSWORD', PGPW], ['ANON_KEY', ANON], ['SERVICE_ROLE_KEY', SVC]]);
    assert.doesNotThrow(() => checkResolved('prod', base, secrets));
    for (const [svc, k, v] of [['api', 'ANON_KEY', ANON], ['rest', 'POSTGRES_PASSWORD', PGPW], ['realtime', 'SERVICE_ROLE_KEY', SVC]]) {
      const cfg = structuredClone(base);
      cfg.services[svc] = { ...(cfg.services[svc] ?? {}), labels: { x: v } };
      let msg = '';
      try { checkResolved('prod', cfg, secrets); } catch (e) { msg = e.message; }
      assert.match(msg, new RegExp(`${k}.*${svc}`), `${k} in ${svc}`);
      assert.ok(!msg.includes(v));
    }
  });
});
