// Tests for docker/scripts/compose-run.mjs (openbao-secrets D1, D2; infisical-secrets H1-H12).
// Run: node --test docker/scripts/compose-run.test.mjs   (part of the root `npm test`)
//
// Black-box cases run the real wrapper as a child process against a local HTTPS stand-in for
// OpenBao's AppRole and KV v2 API (127.0.0.1 only; CA and server certificate generated by openssl into a temp dir at
// test time, nothing committed) and a stub `docker` first on PATH that records argv, env and
// stdin. `compose ... config` is forwarded to the real docker so the resolved-config guards run
// for real. Unit cases import the wrapper's exported helpers.

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { createHmac } from 'node:crypto';
import https from 'node:https';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { after, before, beforeEach, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  allowedNames,
  checkCaFile,
  checkCredFile,
  checkNodeVersion,
  checkResolved,
  httpsJson,
  parseAddr,
  parseKvPath,
  retiredKeyWarning,
  sanitizeMessage,
  splitStep,
  validateSecrets,
} from './compose-run.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const WRAPPER = join(ROOT, 'docker/scripts/compose-run.mjs');
const REAL_DOCKER = spawnSync('sh', ['-c', 'command -v docker'], { encoding: 'utf8' }).stdout.trim();
const SECRET = 'csec-SHOULD-NOT-LEAK';
const TOKEN = 'tok-SHOULD-NOT-LEAK';
const PGPW = '0123456789abcdef0123456789abcdef'; // a valid POSTGRES_PASSWORD (supabase-db D4)
// supabase-services: the compose files interpolate every Supabase key, so resolve needs them all
// (drop-unused-supabase-services D3: the four that remain).
const SB_JS = 'j'.repeat(43);
const sbSecrets = () => [secret('POSTGRES_PASSWORD', PGPW), secret('SUPABASE_ROLES_PASSWORD', 'f'.repeat(32)), secret('APP_DB_PASSWORD', 'e'.repeat(32)), secret('JWT_SECRET', SB_JS)];
// drop-unused-supabase-services D3: the retired keys as the old generator wrote them.
const retiredSecrets = () => [secret('ANON_KEY', 'aaa.bbb.ccc-anon-value'), secret('SERVICE_ROLE_KEY', 'aaa.bbb.ccc-service-value'), secret('SECRET_KEY_BASE', 's'.repeat(64)),
  secret('REALTIME_DB_ENC_KEY', 'r'.repeat(16)), secret('SUPABASE_PORT', '18790')];

let T; // temp dir
let server;
let port;
let otherServer; // presents a certificate from a different CA
let otherPort;
let handler; // (req, body, res) => void, set per test
let seen; // requests the stand-in received

function ossl(...args) {
  const r = spawnSync('openssl', args, { cwd: T, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`openssl ${args[0]} failed: ${r.stderr}`);
}

function makeCa(name) {
  ossl('req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '1', '-subj', `/CN=${name}`,
    '-keyout', `${name}.key`, '-out', `${name}.crt`);
}
function makeServerCert(ca, name) {
  ossl('req', '-newkey', 'rsa:2048', '-nodes', '-subj', '/CN=127.0.0.1', '-keyout', `${name}.key`, '-out', `${name}.csr`);
  writeFileSync(join(T, `${name}.ext`), 'subjectAltName=IP:127.0.0.1\n');
  ossl('x509', '-req', '-in', `${name}.csr`, '-CA', `${ca}.crt`, '-CAkey', `${ca}.key`, '-CAcreateserial',
    '-days', '1', '-extfile', `${name}.ext`, '-out', `${name}.crt`);
}

function listen(srv) {
  return new Promise((ok) => srv.listen(0, '127.0.0.1', () => ok(srv.address().port)));
}

function ok200(res, obj) {
  res.writeHead(200, { 'content-type': 'application/json' });
  res.end(JSON.stringify(obj));
}
// One secret as a [key, value] entry; kv() wraps entries as a KV v2 read response.
function secret(k, v) {
  return [k, v];
}
function kv(entries, metadata = {}) {
  return { request_id: 'r1', data: { data: Object.fromEntries(entries), metadata: { version: 3, deletion_time: '', destroyed: false, ...metadata } } };
}
// revoke: status for revoke-self (OpenBao answers 204 No Content).
function standIn(secrets, { revoke = 204 } = {}) {
  return (req, body, res) => {
    if (req.method === 'POST' && req.url === '/v1/auth/approle/login') {
      return ok200(res, { auth: { client_token: TOKEN, lease_duration: 300, renewable: true } });
    }
    if (req.method === 'GET' && /^\/v1\/kv\/data\/autologger\/(dev|stage)$/.test(req.url)) return ok200(res, kv(secrets));
    if (req.method === 'POST' && req.url === '/v1/auth/token/revoke-self') return res.writeHead(revoke).end();
    res.writeHead(404, { 'content-type': 'application/json' }).end('{"errors":[]}');
  };
}

// Stub docker: records argv (one line per call), env and stdin; forwards `config` to real docker.
function writeStubs() {
  mkdirSync(join(T, 'bin'), { recursive: true });
  writeFileSync(join(T, 'bin/docker'), `#!/bin/sh
d=${JSON.stringify(join(T, 'log'))}
mkdir -p "$d"
printf '%s\\n' "$*" >>"$d/argv"
for a in "$@"; do [ "$a" = config ] && exec ${JSON.stringify(REAL_DOCKER)} "$@"; done
env >"$d/env"
if [ -n "\${DOCKER_CONFIG-}" ]; then
  ls -A "$DOCKER_CONFIG" >"$d/dockerls"; stat -c %a "$DOCKER_CONFIG" >"$d/dockermode"; cat "$DOCKER_CONFIG/config.json" >"$d/dockercfg"
fi
for a in "$@"; do [ "$a" = exec ] && cat >"$d/stdin"; done
[ -f "$d/fail" ] && exit 3
if [ -f "$d/sleep" ]; then trap 'echo TERM >"$d/signal"; exit 143' TERM; sleep 5 & wait $!; fi
exit 0
`);
  chmodSync(join(T, 'bin/docker'), 0o755);
}

function writeCreds(env, over = {}) {
  const dir = join(T, 'cred');
  mkdirSync(dir, { recursive: true });
  const vals = {
    BAO_ADDR: `https://127.0.0.1:${port}`,
    BAO_CACERT: join(T, 'ca.crt'),
    BAO_ROLE_ID: 'role-1',
    BAO_SECRET_ID: SECRET,
    BAO_KV_PATH: `kv/autologger/${env}`,
    ...over,
  };
  const f = join(dir, `.env.openbao.${env}`);
  rmSync(f, { force: true });
  writeFileSync(f, Object.entries(vals).filter(([, v]) => v !== null).map(([k, v]) => `${k}=${v}`).join('\n') + '\n');
  chmodSync(f, 0o600);
  return f;
}

function log(name) {
  const f = join(T, 'log', name);
  return existsSync(f) ? readFileSync(f, 'utf8') : '';
}

// Run the wrapper like the Makefile does (clean env), plus the test hooks.
function run(args, { env = {}, input, onSpawn } = {}) {
  return new Promise((ok) => {
    const child = spawn(process.execPath, [WRAPPER, ...args], {
      cwd: ROOT,
      env: {
        PATH: '/usr/local/bin:/usr/bin:/bin',
        HOME: process.env.HOME,
        TERM: 'xterm',
        AUTOLOGGER_TEST: '1',
        AUTOLOGGER_TEST_PATH: join(T, 'bin'),
        AUTOLOGGER_TEST_CRED_DIR: join(T, 'cred'),
        API_TOKEN: 'ambient-weak',
        ...env,
      },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    if (input !== undefined) child.stdin.end(input); else child.stdin.end();
    onSpawn?.(child);
    child.on('close', (code, signal) => ok({ code, signal, out }));
  });
}

before(async () => {
  T = mkdtempSync(join(tmpdir(), 'compose-run-test-'));
  makeCa('ca');
  makeServerCert('ca', 'srv');
  makeCa('other');
  makeServerCert('other', 'osrv');
  chmodSync(join(T, 'ca.crt'), 0o644); // the host umask may leave it group-writable (H7 refuses that)
  writeStubs();
  const onReq = (req, res) => {
    let body = '';
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      seen.push({ method: req.method, url: req.url, headers: req.headers, body });
      handler(req, body, res);
    });
  };
  server = https.createServer({ key: readFileSync(join(T, 'srv.key')), cert: readFileSync(join(T, 'srv.crt')) }, onReq);
  port = await listen(server);
  otherServer = https.createServer({ key: readFileSync(join(T, 'osrv.key')), cert: readFileSync(join(T, 'osrv.crt')) }, onReq);
  otherPort = await listen(otherServer);
});
after(() => {
  server?.closeAllConnections();
  server?.close();
  otherServer?.closeAllConnections();
  otherServer?.close();
  if (T) rmSync(T, { recursive: true, force: true });
});
beforeEach(() => {
  seen = [];
  handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', '18787'), ...sbSecrets()]);
  rmSync(join(T, 'log'), { recursive: true, force: true });
  rmSync(join(T, 'cred'), { recursive: true, force: true });
});


// git run from a test must not inherit GIT_* from a calling git hook (GIT_DIR, GIT_INDEX_FILE, ...),
// or it reads or writes the repository that runs the hook instead of the one named with -C.
const gitEnv = () => Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith('GIT_')));
describe('credentials file (H7, D1 step 1)', () => {
  it('missing file names the template', async () => {
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /docker\/openbao-credentials\.example/);
  });
  it('http address is refused before any request', async () => {
    writeCreds('dev', { BAO_ADDR: `http://127.0.0.1:${port}` });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /https/);
    assert.equal(seen.length, 0);
  });
  it('group/world-readable file is refused, naming the mode', async () => {
    chmodSync(writeCreds('dev'), 0o644);
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /chmod 600|mode/);
  });
  it('a missing key is named', async () => {
    for (const k of ['BAO_ADDR', 'BAO_CACERT', 'BAO_ROLE_ID', 'BAO_SECRET_ID', 'BAO_KV_PATH']) {
      writeCreds('dev', { [k]: null });
      const r = await run(['dev', 'compose version']);
      assert.notEqual(r.code, 0, k);
      assert.match(r.out, new RegExp(k), k);
    }
    assert.equal(seen.length, 0);
  });
  it('a missing or relative CA file is named', async () => {
    for (const ca of [join(T, 'nope.crt'), 'ca.crt']) {
      writeCreds('dev', { BAO_CACERT: ca });
      const r = await run(['dev', 'compose version']);
      assert.notEqual(r.code, 0);
      assert.match(r.out, /BAO_CACERT/);
    }
  });
  it('a KV path for another stack, or with odd segments, is refused before any request (D1)', async () => {
    for (const p of ['kv/autologger/prod', 'kv/autologger/stage', 'kv', 'kv/../autologger/dev', 'kv/autologger/dev/', 'kv//dev', 'kv/auto logger/dev', 'kv/autologger/dev?x=1']) {
      writeCreds('dev', { BAO_KV_PATH: p });
      const r = await run(['dev', 'compose version']);
      assert.notEqual(r.code, 0, p);
      assert.match(r.out, /BAO_KV_PATH/, p);
    }
    assert.equal(seen.length, 0);
    assert.deepEqual(parseKvPath('kv/autologger/dev', 'dev'), { mount: 'kv', path: 'autologger/dev' });
    assert.deepEqual(parseKvPath('secret/stage', 'stage'), { mount: 'secret', path: 'stage' });
    assert.throws(() => parseKvPath('kv/autologger/dev', 'stage'), /end in \/stage/);
  });
  it('symlink, group-writable file, or another owner is refused', () => {
    const f = join(T, 'c1');
    writeFileSync(f, 'x\n');
    chmodSync(f, 0o600);
    const l = join(T, 'c1link');
    rmSync(l, { force: true });
    symlinkSync(f, l);
    assert.throws(() => checkCredFile(l), /symlink|regular file/);
    chmodSync(f, 0o620);
    assert.throws(() => checkCredFile(f), /chmod 600|mode/);
    chmodSync(f, 0o600);
    assert.throws(() => checkCredFile(f, process.getuid() + 1), /owned/);
    assert.doesNotThrow(() => checkCredFile(f));
  });
  it('a FIFO or oversized CA file is refused before reading', () => {
    const fifo = join(T, 'ca.fifo');
    rmSync(fifo, { force: true });
    spawnSync('mkfifo', [fifo]);
    assert.throws(() => checkCaFile(fifo), /regular file/);
    const big = join(T, 'big.crt');
    writeFileSync(big, 'x'.repeat(70 * 1024));
    chmodSync(big, 0o644);
    assert.throws(() => checkCaFile(big), /64 KiB/);
    const gw = join(T, 'gw.crt');
    writeFileSync(gw, 'x');
    chmodSync(gw, 0o664);
    assert.throws(() => checkCaFile(gw), /writable/);
  });
});

describe('TLS and HTTP (H2, H3)', () => {
  it('a certificate from another CA says to trust the OpenBao CA, never to disable checks', async () => {
    writeCreds('dev', { BAO_ADDR: `https://127.0.0.1:${otherPort}` });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /trust the OpenBao CA/);
    assert.doesNotMatch(r.out, /http:\/\/|insecure|rejectUnauthorized|disable/i);
    assert.equal(seen.length, 0);
  });
  it('explicit rejectUnauthorized wins over NODE_TLS_REJECT_UNAUTHORIZED=0', async () => {
    const saved = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
    process.removeAllListeners('warning');
    try {
      await assert.rejects(
        httpsJson({ url: parseAddr(`https://127.0.0.1:${otherPort}`), ca: readFileSync(join(T, 'ca.crt')), method: 'GET', path: '/x' }),
        /trust the OpenBao CA/,
      );
    } finally {
      if (saved === undefined) delete process.env.NODE_TLS_REJECT_UNAUTHORIZED; else process.env.NODE_TLS_REJECT_UNAUTHORIZED = saved;
    }
  });
  it('address with a path, query, fragment or userinfo is refused', () => {
    for (const d of ['https://h/api', 'https://h/v1', 'https://h/?x=1', 'https://h/#f', 'https://u:p@h/', 'http://h/', 'nonsense']) {
      assert.throws(() => parseAddr(d), /BAO_ADDR/, d);
    }
    assert.equal(parseAddr('https://10.88.0.10:8200').port, '8200');
  });
  const ca = () => readFileSync(join(T, 'ca.crt'));
  const url = () => parseAddr(`https://127.0.0.1:${port}`);
  it('302 and 500 are refused with the status only', async () => {
    handler = (_q, _b, res) => { res.writeHead(302, { location: 'http://127.0.0.1:1/x' }).end('{"auth":{"client_token":"t"}}'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /HTTP 302/);
    handler = (_q, _b, res) => { res.writeHead(500).end('{"errors":["boom"]}'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /HTTP 500: boom/);
  });
  it('204 is accepted only where an empty answer is expected', async () => {
    handler = (_q, _b, res) => { res.writeHead(204).end(); };
    assert.equal(await httpsJson({ url: url(), ca: ca(), method: 'POST', path: '/x', allowEmpty: true }), null);
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /HTTP 204/);
  });
  it('a body over 1 MiB is refused', async () => {
    handler = (_q, _b, res) => { res.writeHead(200).end('x'.repeat(1024 * 1024 + 10)); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /too large/);
  });
  it('a server that never answers times out', async () => {
    handler = () => {};
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x', totalMs: 300 }), /timed out/);
  });
  it('a compressed response is refused', async () => {
    handler = (_q, _b, res) => { res.writeHead(200, { 'content-encoding': 'gzip' }).end('x'); };
    await assert.rejects(httpsJson({ url: url(), ca: ca(), method: 'GET', path: '/x' }), /encoding/);
  });
});

describe('no secret in any output (H4)', () => {
  it('a truncated secrets body with a sentinel prints a fixed message only', async () => {
    writeCreds('dev');
    handler = (req, _b, res) => {
      if (req.method === 'POST') return req.url.endsWith('/login') ? ok200(res, { auth: { client_token: TOKEN } }) : res.writeHead(204).end();
      res.writeHead(200).end('{"data":{"data":{"API_TOKEN":"SENTINEL-VALUE-123"');
    };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.doesNotMatch(r.out, /SENTINEL|API_TOKEN|tok-SHOULD/);
    assert.match(r.out, /not valid JSON/);
    assert.equal(log('argv'), '');
  });
  it('error messages are sanitized; an errors array prints its strings only', () => {
    assert.equal(sanitizeMessage('bad\u001b[31mred\u0007'.padEnd(300, 'z')).length, 200);
    assert.doesNotMatch(sanitizeMessage('bad\u001b[31mred'), /\u001b/);
    assert.equal(sanitizeMessage(['permission denied', { value: 'SECRETISH' }, 'x\u001by']), 'permission denied; xy');
    assert.equal(sanitizeMessage({ x: 1 }), '');
  });
  it('login 400 prints only the status and errors; no read, nothing to revoke', async () => {
    writeCreds('dev');
    handler = (_q, _b, res) => { res.writeHead(400, { 'content-type': 'application/json' }).end('{"errors":["invalid role or secret ID"]}'); };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /HTTP 400: invalid role or secret ID/);
    assert.equal(seen.length, 1);
    assert.doesNotMatch(r.out, new RegExp(SECRET));
  });
  it('login JSON without a string client_token is refused; no read', async () => {
    writeCreds('dev');
    handler = (_q, _b, res) => ok200(res, { auth: { client_token: 42 } });
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.equal(seen.length, 1);
  });
});

describe('secret validation (D1 step 4, H5, H6)', () => {
  const allowed = new Set(['API_TOKEN', 'GOOGLE_CLIENT_ID']);
  const refuse = (entries, re) => assert.throws(() => validateSecrets(kv(entries), allowed), re);
  it('refuses names outside the allowed set, printing names not values', () => {
    assert.throws(() => validateSecrets(kv([secret('LD_PRELOAD', '/tmp/evil.so'), secret('DOCKER_HOST', 'tcp://x')]), allowed), /DOCKER_HOST LD_PRELOAD/);
    let msg = '';
    try { validateSecrets(kv([secret('LD_PRELOAD', '/tmp/evil.so')]), allowed); } catch (err) { msg = err.message; }
    assert.doesNotMatch(msg, /evil/);
  });
  it('no environment allows a BAO_* name', () => {
    for (const env of ['dev', 'stage', 'prod']) {
      const names = allowedNames(env);
      assert.deepEqual([...names].filter((k) => k.startsWith('BAO_')), [], env);
      assert.throws(() => validateSecrets(kv([secret('BAO_TOKEN', 'x')]), names), /BAO_TOKEN/, env);
    }
  });
  it('refuses non-string values, NUL, bad identifiers, an empty or missing data object', () => {
    refuse([['API_TOKEN', ['x', 'LD_PRELOAD=y']]], /API_TOKEN.*not-a-string/);
    refuse([['API_TOKEN', null]], /API_TOKEN/);
    refuse([['API_TOKEN', 42]], /API_TOKEN/);
    refuse([['API_TOKEN', { v: 'x' }]], /API_TOKEN/);
    refuse([secret('API_TOKEN', 'a\u0000b')], /NUL/);
    refuse([secret('bad-name', 'v')], /1 more/);
    refuse([secret('API_TOKEN\n', 'v')], /1 more/);
    refuse([], /no secrets/);
    assert.throws(() => validateSecrets({}, allowed), /shape/);
    assert.throws(() => validateSecrets(null, allowed), /shape/);
    assert.throws(() => validateSecrets({ data: { data: null, metadata: {} } }, allowed), /shape/);
    assert.throws(() => validateSecrets({ data: { data: ['API_TOKEN'] } }, allowed), /shape/);
  });
  it('refuses a deleted or destroyed current version (KV v2 field deletion_time)', () => {
    const past = new Date(Date.now() - 3600e3).toISOString();
    const future = new Date(Date.now() + 30 * 86400e3).toISOString();
    // A deletion_time at or before now is a soft-deleted version: undelete or rollback.
    assert.throws(() => validateSecrets(kv([secret('API_TOKEN', 'a')], { deletion_time: past }), allowed), /deleted.*bao kv undelete.*bao kv rollback/);
    // Unparseable non-empty deletion_time fails closed.
    assert.throws(() => validateSecrets(kv([secret('API_TOKEN', 'a')], { deletion_time: 'not-a-time' }), allowed), /deleted/);
    // The shape OpenBao gives a soft-deleted current version: data.data null, metadata kept.
    const gone = { data: { data: null, metadata: { version: 4, deletion_time: past, destroyed: false } } };
    assert.throws(() => validateSecrets(gone, allowed), /deleted.*bao kv undelete/);
    // Destroyed: only rollback can help (undelete cannot restore destroyed data).
    for (const v of [kv([secret('API_TOKEN', 'a')], { destroyed: true }), { data: { data: null, metadata: { version: 4, deletion_time: '', destroyed: true } } }]) {
      let msg = '';
      try { validateSecrets(v, allowed); } catch (e) { msg = e.message; }
      assert.match(msg, /destroyed.*bao kv rollback/);
      assert.doesNotMatch(msg, /undelete/);
    }
    // A live version: empty deletion_time, or a FUTURE one (delete_version_after), destroyed false.
    assert.doesNotThrow(() => validateSecrets(kv([secret('API_TOKEN', 'a')]), allowed));
    assert.doesNotThrow(() => validateSecrets(kv([secret('API_TOKEN', 'a')], { deletion_time: future }), allowed));
  });
  it('refuses __proto__ and constructor without polluting anything', () => {
    const parsed = JSON.parse('{"data":{"data":{"__proto__":"x","constructor":"y"},"metadata":{"version":1}}}');
    assert.throws(() => validateSecrets(parsed, allowed), /__proto__.*constructor|constructor.*__proto__/);
    assert.equal({}.x, undefined);
  });
  it('returns a Map of the validated secrets', () => {
    const m = validateSecrets(kv([secret('API_TOKEN', `a'b"c$d\`e\nf`)]), allowed);
    assert.equal(m.get('API_TOKEN'), `a'b"c$d\`e\nf`);
  });
});

describe('start-up checks (H1, H10, H11)', () => {
  it('refuses NODE_* and proxy variables before any request', async () => {
    writeCreds('dev');
    for (const [k, v] of [['NODE_OPTIONS', '--no-warnings'], ['NODE_DEBUG', 'http'], ['NODE_TLS_REJECT_UNAUTHORIZED', '0'], ['HTTPS_PROXY', 'http://127.0.0.1:1']]) {
      const r = await run(['dev', 'compose version'], { env: { [k]: v } });
      assert.notEqual(r.code, 0, k);
      assert.match(r.out, new RegExp(k), k);
    }
    assert.equal(seen.length, 0);
  });
  it('refuses Node older than 22.12', () => {
    assert.throws(() => checkNodeVersion('22.11.9'), /22\.12/);
    assert.throws(() => checkNodeVersion('20.18.0'), /22\.12/);
    assert.doesNotThrow(() => checkNodeVersion('22.12.0'));
    assert.doesNotThrow(() => checkNodeVersion('24.21.0'));
  });
  it('step words with quotes, $ or ; are refused', () => {
    for (const w of [`compose up 'x'`, 'compose up $X', 'compose up;id', 'compose up `id`']) {
      assert.throws(() => splitStep(w), /step/, w);
    }
    assert.deepEqual(splitStep('compose logs -f --tail=200'), ['logs', '-f', '--tail=200']);
  });
  it('test hooks without AUTOLOGGER_TEST=1 are ignored', async () => {
    // prod: honored hooks would be refused for prod; ignored hooks fall through to the repo-root
    // credentials file, which never exists for prod on a dev host or in CI. (dev/stage would use
    // a real .env.openbao.<env> once the owner has one, and reach the real OpenBao.)
    const r = await run(['prod', 'compose version'], { env: { AUTOLOGGER_TEST: '' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /\.env\.openbao\.prod is missing/);
    assert.doesNotMatch(r.out, /TEST HOOKS ACTIVE|test hooks/);
    assert.equal(seen.length, 0);
  });
  it('relative hook paths and hooks with prod are refused; a banner shows when active', async () => {
    writeCreds('dev');
    let r = await run(['dev', 'compose version'], { env: { AUTOLOGGER_TEST_PATH: 'bin' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /absolute/);
    writeCreds('prod');
    r = await run(['prod', 'prod-tags']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /prod/);
    assert.equal(seen.length, 0);
    r = await run(['dev', 'compose version']);
    assert.match(r.out, /TEST HOOKS ACTIVE/);
  });
});

describe('success path (D1 steps 5-6, H12)', () => {
  it('logs in once, reads the KV path, revokes the token, and spawns docker with only the clean env', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', `a'b"c$d\`e\nf`), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', '18787'), ...sbSecrets(), ...retiredSecrets()]);
    const r = await run(['dev', 'compose version']);
    assert.equal(r.code, 0, r.out);
    assert.deepEqual(seen.map((q) => `${q.method} ${q.url}`), ['POST /v1/auth/approle/login', 'GET /v1/kv/data/autologger/dev', 'POST /v1/auth/token/revoke-self']);
    const [login, fetch, revoke] = seen;
    assert.deepEqual(JSON.parse(login.body), { role_id: 'role-1', secret_id: SECRET });
    assert.equal(login.headers['x-vault-token'], undefined);
    assert.equal(fetch.headers['x-vault-token'], TOKEN);
    assert.equal(fetch.headers.authorization, undefined);
    assert.equal(fetch.body, '');
    assert.equal(revoke.headers['x-vault-token'], TOKEN);
    // drop-unused-supabase-services D3: the fixture still holds the retired keys; one warning names them.
    assert.equal(r.out.match(/warning/g)?.length, 1, r.out);
    assert.match(r.out, /^compose-run: warning: the OpenBao dev secret holds retired keys ANON_KEY, REALTIME_DB_ENC_KEY, SECRET_KEY_BASE, SERVICE_ROLE_KEY, SUPABASE_PORT; /m);
    for (const [k, v] of retiredSecrets()) if (v.length > 5) assert.ok(!r.out.includes(v), k);
    const argv = log('argv');
    assert.match(argv, /--env-file \/dev\/null/);
    assert.doesNotMatch(argv, new RegExp(`${SECRET}|${TOKEN}`));
    const env = log('env');
    assert.doesNotMatch(env, /^(BAO_|VAULT_|LD_|NODE_|API_TOKEN=)/m);
    assert.doesNotMatch(env, new RegExp(`${SECRET}|${TOKEN}`));
    assert.match(env, /^AUTOLOGGER_STACK=dev$/m);
    assert.match(env, /^TERM=xterm$/m);
    assert.ok(env.includes(`GOOGLE_CLIENT_ID=a'b"c$d\`e\nf`));
    const names = env.split('\n').filter((l) => /^[A-Za-z_][A-Za-z0-9_]*=/.test(l)).map((l) => l.split('=')[0]).sort();
    assert.deepEqual(names, ['APP_DB_PASSWORD', 'AUTOLOGGER_STACK', 'BOOTSTRAP_OWNER_EMAIL', 'DEV_PORT', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'HOME', 'JWT_SECRET', 'PATH', 'POSTGRES_PASSWORD', 'PWD', 'SUPABASE_ROLES_PASSWORD', 'TERM']);
    assert.match(env, new RegExp(`^POSTGRES_PASSWORD=${PGPW}$`, 'm'));
  });
  it('a failed revoke only warns; the token expires with its TTL', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', '18787'), ...sbSecrets()], { revoke: 403 });
    const r = await run(['dev', 'compose version']);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /warning: could not revoke the OpenBao token \(OpenBao answered HTTP 403\)/);
    assert.doesNotMatch(r.out, new RegExp(TOKEN));
  });
  it('a refused read still revokes the token, and prints the status only', async () => {
    writeCreds('dev');
    handler = (req, _b, res) => {
      if (req.url === '/v1/auth/approle/login') return ok200(res, { auth: { client_token: TOKEN } });
      if (req.url === '/v1/auth/token/revoke-self') return res.writeHead(204).end();
      return res.writeHead(403, { 'content-type': 'application/json' }).end('{"errors":["1 error occurred:\\n\\t* permission denied\\n\\n"]}');
    };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /HTTP 403: 1 error occurred:\t\* permission denied|HTTP 403: 1 error occurred:.*permission denied/);
    assert.deepEqual(seen.map((q) => q.url), ['/v1/auth/approle/login', '/v1/kv/data/autologger/dev', '/v1/auth/token/revoke-self']);
    assert.equal(log('argv'), '');
  });
  it('a soft-deleted current version (404 with metadata) is refused naming undelete, after revoking', async () => {
    writeCreds('dev');
    handler = (req, _b, res) => {
      if (req.url === '/v1/auth/approle/login') return ok200(res, { auth: { client_token: TOKEN } });
      if (req.url === '/v1/auth/token/revoke-self') return res.writeHead(204).end();
      return res.writeHead(404, { 'content-type': 'application/json' })
        .end(JSON.stringify({ errors: [], data: { data: null, metadata: { version: 4, deletion_time: new Date(Date.now() - 3600e3).toISOString(), destroyed: false } } }));
    };
    const r = await run(['dev', 'compose version']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /is deleted/);
    assert.match(r.out, /bao kv undelete/);
    assert.deepEqual(seen.map((q) => q.url), ['/v1/auth/approle/login', '/v1/kv/data/autologger/dev', '/v1/auth/token/revoke-self']);
    assert.equal(log('argv'), '');
  });
  it('a multi-step call logs in once and runs the steps in order', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'compose restart app', 'compose restart app-gate', 'compose restart companion', 'compose restart companion-gate']);
    assert.equal(r.code, 0, r.out);
    assert.equal(seen.length, 3);
    assert.deepEqual(log('argv').trim().split('\n').map((l) => l.split(' ').at(-1)), ['app', 'app-gate', 'companion', 'companion-gate']);
  });
  it('an exec step gets the caller stdin', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'compose exec app sh'], { input: 'hello-stdin\n' });
    assert.equal(r.code, 0, r.out);
    assert.equal(log('stdin'), 'hello-stdin\n');
  });
  it('SIGTERM is forwarded to the running child and the wrapper exits with its status', async () => {
    writeCreds('dev');
    mkdirSync(join(T, 'log'), { recursive: true });
    writeFileSync(join(T, 'log/sleep'), '');
    const r = await run(['dev', 'compose up'], {
      onSpawn: (c) => {
        const t = setInterval(() => { if (existsSync(join(T, 'log/argv'))) { clearInterval(t); setTimeout(() => c.kill('SIGTERM'), 200); } }, 50);
      },
    });
    assert.equal(log('signal').trim(), 'TERM');
    assert.equal(r.code, 143);
  });
});

describe('guard steps (resolved, urls, prod-tags, reset; H8)', () => {
  it('resolved passes and urls prints the OpenBao DEV_PORT', async () => {
    writeCreds('dev');
    const r = await run(['dev', 'resolved', 'urls']);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /127\.0\.0\.1:18787/);
    assert.doesNotMatch(r.out, /Supabase:/); // drop-unused-supabase-services D3
  });
  it('resolved refuses 8080, 80/443 in dev, and a non-numeric port', async () => {
    writeCreds('dev');
    for (const p of ['8080', '443', 'abc']) {
      handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', p), ...sbSecrets()]);
      const r = await run(['dev', 'resolved', 'compose up -d']);
      assert.notEqual(r.code, 0, p);
      assert.doesNotMatch(log('argv'), / up /, p);
    }
  });
  it('prod-tags refuses latest (checked with the stage-free prod allowlist, hooks refused for prod)', async () => {
    const { checkProdTags } = await import('./compose-run.mjs');
    assert.throws(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa'], ['API_TAG', 'latest']])), /API_TAG/);
    assert.throws(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa']])), /API_TAG/);
    assert.doesNotThrow(() => checkProdTags(new Map([['WEB_TAG', 'aaaaaaaaaaaa'], ['API_TAG', 'aaaaaaaaaaaa']])));
  });
  it('reset needs CONFIRM=yes before any request, and is refused for prod', async () => {
    writeCreds('dev');
    let r = await run(['dev', 'reset', 'compose down -v']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /CONFIRM=yes/);
    assert.equal(seen.length, 0);
    r = await run(['prod', 'reset', 'compose down -v'], { env: { CONFIRM: 'yes', AUTOLOGGER_TEST: '' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /reset.*prod|prod.*reset/);
    r = await run(['dev', 'reset', 'compose down -v'], { env: { CONFIRM: 'yes' } });
    assert.equal(r.code, 0, r.out);
    assert.match(log('argv'), /down -v/);
  });
  it('a failing guard stops before the destructive step', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', '8080'), ...sbSecrets()]);
    const r = await run(['dev', 'reset', 'resolved', 'compose down -v'], { env: { CONFIRM: 'yes' } });
    assert.notEqual(r.code, 0);
    assert.doesNotMatch(log('argv'), /down/);
  });
});

describe('Postgres password and prod run/exec (supabase-db D4, D6)', () => {
  const allowed = new Set(['POSTGRES_PASSWORD']);
  it('POSTGRES_PASSWORD must be at least 32 lowercase hex characters; the value is never printed', () => {
    for (const v of ['-e', 'a'.repeat(31), 'A'.repeat(32), `${PGPW}\n`, `${PGPW} `, 'g'.repeat(32)]) {
      let msg = '';
      try { validateSecrets(kv([secret('POSTGRES_PASSWORD', v)]), allowed); } catch (e) { msg = e.message; }
      assert.match(msg, /POSTGRES_PASSWORD.*bad-format/, JSON.stringify(v));
      if (v.length > 2) assert.ok(!msg.includes(v.trim()), JSON.stringify(v));
    }
    assert.equal(validateSecrets(kv([secret('POSTGRES_PASSWORD', PGPW)]), allowed).get('POSTGRES_PASSWORD'), PGPW);
  });
  it('a weak password from OpenBao stops the target before docker runs', async () => {
    writeCreds('dev');
    handler = standIn([secret('DEV_PORT', '18787'), secret('POSTGRES_PASSWORD', '-e')]);
    const r = await run(['dev', 'compose up -d']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /POSTGRES_PASSWORD/);
    assert.equal(log('argv'), '');
  });
  it('prod refuses compose run and exec before any request', async () => {
    for (const step of ['compose run --rm migrate', 'compose exec db psql -U postgres', 'compose --profile tools run migrate']) {
      const r = await run(['prod', step], { env: { AUTOLOGGER_TEST: '' } });
      assert.notEqual(r.code, 0, step);
      assert.match(r.out, /prod.*(run|exec)|(run|exec).*prod/, step);
    }
    assert.equal(seen.length, 0);
    writeCreds('dev');
    const r = await run(['dev', 'compose run --rm migrate']);
    assert.equal(r.code, 0, r.out);
  });
  it('resolved refuses a config where the password value appears outside db and migrate', () => {
    const ok = { name: 'autologger', services: { router: { ports: [{ host_ip: '127.0.0.1', published: '8080' }] }, db: { environment: { POSTGRES_PASSWORD: PGPW } }, migrate: { environment: { PGPASSWORD: PGPW } } } };
    const secrets = new Map([['POSTGRES_PASSWORD', PGPW]]);
    assert.doesNotThrow(() => checkResolved('prod', ok, secrets));
    for (const leak of [{ labels: { x: `pw=${PGPW}` } }, { environment: { DATABASE_URL: `postgres://u:${PGPW}@db/x` } }, { build: { args: { P: PGPW } } }]) {
      const cfg = structuredClone(ok);
      cfg.services.api = leak;
      let msg = '';
      try { checkResolved('prod', cfg, secrets); } catch (e) { msg = e.message; }
      assert.match(msg, /POSTGRES_PASSWORD.*api|api.*POSTGRES_PASSWORD/, JSON.stringify(leak));
      assert.ok(!msg.includes(PGPW));
    }
  });
});

// catalog-pg-schema D4-D5: the app's database password, its format and its per-stack services.
describe('APP_DB_PASSWORD (catalog-pg-schema D4, D5)', () => {
  const APW = 'abcdef0123456789abcdef0123456789';
  it('must be at least 32 lowercase hex characters; the value is never printed', () => {
    for (const v of ['-e', 'A'.repeat(32), 'a'.repeat(31), `${APW}\n${APW}`]) {
      let msg = '';
      try { validateSecrets(kv([secret('APP_DB_PASSWORD', v)]), new Set(['APP_DB_PASSWORD'])); } catch (e) { msg = e.message; }
      assert.match(msg, /APP_DB_PASSWORD.*bad-format/, JSON.stringify(v));
      if (v.length > 2) assert.ok(!msg.includes(v));
    }
  });
  it('is an allowed name in every environment', () => {
    for (const env of ['dev', 'stage', 'prod']) {
      assert.equal(validateSecrets(kv([secret('APP_DB_PASSWORD', APW)]), allowedNames(env)).get('APP_DB_PASSWORD'), APW, env);
    }
  });
  const base = (env) => {
    const ports = env === 'dev'
      ? { app: { ports: [{ host_ip: '127.0.0.1', published: '8787' }] }, companion: { ports: [{ host_ip: '127.0.0.1', published: '8000' }] } }
      : { router: { ports: [{ host_ip: '127.0.0.1', published: env === 'prod' ? '8080' : '8788' }] } };
    return { name: { dev: 'autologger-dev', stage: 'autologger-stage', prod: 'autologger' }[env], services: { ...ports, migrate: { environment: { APP_DB_PASSWORD: APW } } } };
  };
  const secrets = new Map([['APP_DB_PASSWORD', APW]]);
  const refusal = (env, svc) => {
    const cfg = base(env);
    cfg.services[svc] = { ...(cfg.services[svc] ?? {}), environment: { PGPASSWORD: APW } };
    try { checkResolved(env, cfg, secrets); return ''; } catch (e) { return e.message; }
  };
  it('is allowed in the stack app service and migrate only', () => {
    assert.equal(refusal('dev', 'app'), '');
    assert.equal(refusal('stage', 'api'), '');
    assert.equal(refusal('prod', 'api'), '');
  });
  it('is refused in rest, in a dev api or a prod app, without printing it', () => {
    for (const [env, svc] of [['dev', 'rest'], ['prod', 'rest'], ['dev', 'api'], ['prod', 'app'], ['dev', 'companion']]) {
      const msg = refusal(env, svc);
      assert.match(msg, new RegExp(`APP_DB_PASSWORD value appears in ${svc}`), `${env} ${svc}`);
      assert.ok(!msg.includes(APW));
    }
  });
});

// supabase-services D4: formats and per-secret confinement (drop-unused-supabase-services D3: the
// anon/service-role JWT check is gone with the services that used the keys).
const JS = 'j'.repeat(43);
const RPW = 'f'.repeat(32);

describe('Supabase keys (supabase-services D4)', () => {
  const keys = ['POSTGRES_PASSWORD', 'SUPABASE_ROLES_PASSWORD', 'JWT_SECRET'];
  const allowed = new Set(keys);
  it('each format refuses a bad value without printing it', () => {
    // drop-unused-supabase-services D3: the retired keys have no format any more (see below).
    const bad = {
      SUPABASE_ROLES_PASSWORD: 'A'.repeat(32), // uppercase is refused
      JWT_SECRET: 'short-secret-value',
    };
    for (const [k, v] of Object.entries(bad)) {
      let msg = '';
      try { validateSecrets(kv([secret(k, v)]), allowed); } catch (e) { msg = e.message; }
      assert.match(msg, new RegExp(`${k}.*bad-format`), k);
      assert.ok(!msg.includes(v), k);
    }
    const ok = validateSecrets(kv([secret('SUPABASE_ROLES_PASSWORD', PGPW), secret('JWT_SECRET', JS)]), allowed);
    assert.equal(ok.size, 2);
  });
  it('an ANON_KEY signed with another secret is not refused (drop-unused-supabase-services D3)', async () => {
    writeCreds('dev');
    const p = (o) => Buffer.from(JSON.stringify(o)).toString('base64url');
    const hp = `${p({ alg: 'HS256', typ: 'JWT' })}.${p({ role: 'anon', exp: Math.floor(Date.now() / 1000) + 86400 })}`;
    const foreign = `${hp}.${createHmac('sha256', 'x'.repeat(43)).update(hp).digest('base64url')}`;
    handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('DEV_PORT', '18787'), ...sbSecrets(), secret('ANON_KEY', foreign)]);
    const r = await run(['dev', 'compose version']);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /retired keys ANON_KEY;/);
    assert.ok(!r.out.includes(foreign));
  });
  it('resolved refuses a secret value outside its allowed services', () => {
    // drop-unused-supabase-services D3: db, migrate and auth hold the Supabase keys; rest, realtime
    // and storage are fixture services that no longer exist.
    const base = { name: 'autologger', services: { router: { ports: [{ host_ip: '127.0.0.1', published: '8080' }] }, db: { environment: { P: PGPW, R: RPW } }, migrate: { environment: { P: PGPW } }, auth: { environment: { R: RPW, J: JS } } } };
    const secrets = new Map([['POSTGRES_PASSWORD', PGPW], ['SUPABASE_ROLES_PASSWORD', RPW], ['JWT_SECRET', JS]]);
    assert.doesNotThrow(() => checkResolved('prod', base, secrets));
    for (const [svc, k, v] of [['api', 'JWT_SECRET', JS], ['rest', 'JWT_SECRET', JS], ['storage', 'JWT_SECRET', JS], ['realtime', 'POSTGRES_PASSWORD', PGPW], ['rest', 'SUPABASE_ROLES_PASSWORD', RPW], ['auth', 'POSTGRES_PASSWORD', PGPW]]) {
      const cfg = structuredClone(base);
      cfg.services[svc] = { ...(cfg.services[svc] ?? {}), labels: { x: v } };
      let msg = '';
      try { checkResolved('prod', cfg, secrets); } catch (e) { msg = e.message; }
      assert.match(msg, new RegExp(`${k}.*${svc}`), `${k} in ${svc}`);
      assert.ok(!msg.includes(v));
    }
  });
});

// drop-unused-supabase-services D3: the five retired keys are accepted, never format-checked, never
// passed to compose, and named (never their values) in one warning.
describe('retired Supabase keys (drop-unused-supabase-services D3)', () => {
  const RETIRED = { ANON_KEY: 'not-a-jwt', SECRET_KEY_BASE: 'k'.repeat(10), REALTIME_DB_ENC_KEY: 'k'.repeat(40), SERVICE_ROLE_KEY: 'a.b.c.d', SUPABASE_PORT: '80' };
  it('are accepted in every environment, whatever their format', () => {
    for (const env of ['dev', 'stage', 'prod']) {
      const got = validateSecrets(kv(Object.entries(RETIRED)), allowedNames(env));
      assert.equal(got.size, 5, env);
    }
  });
  it('the warning names exactly the retired keys present, sorted, and no value', () => {
    assert.equal(retiredKeyWarning(new Map([['POSTGRES_PASSWORD', PGPW], ['JWT_SECRET', JS]]), 'dev'), undefined);
    const all = retiredKeyWarning(new Map([['POSTGRES_PASSWORD', PGPW], ...Object.entries(RETIRED)]), 'stage');
    assert.equal(all, 'compose-run: warning: the OpenBao stage secret holds retired keys ANON_KEY, REALTIME_DB_ENC_KEY, SECRET_KEY_BASE, SERVICE_ROLE_KEY, SUPABASE_PORT; nothing reads them, and they can be removed once no checkout runs the old Supabase services (docs/openbao-secrets.md)');
    const two = retiredKeyWarning(new Map([['SUPABASE_PORT', '8790'], ['ANON_KEY', 'not-a-jwt']]), 'dev');
    assert.match(two, /OpenBao dev secret holds retired keys ANON_KEY, SUPABASE_PORT; /);
    assert.doesNotMatch(two, /SERVICE_ROLE_KEY|SECRET_KEY_BASE|REALTIME_DB_ENC_KEY|not-a-jwt|8790/);
    for (const v of Object.values(RETIRED)) if (v.length > 3) assert.ok(!all.includes(v), v);
  });
});

describe('published ports without the Supabase gateway (drop-unused-supabase-services D3)', () => {
  const port = (n) => ({ ports: [{ host_ip: '127.0.0.1', published: String(n) }] });
  it('dev needs exactly app and Companion on distinct ports; stage and prod exactly the router', () => {
    assert.doesNotThrow(() => checkResolved('dev', { name: 'autologger-dev', services: { app: port(8787), companion: port(8000) } }));
    assert.throws(() => checkResolved('dev', { name: 'autologger-dev', services: { app: port(8787), companion: port(8000), 'supabase-gw': port(8790) } }), /expected set/);
    assert.throws(() => checkResolved('dev', { name: 'autologger-dev', services: { app: port(8787), companion: port(8787) } }), /expected set/);
    assert.throws(() => checkResolved('dev', { name: 'autologger-dev', services: { app: port(8787) } }), /expected set/);
    for (const [env, name, p] of [['stage', 'autologger-stage', 8788], ['prod', 'autologger', 8080]]) {
      assert.doesNotThrow(() => checkResolved(env, { name, services: { router: port(p) } }), env);
      assert.throws(() => checkResolved(env, { name, services: { router: port(p), 'supabase-gw': port(8791) } }), /expected set/, env);
    }
  });
});

describe('sign-in client and bootstrap owner (gotrue-sign-in D3, require-login D1, owner-bootstrap D8)', () => {
  const KEYS = ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'BOOTSTRAP_OWNER_EMAIL'];
  const full = () => new Map([['GOOGLE_CLIENT_ID', 'id.apps.googleusercontent.com'], ['GOOGLE_CLIENT_SECRET', 'secret-value'], ['BOOTSTRAP_OWNER_EMAIL', 'owner-value@example.com']]);
  it('every stack refuses a missing or empty GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET or BOOTSTRAP_OWNER_EMAIL', async () => {
    const { checkSignInClient } = await import('./compose-run.mjs');
    for (const env of ['dev', 'stage', 'prod']) {
      assert.throws(() => checkSignInClient(env, new Map()), /GOOGLE_CLIENT_ID/, env);
      for (const k of KEYS) {
        const missing = full();
        missing.delete(k);
        assert.throws(() => checkSignInClient(env, missing), new RegExp(k), `${env} ${k} missing`);
        assert.throws(() => checkSignInClient(env, new Map([...full(), [k, '']])), new RegExp(k), `${env} ${k} empty`);
      }
      assert.doesNotThrow(() => checkSignInClient(env, full()), env);
    }
  });
  it('every stack refuses a whitespace-only value, without printing values', async () => {
    const { checkSignInClient } = await import('./compose-run.mjs');
    for (const env of ['dev', 'stage', 'prod']) {
      for (const k of KEYS) {
        assert.throws(() => checkSignInClient(env, new Map([...full(), [k, '  \t ']])), new RegExp(k), `${env} ${k}`);
        let msg = '';
        try { checkSignInClient(env, new Map([...full(), [k, ' ']])); } catch (err) { msg = err.message; }
        assert.doesNotMatch(msg, /secret-value|googleusercontent|owner-value/, `${env} ${k}`);
      }
    }
  });
  it('a dev run without BOOTSTRAP_OWNER_EMAIL in OpenBao refuses before docker runs', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('DEV_PORT', '18787'), ...sbSecrets()]);
    const r = await run(['dev', 'compose up -d']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /BOOTSTRAP_OWNER_EMAIL/);
    assert.equal(log('argv'), '');
  });
  it('a dev run without GOOGLE_CLIENT_SECRET in OpenBao refuses before docker runs', async () => {
    writeCreds('dev');
    handler = standIn([secret('GOOGLE_CLIENT_ID', 'gid'), secret('DEV_PORT', '18787'), ...sbSecrets()]);
    const r = await run(['dev', 'compose up -d']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /GOOGLE_CLIENT_SECRET/);
    assert.equal(log('argv'), '');
  });
});

// stage-public-https: the stage operator values (STAGE_IMAGE_TAG, STAGE_PUBLIC_BASE_URL, DOCKER_CONFIG).
describe('stage public mode (stage-public-https)', () => {
  const SHA = 'a'.repeat(40);
  const URL1 = 'https://stage.example.com';
  // The tagged end-to-end runs need the tree to be the tagged commit (checkStageTree): use HEAD.
  const HEAD = spawnSync('git', ['-C', ROOT, 'rev-parse', 'HEAD'], { encoding: 'utf8', env: gitEnv() }).stdout.trim();
  const stageSecrets = () => [secret('GOOGLE_CLIENT_ID', 'gid'), secret('GOOGLE_CLIENT_SECRET', 'gsecret'), secret('BOOTSTRAP_OWNER_EMAIL', 'owner@example.com'), secret('STAGE_PORT', '18788'), ...sbSecrets()];
  it('STAGE_PUBLIC_BASE_URL accepts only a bare https DNS origin', async () => {
    const { parseStagePublicUrl } = await import('./compose-run.mjs');
    assert.equal(parseStagePublicUrl(undefined), '');
    assert.equal(parseStagePublicUrl(''), '');
    assert.equal(parseStagePublicUrl('https://stage.example.com'), 'https://stage.example.com');
    assert.equal(parseStagePublicUrl('https://stage.example.com/'), 'https://stage.example.com');
    for (const bad of ['stage.example.com', 'http://stage.example.com', 'https://stage.example.com/app', 'https://stage.example.com?x=1',
      'https://u:p@stage.example.com', 'https://stage.example.com:8443', 'https://localhost', 'https://10.0.0.1', 'https://Stage.Example.com',
      'https://stage.example.com#x', 'ftp://stage.example.com', 'https://stage.example.com\n', 'https://st"age.example.com', 'http://127.0.0.1:8788',
      'http://localhost:8788', 'http://localhost']) {
      assert.throws(() => parseStagePublicUrl(bad), /STAGE_PUBLIC_BASE_URL/, JSON.stringify(bad));
    }
  });
  it('STAGE_IMAGE_TAG must be a full 40-hex SHA (never prod-push\'s 12-char tag); it selects the ghcr images; https sets COOKIE_SECURE=1', async () => {
    const { parseStageOptions, stageComposeEnv } = await import('./compose-run.mjs');
    const local = parseStageOptions({});
    assert.deepEqual(local.images, { web: 'autologger-stage-web:local', api: 'autologger-stage-api:local' });
    assert.equal(local.cookieSecure, '0');
    assert.deepEqual(stageComposeEnv(local), {});
    for (const bad of ['latest', 'stage', 'A'.repeat(40), 'a'.repeat(12), 'a'.repeat(13), 'a'.repeat(41), `${'a'.repeat(40)} `, '-x']) {
      assert.throws(() => parseStageOptions({ STAGE_IMAGE_TAG: bad }), /STAGE_IMAGE_TAG/, bad);
    }
    // A tagged run is a public run (stage-public-https panel F2).
    assert.throws(() => parseStageOptions({ STAGE_IMAGE_TAG: SHA }), /also set STAGE_PUBLIC_BASE_URL/);
    const pub = parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: 'https://stage.example.com' });
    assert.deepEqual(stageComposeEnv(pub), {
      STAGE_WEB_IMAGE: `ghcr.io/kwcantrell/autologger-web:${SHA}`,
      STAGE_API_IMAGE: `ghcr.io/kwcantrell/autologger-api:${SHA}`,
      STAGE_PUBLIC_BASE_URL: 'https://stage.example.com',
      STAGE_COOKIE_SECURE: '1',
    });
    // DOCKER_CONFIG is read only with a tag (re-panel RS1); untagged it is ignored, as for dev/prod.
    for (const dc of ['rel/dir', '/tmp', join(T, 'no-such-dir')]) {
      assert.equal(parseStageOptions({ DOCKER_CONFIG: dc }).dockerAuths, null, dc);
      assert.deepEqual(stageComposeEnv(parseStageOptions({ DOCKER_CONFIG: dc })), {}, dc);
      assert.throws(() => parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: URL1, DOCKER_CONFIG: dc }), /DOCKER_CONFIG/, dc);
    }
    const dcOk = mkdtempSync(join(T, 'dc-opt-'));
    assert.deepEqual(parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: URL1, DOCKER_CONFIG: dcOk }).dockerAuths, {});
    assert.equal(parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: URL1 }).dockerAuths, null);
    // compose gets the wrapper's temporary directory, never the caller's.
    assert.deepEqual(stageComposeEnv(pub, '/tmp/compose-run-docker-x'), { ...stageComposeEnv(pub), DOCKER_CONFIG: '/tmp/compose-run-docker-x', DOCKER_CONTEXT: 'default' });
    // An https origin without a tag (a local build served publicly) is still COOKIE_SECURE=1.
    assert.equal(parseStageOptions({ STAGE_PUBLIC_BASE_URL: URL1 }).cookieSecure, '1');
  });
  it('DOCKER_CONFIG must be a directory you own that no one else can write (and so must its config.json)', async () => {
    const { checkDockerConfig } = await import('./compose-run.mjs');
    const d = mkdtempSync(join(T, 'dc-'));
    assert.doesNotThrow(() => checkDockerConfig(d));
    writeFileSync(join(d, 'config.json'), '{}');
    chmodSync(join(d, 'config.json'), 0o600);
    assert.doesNotThrow(() => checkDockerConfig(d));
    chmodSync(join(d, 'config.json'), 0o620);
    assert.throws(() => checkDockerConfig(d), /config\.json is writable by group or others/);
    chmodSync(join(d, 'config.json'), 0o600);
    rmSync(join(d, 'config.json'));
    symlinkSync('/dev/null', join(d, 'config.json'));
    assert.throws(() => checkDockerConfig(d), /config\.json must not be a symlink/);
    rmSync(join(d, 'config.json'));
    assert.throws(() => checkDockerConfig('/tmp'), /DOCKER_CONFIG (must be owned by you|is writable by group or others)/);
    assert.throws(() => checkDockerConfig(d, process.getuid() + 1), /DOCKER_CONFIG must be owned by you/);
    chmodSync(d, 0o770);
    assert.throws(() => checkDockerConfig(d), /DOCKER_CONFIG is writable by group or others/);
    chmodSync(d, 0o700);
    const link = join(T, 'dc-link');
    rmSync(link, { force: true });
    symlinkSync(d, link);
    assert.throws(() => checkDockerConfig(link), /DOCKER_CONFIG must not be a symlink/);
    writeFileSync(join(T, 'dc-file'), '');
    assert.throws(() => checkDockerConfig(join(T, 'dc-file')), /DOCKER_CONFIG must be a directory/);
    assert.throws(() => checkDockerConfig(join(T, 'no-such-dir')), /DOCKER_CONFIG does not exist/);
    assert.throws(() => checkDockerConfig('rel/dir'), /absolute path/);
  });
  it('DOCKER_CONFIG: only the inline auths of config.json are kept; a credential helper is refused', async () => {
    const { readDockerAuths, makeDockerConfig } = await import('./compose-run.mjs');
    const d = mkdtempSync(join(T, 'dc-auths-'));
    assert.deepEqual(readDockerAuths(d), {}); // no config.json: anonymous pulls
    const cfg = (o) => {
      rmSync(join(d, 'config.json'), { force: true });
      writeFileSync(join(d, 'config.json'), typeof o === 'string' ? o : JSON.stringify(o));
      chmodSync(join(d, 'config.json'), 0o600);
    };
    const auths = { 'ghcr.io': { auth: Buffer.from('u:tok').toString('base64') } };
    // cliPluginsExtraDirs, currentContext and proxies are dropped: only auths survive.
    cfg({ auths, cliPluginsExtraDirs: ['/tmp/evil'], currentContext: 'evil', proxies: { default: { httpProxy: 'http://evil' } } });
    assert.deepEqual(readDockerAuths(d), auths);
    cfg({ auths: { 'ghcr.io': {} }, credsStore: 'secretservice' });
    assert.throws(() => readDockerAuths(d), /credential helper \(credsStore\/credHelpers\)/);
    cfg({ auths, credHelpers: { 'ghcr.io': 'pass' } });
    assert.throws(() => readDockerAuths(d), /credential helper/);
    cfg({ auths, credHelpers: {}, credsStore: '' }); // empty: no helper
    assert.deepEqual(readDockerAuths(d), auths);
    cfg('{not json');
    assert.throws(() => readDockerAuths(d), /not valid JSON/);
    cfg({ auths: [] });
    assert.throws(() => readDockerAuths(d), /"auths" is not an object/);
    // The temporary directory: 0700, only config.json (0600) holding {"auths": ...}.
    const tmp = makeDockerConfig(auths, T);
    assert.equal(spawnSync('stat', ['-c', '%a', tmp], { encoding: 'utf8' }).stdout.trim(), '700');
    assert.equal(spawnSync('stat', ['-c', '%a', join(tmp, 'config.json')], { encoding: 'utf8' }).stdout.trim(), '600');
    assert.deepEqual(spawnSync('ls', ['-A', tmp], { encoding: 'utf8' }).stdout.trim(), 'config.json');
    assert.deepEqual(JSON.parse(readFileSync(join(tmp, 'config.json'), 'utf8')), { auths });
  });
  it('a pinned tree (REVISION, no .git) refuses an untagged up, build or run', async () => {
    const { checkPinnedUntagged } = await import('./compose-run.mjs');
    const plan = (...s) => s.map((x) => ({ kind: 'compose', args: splitStep(x) }));
    const r = mkdtempSync(join(T, 'tree-pinned-'));
    const all = plan('compose run --rm migrate', 'compose up -d --build');
    assert.doesNotThrow(() => checkPinnedUntagged(r, '', all)); // no REVISION: a plain tree
    writeFileSync(join(r, 'REVISION'), `${SHA}\n`);
    for (const s of ['compose up -d --build', 'compose up -d', 'compose build', 'compose run --rm migrate']) {
      assert.throws(() => checkPinnedUntagged(r, '', plan(s)), /deployed pinned .* need STAGE_IMAGE_TAG/, s);
    }
    assert.doesNotThrow(() => checkPinnedUntagged(r, '', plan('compose down', 'compose logs -f', 'compose down -v')));
    assert.doesNotThrow(() => checkPinnedUntagged(r, SHA, all)); // tagged: checkStageTree and checkStagePlan apply
    mkdirSync(join(r, '.git'));
    assert.doesNotThrow(() => checkPinnedUntagged(r, '', all)); // a git checkout is not pinned
  });
  it('with a tag, the tree must be the tagged commit: git HEAD, or a REVISION file without .git', async () => {
    const { checkStageTree } = await import('./compose-run.mjs');
    assert.doesNotThrow(() => checkStageTree(join(T, 'no-such-tree'), '')); // untagged: no check
    const g = mkdtempSync(join(T, 'tree-git-'));
    const git = (...a) => {
      // Scratch repo: no hooks, and no GIT_* inherited from a git hook (GIT_DIR etc. would aim at the real repo).
      const r = spawnSync('git', ['-C', g, '-c', 'user.name=t', '-c', 'user.email=t@example.invalid', '-c', 'commit.gpgsign=false', '-c', 'core.hooksPath=/dev/null', ...a], { encoding: 'utf8', env: gitEnv() });
      assert.equal(r.status, 0, r.stderr);
      return r.stdout.trim();
    };
    git('init', '-q');
    git('commit', '-q', '--allow-empty', '-m', 'one');
    const one = git('rev-parse', 'HEAD');
    git('commit', '-q', '--allow-empty', '-m', 'two');
    const two = git('rev-parse', 'HEAD');
    assert.doesNotThrow(() => checkStageTree(g, two));
    assert.throws(() => checkStageTree(g, one), /STAGE_IMAGE_TAG is not HEAD/);
    assert.throws(() => checkStageTree(g, one), new RegExp(`run make from a checkout of ${one}`));
    // .git wins over a REVISION file; the hint then names the likely stale .git.
    writeFileSync(join(g, 'REVISION'), `${one}\n`);
    assert.throws(() => checkStageTree(g, one), /is not HEAD .*REVISION file, so its \.git is probably left over .*remove the \.git/);
    const r = mkdtempSync(join(T, 'tree-rev-'));
    assert.throws(() => checkStageTree(r, SHA), /no \.git and no REVISION file/);
    writeFileSync(join(r, 'REVISION'), `${SHA}\n`);
    assert.doesNotThrow(() => checkStageTree(r, SHA));
    assert.throws(() => checkStageTree(r, 'b'.repeat(40)), /is not the REVISION/);
    writeFileSync(join(r, 'REVISION'), 'junk\n');
    assert.throws(() => checkStageTree(r, SHA), /not a 40-hex SHA/);
    rmSync(join(r, 'REVISION'));
    writeFileSync(join(T, 'rev-target'), `${SHA}\n`);
    symlinkSync(join(T, 'rev-target'), join(r, 'REVISION'));
    assert.throws(() => checkStageTree(r, SHA), /REVISION must be a small regular file/);
  });
  it('with a tag nothing builds and every up passes --no-build', async () => {
    const { checkStagePlan, parseStageOptions } = await import('./compose-run.mjs');
    const plan = (...s) => s.map((x) => ({ kind: 'compose', args: splitStep(x) }));
    const tagged = parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: URL1 });
    assert.doesNotThrow(() => checkStagePlan(tagged, plan('compose pull web api', 'compose run --rm migrate', 'compose up -d --no-build')));
    assert.throws(() => checkStagePlan(tagged, plan('compose build')), /building is refused/);
    assert.throws(() => checkStagePlan(tagged, plan('compose up -d --build')), /building is refused/);
    assert.throws(() => checkStagePlan(tagged, plan('compose up -d')), /--no-build/);
    assert.doesNotThrow(() => checkStagePlan(parseStageOptions({}), plan('compose up -d --build')));
  });
  it('the resolved stage config must carry the expected images, origin and cookie posture', async () => {
    const { checkStageResolved, parseStageOptions } = await import('./compose-run.mjs');
    const cfg = (web, api, url, cs) => ({ services: { router: { ports: [{ published: '8788' }] }, web: { image: web }, api: { image: api, environment: { PUBLIC_BASE_URL: url, COOKIE_SECURE: cs, TRUST_PROXY: '1' } } } });
    const local = parseStageOptions({});
    assert.doesNotThrow(() => checkStageResolved(cfg('autologger-stage-web:local', 'autologger-stage-api:local', 'http://localhost:8788', '0'), local));
    assert.throws(() => checkStageResolved(cfg('autologger-stage-web:local', 'autologger-stage-api:local', 'http://localhost:8788', '1'), local), /COOKIE_SECURE/);
    const pub = parseStageOptions({ STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: 'https://stage.example.com' });
    const g = (n) => `ghcr.io/kwcantrell/autologger-${n}:${SHA}`;
    assert.doesNotThrow(() => checkStageResolved(cfg(g('web'), g('api'), 'https://stage.example.com', '1'), pub));
    assert.throws(() => checkStageResolved(cfg('autologger-stage-web:local', g('api'), 'https://stage.example.com', '1'), pub), /images/);
    assert.throws(() => checkStageResolved(cfg(g('web'), g('api'), 'http://localhost:8788', '1'), pub), /PUBLIC_BASE_URL/);
    assert.throws(() => checkStageResolved(cfg(g('web'), g('api'), 'https://stage.example.com', '0'), pub), /COOKIE_SECURE/);
    assert.throws(() => checkStageResolved(cfg('autologger-stage-web:local', 'autologger-stage-api:local', 'http://localhost:9999', '0'), local), /PUBLIC_BASE_URL/);
  });
  it('the stage values are refused for dev and prod, and a bad one stops before any request', async () => {
    writeCreds('dev');
    let r = await run(['dev', 'compose version'], { env: { STAGE_IMAGE_TAG: SHA } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /stage only/);
    writeCreds('stage');
    r = await run(['stage', 'compose version'], { env: { STAGE_PUBLIC_BASE_URL: 'http://stage.example.com' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /STAGE_PUBLIC_BASE_URL/);
    r = await run(['stage', 'compose up -d --build'], { env: { STAGE_IMAGE_TAG: HEAD, STAGE_PUBLIC_BASE_URL: URL1 } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /building is refused/);
    r = await run(['stage', 'compose up -d --no-build'], { env: { STAGE_IMAGE_TAG: HEAD } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /also set STAGE_PUBLIC_BASE_URL/);
    // F1: a tag that is not this tree's HEAD (image/migration skew) stops before any request.
    r = await run(['stage', 'compose up -d --no-build'], { env: { STAGE_IMAGE_TAG: SHA, STAGE_PUBLIC_BASE_URL: URL1 } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /STAGE_IMAGE_TAG is not HEAD/);
    // F4: with a tag, a DOCKER_CONFIG anyone can write (/tmp) stops before any request.
    r = await run(['stage', 'compose version'], { env: { STAGE_IMAGE_TAG: HEAD, STAGE_PUBLIC_BASE_URL: URL1, DOCKER_CONFIG: '/tmp' } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /DOCKER_CONFIG/);
    // FA-2: a credential helper in the caller's config.json stops before any request.
    const dcHelper = mkdtempSync(join(T, 'dc-helper-'));
    writeFileSync(join(dcHelper, 'config.json'), '{"auths":{"ghcr.io":{}},"credsStore":"secretservice"}');
    chmodSync(join(dcHelper, 'config.json'), 0o600);
    r = await run(['stage', 'compose version'], { env: { STAGE_IMAGE_TAG: HEAD, STAGE_PUBLIC_BASE_URL: URL1, DOCKER_CONFIG: dcHelper } });
    assert.notEqual(r.code, 0);
    assert.match(r.out, /credential helper/);
    assert.equal(seen.length, 0);
    assert.equal(log('argv'), '');
  });
  it('a tagged public stage run resolves, passes the compose variables and prints the https origin', async () => {
    writeCreds('stage');
    handler = standIn(stageSecrets());
    // The caller's dir carries both plugin paths the re-panel demonstrated (FA-2): a cli-plugins
    // symlink to a world-writable dir and cliPluginsExtraDirs. compose must see neither.
    const dc = mkdtempSync(join(T, 'dc-run-'));
    const evil = mkdtempSync(join(T, 'evil-'));
    chmodSync(evil, 0o777);
    symlinkSync(evil, join(dc, 'cli-plugins'));
    const auths = { 'ghcr.io': { auth: Buffer.from('u:tok').toString('base64') } };
    writeFileSync(join(dc, 'config.json'), JSON.stringify({ auths, cliPluginsExtraDirs: [evil], currentContext: 'evil' }));
    chmodSync(join(dc, 'config.json'), 0o600);
    const r = await run(['stage', 'resolved', 'compose pull web api', 'compose up -d --no-build', 'urls'], {
      env: { STAGE_IMAGE_TAG: HEAD, STAGE_PUBLIC_BASE_URL: 'https://stage.example.com', DOCKER_CONFIG: dc },
    });
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /stage: +https:\/\/stage\.example\.com +\(the HTTPS edge proxies to http:\/\/127\.0\.0\.1:18788\)/);
    assert.match(log('argv'), /pull web api/);
    const env = log('env');
    assert.match(env, new RegExp(`^STAGE_WEB_IMAGE=ghcr\\.io/kwcantrell/autologger-web:${HEAD}$`, 'm'));
    assert.match(env, new RegExp(`^STAGE_API_IMAGE=ghcr\\.io/kwcantrell/autologger-api:${HEAD}$`, 'm'));
    const childDc = /^DOCKER_CONFIG=(.*)$/m.exec(env)?.[1];
    assert.ok(childDc && childDc !== dc && /\/compose-run-docker-[^/]+$/.test(childDc), childDc);
    assert.equal(log('dockerls').trim(), 'config.json');
    assert.equal(log('dockermode').trim(), '700');
    assert.deepEqual(JSON.parse(log('dockercfg')), { auths });
    assert.equal(existsSync(childDc), false, 'the temporary DOCKER_CONFIG is removed');
    assert.match(env, /^DOCKER_CONTEXT=default$/m);
    assert.match(env, /^STAGE_PUBLIC_BASE_URL=https:\/\/stage\.example\.com$/m);
    assert.match(env, /^STAGE_COOKIE_SECURE=1$/m);
    assert.doesNotMatch(env, /^STAGE_IMAGE_TAG=/m);
  });
  it('an untagged stage run is the local one (resolved checks the :local images; DOCKER_CONFIG ignored)', async () => {
    writeCreds('stage');
    handler = standIn(stageSecrets());
    // An ambient DOCKER_CONFIG (even /tmp) neither refuses nor reaches compose without a tag (RS1).
    const r = await run(['stage', 'resolved', 'compose up -d --build', 'urls'], { env: { DOCKER_CONFIG: '/tmp' } });
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /stage: +http:\/\/localhost:18788/);
    assert.doesNotMatch(log('env'), /^STAGE_(WEB_IMAGE|API_IMAGE|PUBLIC_BASE_URL|COOKIE_SECURE)=/m);
    assert.doesNotMatch(log('env'), /^DOCKER_(CONFIG|CONTEXT)=/m);
  });
  it('the temporary DOCKER_CONFIG is removed when a step fails and on SIGTERM', async () => {
    writeCreds('stage');
    handler = standIn(stageSecrets());
    const dc = mkdtempSync(join(T, 'dc-clean-'));
    const env = { STAGE_IMAGE_TAG: HEAD, STAGE_PUBLIC_BASE_URL: URL1, DOCKER_CONFIG: dc };
    mkdirSync(join(T, 'log'), { recursive: true });
    writeFileSync(join(T, 'log/fail'), '');
    let r = await run(['stage', 'compose pull web api', 'compose up -d --no-build'], { env });
    assert.equal(r.code, 3, r.out);
    let childDc = /^DOCKER_CONFIG=(.*)$/m.exec(log('env'))?.[1];
    assert.ok(childDc && childDc !== dc, childDc);
    assert.equal(existsSync(childDc), false, 'removed after a failed step');
    rmSync(join(T, 'log'), { recursive: true, force: true });
    mkdirSync(join(T, 'log'), { recursive: true });
    writeFileSync(join(T, 'log/sleep'), '');
    r = await run(['stage', 'compose up -d --no-build'], {
      env,
      onSpawn: (c) => {
        const t = setInterval(() => { if (existsSync(join(T, 'log/env'))) { clearInterval(t); setTimeout(() => c.kill('SIGTERM'), 200); } }, 50);
      },
    });
    assert.equal(r.code, 143, r.out);
    childDc = /^DOCKER_CONFIG=(.*)$/m.exec(log('env'))?.[1];
    assert.ok(childDc && childDc !== dc, childDc);
    assert.equal(existsSync(childDc), false, 'removed after SIGTERM');
  });
  it('the stage values cannot come from OpenBao', () => {
    for (const k of ['STAGE_IMAGE_TAG', 'STAGE_WEB_IMAGE', 'STAGE_API_IMAGE', 'STAGE_PUBLIC_BASE_URL', 'STAGE_COOKIE_SECURE', 'DOCKER_CONFIG']) {
      assert.throws(() => validateSecrets(kv([secret(k, 'x')]), allowedNames('stage')), /not-allowed/, k);
    }
  });
});

// drop-unused-supabase-services D5: every compose up and down the Makefile runs removes orphans, so
// the retired Supabase containers another checkout started are gone after the next up, down or reset.
describe('Makefile compose steps remove orphans (drop-unused-supabase-services D5)', () => {
  const make = readFileSync(join(ROOT, 'Makefile'), 'utf8');
  const steps = (verb) => [...make.matchAll(new RegExp(`'compose ${verb}\\b[^']*'`, 'g'))].map((m) => m[0]);
  it('holds four compose up and five compose down steps, each with --remove-orphans', () => {
    const ups = steps('up');
    const downs = steps('down');
    assert.equal(ups.length, 4, ups.join(' '));
    assert.equal(downs.length, 5, downs.join(' '));
    for (const s of [...ups, ...downs]) assert.match(s, / --remove-orphans\b/, s);
  });
  it('the tagged stage up still passes --no-build', async () => {
    const { checkStagePlan, parseStageOptions } = await import('./compose-run.mjs');
    const plan = (...s) => s.map((x) => ({ kind: 'compose', args: splitStep(x) }));
    const tagged = parseStageOptions({ STAGE_IMAGE_TAG: 'a'.repeat(40), STAGE_PUBLIC_BASE_URL: 'https://stage.example.com' });
    assert.ok(steps('up').includes("'compose up -d --no-build --remove-orphans'"));
    assert.doesNotThrow(() => checkStagePlan(tagged, plan('compose pull web api', 'compose run --rm migrate', 'compose up -d --no-build --remove-orphans')));
  });
});
