// Tests for docker/scripts/supabase-keys.mjs (supabase-db task 1.2, design D5; openbao-secrets D4).
// Run: node --test docker/scripts/supabase-keys.test.mjs   (part of the root `npm test`)
//
// The generator runs as a child process against a local HTTPS stand-in for OpenBao's KV v2 API
// (127.0.0.1, throwaway CA generated by openssl at test time). Test hooks: AUTOLOGGER_TEST=1 with
// an absolute AUTOLOGGER_TEST_CRED_DIR, never for prod (as compose-run.mjs H10).

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import https from 'node:https';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { after, before, beforeEach, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const GEN = join(ROOT, 'docker/scripts/supabase-keys.mjs');
const TOKEN = 'tok-SHOULD-NOT-LEAK';
const KVURL = '/v1/kv/data/autologger/dev';
// drop-unused-supabase-services D3: the generator owns four keys; the five retired ones are never
// created, reported or written.
const ALL = ['POSTGRES_PASSWORD', 'SUPABASE_ROLES_PASSWORD', 'APP_DB_PASSWORD', 'JWT_SECRET'];
const RETIRED = ['ANON_KEY', 'SERVICE_ROLE_KEY', 'SECRET_KEY_BASE', 'REALTIME_DB_ENC_KEY', 'SUPABASE_PORT'];
const FORMAT = {
  POSTGRES_PASSWORD: /^[0-9a-f]{32}$/,
  SUPABASE_ROLES_PASSWORD: /^[0-9a-f]{32}$/,
  APP_DB_PASSWORD: /^[0-9a-f]{32}$/,
  JWT_SECRET: /^[A-Za-z0-9_-]{43}$/,
};

let T;
let server;
let port;
let handler;
let seen;

function ossl(...args) {
  const r = spawnSync('openssl', args, { cwd: T, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`openssl ${args[0]} failed: ${r.stderr}`);
}

function json(res, status, obj) {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(JSON.stringify(obj));
}

// keys: names already in the secret (null: the path does not exist); write: status for the
// PATCH or POST; version: the current version; gone: { status, metadata } answers the read of a
// soft-deleted or destroyed current version (KV v2 keeps the metadata, data.data is null).
function standIn({ keys = [], write = 200, version = 4, gone = null } = {}) {
  return (req, body, res) => {
    if (req.url !== KVURL) return json(res, 404, { errors: [] });
    if (req.headers['x-vault-token'] !== TOKEN) return json(res, 403, { errors: ['permission denied'] });
    if (req.method === 'GET') {
      if (keys === null) return json(res, 404, { errors: [] });
      if (gone) {
        const data = gone.status === 200 && keys.length ? Object.fromEntries(keys.map((k) => [k, `SENTINEL-${k}`])) : null;
        return json(res, gone.status, { errors: [], data: { data, metadata: { version, deletion_time: '', destroyed: false, ...gone.metadata } } });
      }
      return json(res, 200, { data: { data: Object.fromEntries(keys.map((k) => [k, `SENTINEL-${k}`])), metadata: { version, deletion_time: '', destroyed: false } } });
    }
    if (req.method === 'PATCH' || req.method === 'POST') {
      return write === 200 ? json(res, 200, { data: { version: version + 1 } }) : json(res, write, { errors: ['check-and-set parameter did not match the current version'] });
    }
    return json(res, 405, { errors: [] });
  };
}

function writeFiles({ envOver = {}, writerMode = 0o600, writer = `BAO_TOKEN=${TOKEN}\n` } = {}) {
  const dir = join(T, 'cred');
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir);
  const env = {
    BAO_ADDR: `https://127.0.0.1:${port}`,
    BAO_CACERT: join(T, 'ca.crt'),
    BAO_KV_PATH: 'kv/autologger/dev',
    ...envOver,
  };
  const f = join(dir, '.env.openbao.dev');
  writeFileSync(f, Object.entries(env).map(([k, v]) => `${k}=${v}`).join('\n') + '\n');
  chmodSync(f, 0o600);
  const w = join(dir, 'writer');
  writeFileSync(w, writer);
  chmodSync(w, writerMode);
  return w;
}

function run(args, env = {}) {
  return new Promise((ok) => {
    const child = spawn(process.execPath, [GEN, ...args], {
      cwd: ROOT,
      env: { PATH: '/usr/bin:/bin', HOME: process.env.HOME, AUTOLOGGER_TEST: '1', AUTOLOGGER_TEST_CRED_DIR: join(T, 'cred'), ...env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    child.on('close', (code) => ok({ code, out }));
  });
}

before(async () => {
  T = mkdtempSync(join(tmpdir(), 'supabase-keys-test-'));
  ossl('req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '1', '-subj', '/CN=ca', '-keyout', 'ca.key', '-out', 'ca.crt');
  ossl('req', '-newkey', 'rsa:2048', '-nodes', '-subj', '/CN=127.0.0.1', '-keyout', 'srv.key', '-out', 'srv.csr');
  writeFileSync(join(T, 'srv.ext'), 'subjectAltName=IP:127.0.0.1\n');
  ossl('x509', '-req', '-in', 'srv.csr', '-CA', 'ca.crt', '-CAkey', 'ca.key', '-CAcreateserial', '-days', '1', '-extfile', 'srv.ext', '-out', 'srv.crt');
  chmodSync(join(T, 'ca.crt'), 0o644);
  server = https.createServer({ key: readFileSync(join(T, 'srv.key')), cert: readFileSync(join(T, 'srv.crt')) }, (req, res) => {
    let body = '';
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      seen.push({ method: req.method, url: req.url, headers: req.headers, body });
      handler(req, body, res);
    });
  });
  port = await new Promise((ok) => server.listen(0, '127.0.0.1', () => ok(server.address().port)));
});
after(() => {
  server?.closeAllConnections();
  server?.close();
  if (T) rmSync(T, { recursive: true, force: true });
});
beforeEach(() => {
  seen = [];
  handler = standIn();
});

describe('supabase-keys.mjs (supabase-db D5, openbao-secrets D4)', () => {
  const writes = () => seen.filter((s) => s.method === 'PATCH' || s.method === 'POST');
  it('a soft-deleted or destroyed current version is refused, with no write', async () => {
    const past = new Date(Date.now() - 3600e3).toISOString();
    const cases = [
      { gone: { status: 404, metadata: { deletion_time: past } }, hint: 'undelete' }, // bao kv delete
      { gone: { status: 404, metadata: { destroyed: true } }, hint: 'rollback' }, // bao kv destroy
      { gone: { status: 404, metadata: {} }, hint: 'undelete' }, // 404 that still carries metadata.version
      { gone: { status: 200, metadata: { deletion_time: past } }, hint: 'undelete' }, // defensive: 200 shape
      { gone: { status: 200, metadata: { deletion_time: 'garbage' } }, hint: 'undelete' }, // unparseable: fail closed
      { gone: { status: 200, metadata: { destroyed: true } }, hint: 'rollback' },
    ];
    for (const { gone, hint } of cases) {
      const w = writeFiles();
      seen = [];
      handler = standIn({ keys: ['POSTGRES_PASSWORD'], gone });
      const r = await run(['dev', '--writer', w]);
      const tag = JSON.stringify(gone);
      assert.notEqual(r.code, 0, `${tag}: ${r.out}`);
      assert.match(r.out, /deleted|destroyed/, tag);
      assert.match(r.out, /bao kv rollback/, tag);
      if (hint === 'undelete') assert.match(r.out, /bao kv undelete/, tag);
      else assert.doesNotMatch(r.out, /undelete/, tag);
      assert.doesNotMatch(r.out, /^created /m, tag);
      assert.deepEqual(writes(), [], tag);
      assert.doesNotMatch(r.out, new RegExp(`SENTINEL|${TOKEN}`));
    }
  });

  it('a live version with a future deletion_time (delete_version_after) is written normally', async () => {
    const w = writeFiles();
    const future = new Date(Date.now() + 30 * 86400e3).toISOString();
    handler = standIn({ keys: ['POSTGRES_PASSWORD'], gone: { status: 200, metadata: { deletion_time: future } } });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /^kept POSTGRES_PASSWORD$/m);
    assert.match(r.out, /^created APP_DB_PASSWORD$/m);
    assert.equal(writes().length, 1);
    assert.equal(writes()[0].method, 'PATCH');
  });

  it('existing keys are kept: no write request, and no value is printed', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ALL });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    for (const k of ALL) assert.match(r.out, new RegExp(`^kept ${k}$`, 'm'));
    assert.deepEqual(seen.map((s) => `${s.method} ${s.url}`), [`GET ${KVURL}`]);
    assert.doesNotMatch(r.out, /SENTINEL/);
  });

  it('missing keys are merged in one check-and-set PATCH, each in its format, and never printed', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ['POSTGRES_PASSWORD', 'DEEPGRAM_API_KEY'] });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /^kept POSTGRES_PASSWORD$/m);
    assert.equal(writes().length, 1);
    const [p] = writes();
    assert.equal(p.method, 'PATCH');
    assert.equal(p.url, KVURL);
    assert.equal(p.headers['content-type'], 'application/merge-patch+json');
    assert.equal(p.headers['x-vault-token'], TOKEN);
    const b = JSON.parse(p.body);
    assert.deepEqual(b.options, { cas: 4 });
    const got = b.data;
    assert.deepEqual(Object.keys(got).sort(), ALL.filter((k) => k !== 'POSTGRES_PASSWORD').sort());
    for (const [k, v] of Object.entries(got)) {
      assert.match(v, FORMAT[k], k);
      assert.ok(!r.out.includes(v), k);
      assert.match(r.out, new RegExp(`^created ${k}$`, 'm'));
    }
    assert.ok(!r.out.includes(TOKEN));
  });

  it('a path that does not exist yet gets a create-only POST (cas 0)', async () => {
    const w = writeFiles();
    handler = standIn({ keys: null });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.equal(writes().length, 1);
    const [p] = writes();
    assert.equal(p.method, 'POST');
    assert.match(p.headers['content-type'], /^application\/json/);
    const b = JSON.parse(p.body);
    assert.deepEqual(b.options, { cas: 0 });
    // drop-unused-supabase-services D3: exactly the four keys, each in its format.
    assert.deepEqual(Object.keys(b.data).sort(), [...ALL].sort());
    for (const [k, v] of Object.entries(b.data)) assert.match(v, FORMAT[k], k);
    assert.doesNotMatch(r.out, new RegExp(RETIRED.join('|')));
  });

  it('an existing stack gets only the app password created (catalog-pg-schema D4)', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ALL.filter((k) => k !== 'APP_DB_PASSWORD') });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.equal(writes().length, 1);
    const b = JSON.parse(writes()[0].body);
    assert.deepEqual(Object.keys(b.data), ['APP_DB_PASSWORD']);
    assert.match(b.data.APP_DB_PASSWORD, FORMAT.APP_DB_PASSWORD);
    assert.ok(!r.out.includes(b.data.APP_DB_PASSWORD));
    assert.match(r.out, /^created APP_DB_PASSWORD$/m);
    for (const k of ALL.filter((x) => x !== 'APP_DB_PASSWORD')) assert.match(r.out, new RegExp(`^kept ${k}$`, 'm'));
  });

  // drop-unused-supabase-services D3: no trio any more; JWT_SECRET stands alone.
  it('a path with JWT_SECRET and no ANON_KEY is not refused and writes nothing new', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ALL });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.deepEqual(writes(), []);
    assert.doesNotMatch(r.out, /ANON_KEY|SERVICE_ROLE_KEY/);
  });

  it('the retired keys are never reported and cause no write', async () => {
    const w = writeFiles();
    handler = standIn({ keys: [...ALL, ...RETIRED] });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    for (const k of ALL) assert.match(r.out, new RegExp(`^kept ${k}$`, 'm'));
    assert.doesNotMatch(r.out, new RegExp(RETIRED.join('|')));
    assert.deepEqual(writes(), []);
  });

  it('a path missing only JWT_SECRET gets only it created', async () => {
    const w = writeFiles();
    handler = standIn({ keys: [...ALL.filter((k) => k !== 'JWT_SECRET'), ...RETIRED] });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.equal(writes().length, 1);
    const b = JSON.parse(writes()[0].body);
    assert.deepEqual(Object.keys(b.data), ['JWT_SECRET']);
    assert.match(b.data.JWT_SECRET, FORMAT.JWT_SECRET);
    assert.match(r.out, /^created JWT_SECRET$/m);
    assert.doesNotMatch(r.out, new RegExp(RETIRED.join('|')));
  });

  it('a rejected write exits non-zero with no retry', async () => {
    const w = writeFiles();
    for (const status of [400, 403, 500]) {
      seen = [];
      handler = standIn({ keys: ['POSTGRES_PASSWORD'], write: status });
      const r = await run(['dev', '--writer', w]);
      assert.notEqual(r.code, 0, String(status));
      assert.match(r.out, new RegExp(`creating .*HTTP ${status}.*nothing was created`));
      assert.equal(writes().length, 1);
    }
  });

  it('a refused read stops before any write, printing the status only', async () => {
    const w = writeFiles({ writer: 'BAO_TOKEN=wrong-token\n' });
    const r = await run(['dev', '--writer', w]);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /HTTP 403: permission denied/);
    assert.equal(writes().length, 0);
    assert.doesNotMatch(r.out, /wrong-token/);
  });

  it('the token can come from BAO_TOKEN, or from a writer file holding the token alone', async () => {
    writeFiles();
    handler = standIn({ keys: ALL });
    let r = await run(['dev'], { BAO_TOKEN: TOKEN });
    assert.equal(r.code, 0, r.out);
    const w = writeFiles({ writer: `${TOKEN}\n` });
    r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    r = await run(['dev']);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /BAO_TOKEN/);
  });

  it('a writer file readable by others is refused before any request', async () => {
    const w = writeFiles({ writerMode: 0o644 });
    const r = await run(['dev', '--writer', w]);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /chmod 600/);
    assert.equal(seen.length, 0);
  });

  it('an http:// OpenBao address or a KV path for another stack is refused before any request', async () => {
    for (const [over, re] of [[{ BAO_ADDR: `http://127.0.0.1:${port}` }, /https:\/\//], [{ BAO_KV_PATH: 'kv/autologger/prod' }, /BAO_KV_PATH/]]) {
      const w = writeFiles({ envOver: over });
      const r = await run(['dev', '--writer', w]);
      assert.notEqual(r.code, 0);
      assert.match(r.out, re);
    }
    assert.equal(seen.length, 0);
  });

  it('bad usage and test hooks for prod are refused before any request', async () => {
    const w = writeFiles();
    for (const args of [[], ['qa', '--writer', w], ['dev', '--writer'], ['dev', '--token', w], ['dev', '--writer', w, 'x'], ['prod', '--writer', w]]) {
      const r = await run(args, { BAO_TOKEN: TOKEN });
      assert.notEqual(r.code, 0, args.join(' '));
    }
    assert.equal(seen.length, 0);
  });

  it('refuses Node older than 22.12 (shared check)', async () => {
    const { checkNodeVersion } = await import('./compose-run.mjs');
    assert.throws(() => checkNodeVersion('22.11.0'), /22\.12/);
  });
});
