// Tests for docker/scripts/supabase-keys.mjs (supabase-db task 1.2; design D5).
// Run: node --test docker/scripts/supabase-keys.test.mjs   (part of the root `npm test`)
//
// The generator runs as a child process against a local HTTPS stand-in for Infisical (127.0.0.1,
// throwaway CA generated by openssl at test time). Test hooks: AUTOLOGGER_TEST=1 with an absolute
// AUTOLOGGER_TEST_CRED_DIR, never for prod (as compose-run.mjs H10).

import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import https from 'node:https';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { after, before, beforeEach, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const GEN = join(ROOT, 'docker/scripts/supabase-keys.mjs');
const SECRET = 'wsec-SHOULD-NOT-LEAK';
const TOKEN = 'tok-SHOULD-NOT-LEAK';

let T;
let server;
let port;
let handler;
let seen;

function ossl(...args) {
  const r = spawnSync('openssl', args, { cwd: T, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`openssl ${args[0]} failed: ${r.stderr}`);
}

function json(res, status, obj) {
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(JSON.stringify(obj));
}

// keys: names already in the environment; create: status for the batch POST.
function standIn({ keys = [], create = 200 } = {}) {
  return (req, body, res) => {
    if (req.method === 'POST' && req.url === '/api/v1/auth/universal-auth/login') return json(res, 200, { accessToken: TOKEN });
    if (req.method === 'GET' && req.url.startsWith('/api/v4/secrets?')) {
      return json(res, 200, { secrets: keys.map((k) => ({ secretKey: k, secretValue: '<hidden-by-infisical>', secretValueHidden: true })), imports: [] });
    }
    if (req.method === 'POST' && req.url === '/api/v4/secrets/batch') {
      return create === 200 ? json(res, 200, { secrets: [] }) : json(res, create, { message: 'Secret already exist' });
    }
    return json(res, 404, { message: 'no route' });
  };
}

function writeFiles({ envOver = {}, writerMode = 0o600 } = {}) {
  const dir = join(T, 'cred');
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir);
  const env = {
    INFISICAL_PROJECT_ID: 'proj-1',
    INFISICAL_DOMAIN: `https://127.0.0.1:${port}`,
    INFISICAL_CA_FILE: join(T, 'ca.crt'),
    ...envOver,
  };
  const f = join(dir, '.env.infisical.dev');
  writeFileSync(f, Object.entries(env).map(([k, v]) => `${k}=${v}`).join('\n') + '\n');
  chmodSync(f, 0o600);
  const w = join(dir, 'writer');
  writeFileSync(w, `INFISICAL_UNIVERSAL_AUTH_CLIENT_ID=wid\nINFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET=${SECRET}\n`);
  chmodSync(w, writerMode);
  return w;
}

function run(args, env = {}) {
  return new Promise((ok) => {
    const child = spawn(process.execPath, [GEN, ...args], {
      cwd: ROOT,
      env: { PATH: '/usr/bin:/bin', HOME: process.env.HOME, AUTOLOGGER_TEST: '1', AUTOLOGGER_TEST_CRED_DIR: join(T, 'cred'), ...env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let out = '';
    child.stdout.on('data', (d) => { out += d; });
    child.stderr.on('data', (d) => { out += d; });
    child.on('close', (code) => ok({ code, out }));
  });
}

before(async () => {
  T = mkdtempSync(join(tmpdir(), 'supabase-keys-test-'));
  ossl('req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-days', '1', '-subj', '/CN=ca', '-keyout', 'ca.key', '-out', 'ca.crt');
  ossl('req', '-newkey', 'rsa:2048', '-nodes', '-subj', '/CN=127.0.0.1', '-keyout', 'srv.key', '-out', 'srv.csr');
  writeFileSync(join(T, 'srv.ext'), 'subjectAltName=IP:127.0.0.1\n');
  ossl('x509', '-req', '-in', 'srv.csr', '-CA', 'ca.crt', '-CAkey', 'ca.key', '-CAcreateserial', '-days', '1', '-extfile', 'srv.ext', '-out', 'srv.crt');
  chmodSync(join(T, 'ca.crt'), 0o644);
  server = https.createServer({ key: readFileSync(join(T, 'srv.key')), cert: readFileSync(join(T, 'srv.crt')) }, (req, res) => {
    let body = '';
    req.on('data', (d) => { body += d; });
    req.on('end', () => {
      seen.push({ method: req.method, url: req.url, headers: req.headers, body });
      handler(req, body, res);
    });
  });
  port = await new Promise((ok) => server.listen(0, '127.0.0.1', () => ok(server.address().port)));
});
after(() => {
  server?.closeAllConnections();
  server?.close();
  if (T) rmSync(T, { recursive: true, force: true });
});
beforeEach(() => {
  seen = [];
  handler = standIn();
});

describe('supabase-keys.mjs (supabase-db D5)', () => {
  it('an existing key is kept: no write request', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ['POSTGRES_PASSWORD'] });
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /^kept POSTGRES_PASSWORD$/m);
    assert.deepEqual(seen.map((s) => s.method), ['POST', 'GET']);
  });

  it('a missing key is created once with 32 lowercase hex characters that are never printed', async () => {
    const w = writeFiles();
    const r = await run(['dev', '--writer', w]);
    assert.equal(r.code, 0, r.out);
    assert.match(r.out, /^created POSTGRES_PASSWORD$/m);
    const posts = seen.filter((s) => s.url === '/api/v4/secrets/batch');
    assert.equal(posts.length, 1);
    assert.equal(posts[0].method, 'POST');
    const b = JSON.parse(posts[0].body);
    assert.equal(b.projectId, 'proj-1');
    assert.equal(b.environment, 'dev');
    assert.equal(b.secretPath, '/');
    assert.equal(b.secrets.length, 1);
    assert.equal(b.secrets[0].secretKey, 'POSTGRES_PASSWORD');
    assert.match(b.secrets[0].secretValue, /^[0-9a-f]{32}$/);
    assert.ok(!r.out.includes(b.secrets[0].secretValue));
    assert.ok(!r.out.includes(SECRET) && !r.out.includes(TOKEN));
    assert.equal(posts[0].headers.authorization, `Bearer ${TOKEN}`);
  });

  it('lists names with the same scope as compose-run and without values', async () => {
    const w = writeFiles();
    handler = standIn({ keys: ['POSTGRES_PASSWORD'] });
    await run(['dev', '--writer', w]);
    const q = new URL(seen.find((s) => s.method === 'GET').url, 'https://x').searchParams;
    assert.equal(q.get('projectId'), 'proj-1');
    assert.equal(q.get('environment'), 'dev');
    assert.equal(q.get('secretPath'), '/');
    assert.equal(q.get('recursive'), 'false');
    assert.equal(q.get('includeImports'), 'false');
    assert.equal(q.get('viewSecretValue'), 'false');
  });

  it('a rejected create exits non-zero with no update or retry', async () => {
    const w = writeFiles();
    for (const status of [400, 409, 403]) {
      seen = [];
      handler = standIn({ create: status });
      const r = await run(['dev', '--writer', w]);
      assert.notEqual(r.code, 0, String(status));
      assert.match(r.out, new RegExp(`POSTGRES_PASSWORD.*HTTP ${status}`));
      assert.equal(seen.filter((s) => s.url.startsWith('/api/v4/secrets/batch')).length, 1);
      assert.equal(seen.filter((s) => s.method === 'PATCH').length, 0);
    }
  });

  it('a writer file readable by others is refused before any request', async () => {
    const w = writeFiles({ writerMode: 0o644 });
    const r = await run(['dev', '--writer', w]);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /chmod 600/);
    assert.equal(seen.length, 0);
  });

  it('an http:// Infisical URL is refused before any request', async () => {
    const w = writeFiles({ envOver: { INFISICAL_DOMAIN: `http://127.0.0.1:${port}` } });
    const r = await run(['dev', '--writer', w]);
    assert.notEqual(r.code, 0);
    assert.match(r.out, /https:\/\//);
    assert.equal(seen.length, 0);
  });

  it('bad usage and test hooks for prod are refused before any request', async () => {
    const w = writeFiles();
    for (const args of [['dev'], ['qa', '--writer', w], ['dev', '--writer'], ['prod', '--writer', w]]) {
      const r = await run(args);
      assert.notEqual(r.code, 0, args.join(' '));
    }
    assert.equal(seen.length, 0);
  });

  it('refuses Node older than 22.12 (shared check)', async () => {
    const { checkNodeVersion } = await import('./compose-run.mjs');
    assert.throws(() => checkNodeVersion('22.11.0'), /22\.12/);
  });
});
