import { describe, expect, it } from 'vitest';
import { isAutoGeneratedMetadataJson } from '../routers/events';
import { fakeRuntime } from '../test/fakeCore';
import { formatSmpte, fromTotalFrames, isoZ } from '../timecode';
import { EventStore, eventRowToRpc } from './eventStore';

describe('eventRowToRpc', () => {
  it('maps a row with a timecode', () => {
    const r = {
      id: 'e1',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      frame_rate: 24,
      timecode_total_frames: 48,
      category: 'note',
      message: 'hi',
      metadata_json: '{"a":1}',
    };
    expect(eventRowToRpc(r)).toEqual({
      event_id: 'e1',
      wall_time_utc: '2026-06-25T00:00:00.000Z',
      timecode: formatSmpte(fromTotalFrames(48, 24)),
      frame_rate: 24,
      timecode_total_frames: 48,
      category: 'note',
      message: 'hi',
      metadata_json: '{"a":1}',
    });
  });

  it('nulls timecode fields when timecode_total_frames is absent, defaults metadata', () => {
    const r = {
      id: 'e2',
      wall_time_utc: '2026-06-25T00:00:01.000Z',
      frame_rate: 24,
      timecode_total_frames: null,
      category: 'internal',
      message: 'rec start',
      metadata_json: null,
    };
    expect(eventRowToRpc(r)).toEqual({
      event_id: 'e2',
      wall_time_utc: '2026-06-25T00:00:01.000Z',
      timecode: null,
      frame_rate: null,
      timecode_total_frames: null,
      category: 'internal',
      message: 'rec start',
      metadata_json: '{}',
    });
  });
});

// code-health-tail task 2.2 (design D10) — behavior pin over a REAL core
// (in-memory SQLite), written BEFORE the count SQL moved into
// core.eventCounts(): listEvents' total/loggedTotal must exclude
// internal-category rows regardless of casing/whitespace, and near-miss
// categories must still count as logged.
describe('listEvents counts over a real core (D10 pin)', () => {
  it('total counts every event; loggedTotal excludes internal (any casing/whitespace)', () => {
    const { core } = fakeRuntime();
    const categories = [
      'mark', // logged
      'note', // logged
      'internal', // filtered
      'Internal', // filtered (casing)
      ' INTERNAL ', // filtered (casing + surrounding spaces)
      '\tinternal', // logged — SQLite trim() strips SPACES only, a tab survives
      'INTERNAL', // filtered
      'internally', // logged
      'x internal', // logged
    ];
    categories.forEach((cat, i) => {
      core.db.run(
        `INSERT INTO events (id, wall_time_utc, frame_rate, category, message)
         VALUES (?, ?, ?, ?, ?)`,
        `e${i}`,
        '2026-06-25T00:00:00.000Z',
        30,
        cat,
        `m${i}`,
      );
    });
    const out = new EventStore(core).listEvents({ limit: 100, offset: 0 });
    expect(out.total).toBe(9);
    expect(out.loggedTotal).toBe(5);
    expect(out.events).toHaveLength(9);
  });
});

describe('deleteAutoGeneratedEvents', () => {
  it('deletes only metadata whose auto_generated value is JSON true and broadcasts once', () => {
    const { core, broadcasts } = fakeRuntime();
    const rows = [
      ['auto', '{"auto_generated":true}'],
      ['auto-extra', '{"auto_generated":true,"run":"r1"}'],
      ['manual', '{}'],
      ['false', '{"auto_generated":false}'],
      ['number', '{"auto_generated":1}'],
      ['string', '{"auto_generated":"true"}'],
      ['malformed', '{"auto_generated":true'],
    ];
    rows.forEach(([id, metadataJson], index) => {
      core.db.run(
        `INSERT INTO events
           (id, wall_time_utc, frame_rate, timecode_total_frames, category, message, metadata_json)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        id,
        `2026-06-25T00:00:0${index}.000Z`,
        24,
        index,
        'note',
        id,
        metadataJson,
      );
    });

    const deleted = new EventStore(core).deleteAutoGeneratedEvents();

    expect(deleted).toBe(2);
    expect(core.all('SELECT id FROM events ORDER BY id')).toEqual([
      { id: 'false' },
      { id: 'malformed' },
      { id: 'manual' },
      { id: 'number' },
      { id: 'string' },
    ]);
    expect(core.revision()).toBe(1);
    expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
  });

  it('does not bump the revision or broadcast when no auto-generated rows exist', () => {
    const { core, broadcasts } = fakeRuntime();
    core.db.run(
      `INSERT INTO events
         (id, wall_time_utc, frame_rate, timecode_total_frames, category, message, metadata_json)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      'manual',
      '2026-06-25T00:00:00.000Z',
      24,
      0,
      'note',
      'manual',
      '{}',
    );

    expect(new EventStore(core).deleteAutoGeneratedEvents()).toBe(0);
    expect(core.revision()).toBe(0);
    expect(broadcasts).toEqual([]);
  });
});

// event-generate-hardening task 1.2 (design D1) — hasAutoGeneratedEvents():
// a read-only EXISTS check over the SAME SQL predicate deleteAutoGeneratedEvents
// uses, independent of any page/window.
describe('hasAutoGeneratedEvents', () => {
  function insertEvent(
    core: ReturnType<typeof fakeRuntime>['core'],
    id: string,
    metadataJson: string,
    index: number,
  ) {
    core.db.run(
      `INSERT INTO events
         (id, wall_time_utc, frame_rate, timecode_total_frames, category, message, metadata_json)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      id,
      `2026-06-25T00:00:0${index}.000Z`,
      24,
      index,
      'note',
      id,
      metadataJson,
    );
  }

  it('is false when the session has no events', () => {
    const { core } = fakeRuntime();
    expect(new EventStore(core).hasAutoGeneratedEvents()).toBe(false);
  });

  it('is false when only non-auto/false/malformed metadata exists (predicate edges)', () => {
    const { core } = fakeRuntime();
    const rows: Array<[string, string]> = [
      ['manual', '{}'],
      ['false', '{"auto_generated":false}'],
      ['number', '{"auto_generated":1}'],
      ['string', '{"auto_generated":"true"}'],
      ['malformed', '{"auto_generated":true'],
    ];
    rows.forEach(([id, metadataJson], index) => {
      insertEvent(core, id, metadataJson, index);
    });
    expect(new EventStore(core).hasAutoGeneratedEvents()).toBe(false);
  });

  it('is true when at least one row carries auto_generated === true (JSON boolean)', () => {
    const { core } = fakeRuntime();
    insertEvent(core, 'manual', '{}', 0);
    insertEvent(core, 'auto', '{"auto_generated":true}', 1);
    expect(new EventStore(core).hasAutoGeneratedEvents()).toBe(true);
  });

  it('is true for an auto row outside any list page/window (whole-session semantics)', () => {
    const { core } = fakeRuntime();
    // 3 manual rows first, then the one auto row last — a listEvents({limit:1})
    // window would never see it, but the whole-session check must.
    insertEvent(core, 'm0', '{}', 0);
    insertEvent(core, 'm1', '{}', 1);
    insertEvent(core, 'm2', '{}', 2);
    insertEvent(core, 'auto', '{"auto_generated":true}', 3);
    const store = new EventStore(core);
    const page = store.listEvents({ limit: 1, offset: 0 });
    expect(page.events.some((e) => e.event_id === 'auto')).toBe(false);
    expect(store.hasAutoGeneratedEvents()).toBe(true);
  });

  it('does not mutate revision or broadcast (read-only)', () => {
    const { core, broadcasts } = fakeRuntime();
    insertEvent(core, 'auto', '{"auto_generated":true}', 0);
    const revBefore = core.revision();
    expect(new EventStore(core).hasAutoGeneratedEvents()).toBe(true);
    expect(core.revision()).toBe(revBefore);
    expect(broadcasts).toEqual([]);
  });
});

// event-generate-hardening task 1.2 (gate ruling E3) — the route's JS
// isAuto predicate (isAutoGeneratedMetadataJson, exported from
// routers/events.ts) and the event store's SQL predicate must agree on
// every metadata_json value in this corpus: two implementations, one
// tested meaning.
describe('JS↔SQL auto-generated predicate parity (gate ruling E3)', () => {
  const corpus: Array<{ label: string; metadataJson: string; expected: boolean }> = [
    { label: 'true (JSON boolean)', metadataJson: '{"auto_generated":true}', expected: true },
    {
      label: 'true with extra keys',
      metadataJson: '{"auto_generated":true,"auto_generate_run_id":"r1"}',
      expected: true,
    },
    { label: 'false', metadataJson: '{"auto_generated":false}', expected: false },
    { label: 'number 1', metadataJson: '{"auto_generated":1}', expected: false },
    { label: 'string "true"', metadataJson: '{"auto_generated":"true"}', expected: false },
    { label: 'missing key', metadataJson: '{}', expected: false },
    { label: 'empty string (defaults to {})', metadataJson: '', expected: false },
    { label: 'malformed JSON', metadataJson: '{"auto_generated":true', expected: false },
    { label: 'JSON array (not an object)', metadataJson: '[true]', expected: false },
    { label: 'JSON null', metadataJson: 'null', expected: false },
  ];

  it.each(corpus)('$label → $expected, agreeing across JS and SQL', ({
    metadataJson,
    expected,
  }) => {
    // JS side: the exact route predicate.
    expect(isAutoGeneratedMetadataJson(metadataJson)).toBe(expected);

    // SQL side: hasAutoGeneratedEvents() over a single row carrying this
    // metadata — the same predicate deleteAutoGeneratedEvents() uses.
    const { core } = fakeRuntime();
    core.db.run(
      `INSERT INTO events
         (id, wall_time_utc, frame_rate, timecode_total_frames, category, message, metadata_json)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      'row',
      '2026-06-25T00:00:00.000Z',
      24,
      0,
      'note',
      'row',
      metadataJson,
    );
    expect(new EventStore(core).hasAutoGeneratedEvents()).toBe(expected);
  });
});

// auto-generate-event-logs task 2.3 (design D4) — ONE insert path: addEvent
// gains an optional explicit-anchor parameter; when absent, behavior is
// byte-identical to today (pinned below over a real rolling transport), and
// when present the timecodeForMark derivation is bypassed entirely.
describe('addEvent over a real core', () => {
  /** Rolling transport at a known instant: roll started 5s before the fake
   * clock's default now (1_000_000ms), 50 frames already banked. */
  function rollingFixture() {
    const rt = fakeRuntime();
    rt.core.db.run(
      'UPDATE session_transport SET is_rolling = ?, current_take = ?, roll_started_at_utc = ?, elapsed_frames = ? WHERE id = 1',
      1,
      1,
      isoZ(new Date(995_000)),
      50,
    );
    return rt;
  }
  const ctx = { frameRate: 24, startOffsetFrames: 100 };

  describe('manual path (parameter absent) — byte-identical pin', () => {
    it('derives via timecodeForMark from the rolling transport at now(), broadcasts one event.changed', () => {
      const { core, broadcasts } = rollingFixture();
      const out = new EventStore(core).addEvent({
        category: 'note',
        message: 'hi',
        metadataJson: '',
        markedAtUtc: null,
        ctx,
      });
      // 100 offset + 50 elapsed + trunc(5s * 24fps) = 270
      expect(out.event).toEqual({
        event_id: out.event.event_id,
        wall_time_utc: '1970-01-01T00:16:40.000Z',
        timecode: formatSmpte(fromTotalFrames(270, 24)),
        frame_rate: 24,
        timecode_total_frames: 270,
        category: 'note',
        message: 'hi',
        metadata_json: '{}',
      });
      expect(out.projection.event_count).toBe(1);
      expect(out.projection.max_timecode_total_frames).toBe(270);
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
      // Pin the INSERT columns on the raw row, not just the RPC mapping.
      const r = core.first('SELECT * FROM events WHERE id = ?', out.event.event_id);
      expect(r).toEqual({
        id: out.event.event_id,
        wall_time_utc: '1970-01-01T00:16:40.000Z',
        frame_rate: 24,
        timecode_total_frames: 270,
        category: 'note',
        message: 'hi',
        metadata_json: '{}',
      });
    });

    it('honors markedAtUtc as the mark instant for both wall time and timecode', () => {
      const { core, broadcasts } = rollingFixture();
      const out = new EventStore(core).addEvent({
        category: 'note',
        message: 'marked',
        metadataJson: '{"a":1}',
        markedAtUtc: '1970-01-01T00:16:37.000Z', // 2s after roll start
        ctx,
      });
      // 100 offset + 50 elapsed + trunc(2s * 24fps) = 198
      expect(out.event.wall_time_utc).toBe('1970-01-01T00:16:37.000Z');
      expect(out.event.timecode_total_frames).toBe(198);
      expect(out.event.metadata_json).toBe('{"a":1}');
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
    });
  });

  describe('explicit anchor (design D4)', () => {
    it('stores the given frames + wall time verbatim, bypassing the transport derivation', () => {
      const { core, broadcasts } = rollingFixture();
      const out = new EventStore(core).addEvent({
        category: 'note',
        message: 'generated',
        metadataJson: '{"auto_generated":true}',
        markedAtUtc: null,
        ctx,
        explicitAnchor: {
          timecodeTotalFrames: 12345,
          wallTimeUtc: '2026-06-25T00:01:00.000Z',
        },
      });
      expect(out.event).toEqual({
        event_id: out.event.event_id,
        wall_time_utc: '2026-06-25T00:01:00.000Z',
        timecode: formatSmpte(fromTotalFrames(12345, 24)),
        frame_rate: 24,
        timecode_total_frames: 12345,
        category: 'note',
        message: 'generated',
        metadata_json: '{"auto_generated":true}',
      });
      expect(out.projection.event_count).toBe(1);
      expect(out.projection.max_timecode_total_frames).toBe(12345);
      expect(broadcasts).toEqual([{ type: 'event.changed', revision: 1 }]);
      const r = core.first('SELECT * FROM events WHERE id = ?', out.event.event_id);
      expect(r).toEqual({
        id: out.event.event_id,
        wall_time_utc: '2026-06-25T00:01:00.000Z',
        frame_rate: 24,
        timecode_total_frames: 12345,
        category: 'note',
        message: 'generated',
        metadata_json: '{"auto_generated":true}',
      });
    });

    it('stores frame_rate rounded from ctx exactly as the manual path does (29.97)', () => {
      const { core } = fakeRuntime();
      const out = new EventStore(core).addEvent({
        category: 'note',
        message: 'df',
        metadataJson: '',
        markedAtUtc: null,
        ctx: { frameRate: 29.97, startOffsetFrames: 0 },
        explicitAnchor: { timecodeTotalFrames: 60, wallTimeUtc: '2026-06-25T00:00:02.000Z' },
      });
      expect(out.event.frame_rate).toBe(29.97);
      expect(out.event.timecode).toBe(formatSmpte(fromTotalFrames(60, 29.97)));
      expect(out.event.metadata_json).toBe('{}');
    });

    it('rounds a >3-decimal ctx rate exactly like the manual path (23.976023976 → 23.976)', () => {
      // 29.97 is already 3-decimal, so it cannot detect a rounding divergence
      // between the explicit-anchor path and fromTotalFrames' millidecimal
      // rounding (Phase-2 review finding 3) — this rate can.
      const rate = 23.976023976;
      const { core } = fakeRuntime();
      const out = new EventStore(core).addEvent({
        category: 'note',
        message: 'ntsc-film',
        metadataJson: '',
        markedAtUtc: null,
        ctx: { frameRate: rate, startOffsetFrames: 0 },
        explicitAnchor: { timecodeTotalFrames: 24, wallTimeUtc: '2026-06-25T00:00:01.000Z' },
      });
      expect(out.event.frame_rate).toBe(23.976);
      expect(out.event.frame_rate).toBe(fromTotalFrames(24, rate).frame_rate);
      const r = core.first('SELECT frame_rate FROM events WHERE id = ?', out.event.event_id);
      expect(r).toEqual({ frame_rate: 23.976 });
    });

    it('still honors suppressBroadcast (same broadcast handling as the manual path)', () => {
      const { core, broadcasts } = fakeRuntime();
      new EventStore(core).addEvent({
        category: 'note',
        message: 'quiet',
        metadataJson: '',
        markedAtUtc: null,
        ctx,
        explicitAnchor: { timecodeTotalFrames: 1, wallTimeUtc: '2026-06-25T00:00:00.000Z' },
        suppressBroadcast: true,
      });
      expect(broadcasts).toEqual([]);
      expect(core.revision()).toBe(1); // revision still bumps
    });

    it('interleaves per wall_time_utc ASC among manual events in listEvents', () => {
      const { core } = fakeRuntime();
      const store = new EventStore(core);
      store.addEvent({
        category: 'note',
        message: 'first-manual',
        metadataJson: '',
        markedAtUtc: '2026-06-25T00:00:00.000Z',
        ctx,
      });
      store.addEvent({
        category: 'note',
        message: 'second-manual',
        metadataJson: '',
        markedAtUtc: '2026-06-25T00:02:00.000Z',
        ctx,
      });
      store.addEvent({
        category: 'note',
        message: 'generated-between',
        metadataJson: '',
        markedAtUtc: null,
        ctx,
        explicitAnchor: {
          timecodeTotalFrames: 24 * 60,
          wallTimeUtc: '2026-06-25T00:01:00.000Z',
        },
      });
      const out = store.listEvents({ limit: 10, offset: 0 });
      expect(out.events.map((e) => e.message)).toEqual([
        'first-manual',
        'generated-between',
        'second-manual',
      ]);
    });
  });
});
