-- session-content-policies spike, panel finding 4 (design A6, D1): the content policy's cost
-- against the number of sessions the user can access, for three policy forms. Generated by the
-- comment-documented loop below; run AFTER the draft migration in the same transaction, like
-- spike7b2.sql:
--
--   { echo 'begin; set local role postgres;'; \
--     cat openspec/changes/session-content-policies/spike/20261009000000_session_content_policies.sql \
--       openspec/changes/session-content-policies/spike/scale7b2.sql; } \
--     | docker exec -i autologger-dev-db-1 psql -U supabase_admin -d postgres -X -v ON_ERROR_STOP=0 \
--     | grep -E '^(N|V|S)[A-Za-z0-9 =_.:-]*|Planning Time|Execution Time|ERROR'
--
-- Everything ends in ROLLBACK. For each total session count N (300, 3,000, 20,000; extra
-- sessions are added to the fixture session's show, so the owner can access all N) and each policy
-- form ('set': the first draft's `accessible_sessions` set; 'exists': the chosen
-- correlated exists; 'definer': a per-row definer boolean), it recreates the user policy on session_meta, session_events and
-- session_transcript_words, then runs as the owner, each twice (the second is reported):
--   S1 a one-row session_meta insert; S2 a listEvents-sized read (200 rows of a session holding
--   250 events, ordered, plus the count); S3 a 31,621-row session_transcript_words insert.
\pset footer off
reset role;
select s.id as sid, m.user_id as owner
  from catalog.sessions s
  join catalog.shows sh on sh.id = s.show_id
  join catalog.user_studio_memberships m on m.studio_id = sh.studio_id and m.role = 'owner'
 order by s.id limit 1 \gset
select show_id as show from catalog.sessions where id = :'sid' \gset

-- (set) the first draft's helper: the ids of every session of the user's accessible shows.
set local role postgres;
create or replace function catalog.accessible_sessions(uid text) returns setof text
  language sql stable security definer
  set search_path = pg_catalog, pg_temp
  set enable_seqscan = off
  as $$ select s.id from catalog.sessions s
        where s.show_id in (select catalog.accessible_shows(uid)) $$;
revoke all on function catalog.accessible_sessions(text) from public;
grant execute on function catalog.accessible_sessions(text) to catalog_user;
-- (definer) a per-row boolean helper that reads the user id itself.
create or replace function catalog.session_accessible(sid text) returns boolean
  language sql stable security definer
  set search_path = pg_catalog, pg_temp
  set enable_seqscan = off
  as $$ select exists (select 1 from catalog.sessions s
                        where s.id = sid
                          and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))) $$;
revoke all on function catalog.session_accessible(text) from public;
grant execute on function catalog.session_accessible(text) to catalog_user;
reset role;

-- 250 events in the fixture session (as catalog_system).
set local role catalog_system;
insert into catalog.session_events (session_id, id, wall_time_utc, frame_rate, category, message)
  select :'sid', 'spike-ev-' || g, '2026-10-03T00:00:' || lpad((g % 60)::text, 2, '0') || 'Z', 24, 'Note', 'm'
    from generate_series(1, 250) g;
reset role;

\echo N 300
set local role catalog_system;
insert into catalog.sessions (id, show_id)
  select 'spike-sess-' || g, :'show' from generate_series(1, 300) g;
reset role;
analyze catalog.sessions;
\echo V set N 300
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert set 300 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-300-1', '1');
\echo S2 events read set 300 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 300 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert set 300 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-300-2', '1');
\echo S2 events read set 300 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 300 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V exists N 300
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert exists 300 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-300-1', '1');
\echo S2 events read exists 300 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 300 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert exists 300 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-300-2', '1');
\echo S2 events read exists 300 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 300 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V definer N 300
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert definer 300 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-300-1', '1');
\echo S2 events read definer 300 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 300 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert definer 300 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-300-2', '1');
\echo S2 events read definer 300 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 300 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo N 3000
set local role catalog_system;
insert into catalog.sessions (id, show_id)
  select 'spike-sess-' || g, :'show' from generate_series(301, 3000) g;
reset role;
analyze catalog.sessions;
\echo V set N 3000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert set 3000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-3000-1', '1');
\echo S2 events read set 3000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 3000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert set 3000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-3000-2', '1');
\echo S2 events read set 3000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 3000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V exists N 3000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert exists 3000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-3000-1', '1');
\echo S2 events read exists 3000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 3000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert exists 3000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-3000-2', '1');
\echo S2 events read exists 3000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 3000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V definer N 3000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert definer 3000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-3000-1', '1');
\echo S2 events read definer 3000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 3000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert definer 3000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-3000-2', '1');
\echo S2 events read definer 3000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 3000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo N 20000
set local role catalog_system;
insert into catalog.sessions (id, show_id)
  select 'spike-sess-' || g, :'show' from generate_series(3001, 20000) g;
reset role;
analyze catalog.sessions;
\echo V set N 20000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (session_id in (select catalog.accessible_sessions(catalog.app_user_id()))) with check (session_id in (select catalog.accessible_sessions(catalog.app_user_id())));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert set 20000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-20000-1', '1');
\echo S2 events read set 20000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 20000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert set 20000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-set-20000-2', '1');
\echo S2 events read set 20000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert set 20000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V exists N 20000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id())))) with check (exists (select 1 from catalog.sessions s where s.id = session_id and s.show_id in (select catalog.accessible_shows(catalog.app_user_id()))));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert exists 20000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-20000-1', '1');
\echo S2 events read exists 20000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 20000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert exists 20000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-exists-20000-2', '1');
\echo S2 events read exists 20000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert exists 20000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
\echo V definer N 20000
set local role postgres;
drop policy if exists session_meta_user_all on catalog.session_meta;
create policy session_meta_user_all on catalog.session_meta for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_events_user_all on catalog.session_events;
create policy session_events_user_all on catalog.session_events for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
drop policy if exists session_transcript_words_user_all on catalog.session_transcript_words;
create policy session_transcript_words_user_all on catalog.session_transcript_words for all to catalog_user using (catalog.session_accessible(session_id)) with check (catalog.session_accessible(session_id));
reset role;
set local role catalog_user;
select set_config('app.user_id', :'owner', true) is not null as bound;
\echo S1 meta insert definer 20000 run 1
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-20000-1', '1');
\echo S2 events read definer 20000 run 1
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 20000 run 1
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
\echo S1 meta insert definer 20000 run 2
explain (analyze, summary, timing off, costs off) insert into catalog.session_meta (session_id, key, value) values (:'sid', 'spike-definer-20000-2', '1');
\echo S2 events read definer 20000 run 2
explain (analyze, summary, timing off, costs off) select * from catalog.session_events where session_id = :'sid' order by wall_time_utc, id limit 200;
explain (analyze, summary, timing off, costs off) select count(*) from catalog.session_events where session_id = :'sid';
\echo S3 words insert definer 20000 run 2
savepoint s3;
explain (analyze, summary, timing off, costs off) insert into catalog.session_transcript_words (session_id, id, word, ordinal, created_at_utc) select :'sid', 'w' || g, 'word', g, '2026-10-03T00:00:00Z' from generate_series(1, 31621) g;
rollback to savepoint s3;
reset role;
rollback;
