// event-metadata-reserved-keys task 1.2 — unit tripwire: the exported strip
// list must superset the key the JS auto predicate (and the SQL predicate it
// is parity-pinned to, eventStore.test.ts) actually reads. Guards against the
// constant silently drifting out of sync with the predicate if either is
// edited later (design.md's "key-literal drift" residual).

import { describe, expect, it } from 'vitest';
import { AUTO_GENERATION_RESERVED_METADATA_KEYS, isAutoGeneratedMetadataJson } from './events';

describe('AUTO_GENERATION_RESERVED_METADATA_KEYS', () => {
  it('contains the key the auto predicate reads', () => {
    expect(isAutoGeneratedMetadataJson('{"auto_generated":true}')).toBe(true);
    expect(AUTO_GENERATION_RESERVED_METADATA_KEYS).toContain('auto_generated');
  });

  it('also contains the companion run-id attribution key', () => {
    expect(AUTO_GENERATION_RESERVED_METADATA_KEYS).toContain('auto_generate_run_id');
  });
});
