// event-metadata-reserved-keys task 1.2 — unit tripwire: the exported strip
// list must superset the key the JS auto predicate (and the SQL predicate it
// is parity-pinned to, eventStore.test.ts) actually reads. Guards against the
// constant silently drifting out of sync with the predicate if either is
// edited later (design.md's "key-literal drift" residual).
//
// persistence-package-extraction task 4.1: isAutoGeneratedMetadataJson moved
// to @autologger/domain (its own direct unit coverage lives there now,
// packages/domain/src/eventMetadata.test.ts); this file still imports it
// directly to pin the reserved-keys/predicate relationship described above.

import { isAutoGeneratedMetadataJson } from '@autologger/domain';
import { describe, expect, it } from 'vitest';
import { AUTO_GENERATION_RESERVED_METADATA_KEYS } from './events';

describe('AUTO_GENERATION_RESERVED_METADATA_KEYS', () => {
  it('contains the key the auto predicate reads', () => {
    expect(isAutoGeneratedMetadataJson('{"auto_generated":true}')).toBe(true);
    expect(AUTO_GENERATION_RESERVED_METADATA_KEYS).toContain('auto_generated');
  });

  it('also contains the companion run-id attribution key', () => {
    expect(AUTO_GENERATION_RESERVED_METADATA_KEYS).toContain('auto_generate_run_id');
  });
});
