// Entry point for `npm run build -w web-docs`'s `prebuild` step and
// `npm run dev -w web-docs`'s `predev` step (task 6.3; spec "web-docs is a
// static workspace" — "`atlas.json` SHALL be a git-ignored artifact
// regenerated by every build and dev-server start"). Both share
// `scripts/check.ts`'s `runAllGates()` (the SAME extraction/gate battery
// `docs:check` runs) so `atlas.json` is never written from a different code
// path than the one that validated it.
//
// `--strict` distinguishes the two callers' failure semantics:
//   - `prebuild` (this file with `--strict`): a hard failure, matching
//     `npm run build -w web-docs` being one of the spec's "exactly two"
//     entry points where every drift gate SHALL execute and exit non-zero
//     on violation ("Live-repo drift gates run at build and via
//     docs:check").
//   - `predev` (this file with no flag): best-effort — `atlas.json` is
//     still written (so the dev server has *something* fresh to serve) but
//     violations are printed as warnings, not a failing exit. Dev-server
//     start is deliberately NOT one of the spec's two required hard-gate
//     entry points (design.md D4's "Where they run" ruling: the two are
//     `npm run build -w web-docs` and `docs:check`) — a developer mid-fix
//     on an architectural violation should still be able to run the dev
//     server and see the (possibly-inaccurate) site, not be blocked from
//     starting it at all.
import { fileURLToPath } from 'node:url';
import { repoRoot } from '../src/lib/repo';
import { runAllGates, writeAtlasFile } from './check';

function isDirectRun(): boolean {
  return process.argv[1] === fileURLToPath(import.meta.url);
}

if (isDirectRun()) {
  const strict = process.argv.includes('--strict');
  const root = repoRoot();
  const { issues, atlas } = await runAllGates();
  writeAtlasFile(root, atlas);

  if (issues.length > 0) {
    const lines = issues.map((issue) => `  - ${issue}`).join('\n');
    if (strict) {
      console.error(
        `web-docs build failed with ${issues.length} drift gate violation(s):\n${lines}`,
      );
      process.exit(1);
    }
    console.warn(
      `web-docs: atlas.json regenerated, but ${issues.length} drift gate violation(s) exist ` +
        `(run "npm run docs:check" for the full list — dev server starting anyway):\n${lines}`,
    );
  } else {
    console.log('web-docs: atlas.json regenerated, all drift gates passed.');
  }
}
